### ISSUE TITLE
Bees cannot have both the wither and blaze attribute

### ISSUE THREAD

**Issue by CornyCobly** [Team-Resourceful/ResourcefulBees#10]
If I set up the JSON file like below, I would expect the bee to both set me on fire, and give me the wither effect. However it only sets me on fire. It also appears that the bees made with this file have an issue with their hitbox (I am unable to damage them with a sword, or by using splash potions). Trying the same thing with pigman bee and wither bee gives only one effect as well.

{
  "color": "#444444",
  "flower": "minecraft:wither_rose",
  "baseBlock": "minecraft:bedrock",
  "mutationBlock": "minecraft:dirt",
  "mainOutput": "minecraft:charcoal",
  "spawnInWorld": true,
  "biomeList": "tag:NETHER",
  "maxTimeInHive": 600,
  "witherBee": true,
  "blazeBee": true,
  "netherBee": true,
  "breedable" : true,
  "parent1": "Wither",
  "parent2": "Diamond"
}

**Comment by Epic428** [comment]
Correct. It’s the way the logic is being run. The intention was that a bee would only ever have one value set to true. I can modify it so that If a bee has both traits it will apply both effects if you would like me to do so.

**Comment by Epic428** [comment]
As far as the hit box issue and the bees not taking damage I can look into that. That is def not intended. The only thing that is intended is that nether bees can’t take fire damage.

**Comment by ThatGravyBoat** [comment]
Fixed the blaze bees not being able to take damage. Fixed in commit `7ab75f1`
