### ISSUE TITLE
Custom bees breading item bug

### ISSUE THREAD

**Issue by Joshernoob** [Team-Resourceful/ResourcefulBees#100]
When adding a breading item leaving the "item:" tag at the start doesn't make an error show however stops the JEI built in plug in for breading. This can be bad for though unaware as it loads fine even though these items with the "item:" tag don't work.

**Comment by Epic428** [comment]
I’m not sure if I fully understand the issue here. Best to provide some examples and then I could see if it’s something I can fix.

**Comment by Joshernoob** [comment]
Best example I can give is from what I saw if you put on say item: minecraft:stone it shouldn't work because it has the "item: " part. But it does for the breeding section

**Comment by Joshernoob** [comment]
However as it still errors the JEI tabs for the mod are taken away and you can't bread until this is fixed

**Comment by Joshernoob** [comment]
What I mean by not error and error at the same time is that it shouldn't let me load and error ( the not error)  if I have wrong code in the breading section. But then bugs when world loads (error(

**Comment by Epic428** [comment]
Send me examples of the files and what happens with each example so I know I’m following more clearly.

**Comment by Epic428** [comment]
Is this still an issue?

**Comment by Joshernoob** [comment]
This may still is a problem from what I'm aware of but not game breaking so if needed can be put on the back burner. And it's hard to put a files as only thing that stands out is the wrong code. But the bug is the code goes though even though it's wrong. I'll drop an bee json in a second anyway with the part explained in file

**Comment by Joshernoob** [comment]
[Inert_Crystal.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/5784799/Inert_Crystal.txt)
heres the file (made it wrong on purpose and added an explination in it as well, (you may need to change it to .json to test)

**Comment by Epic428** [comment]
Interesting. I will take a look into this further and see what I can figure out

**Comment by Epic428** [comment]
I do want to change it so that item:/block:/fluid: is the standard way of making the jsons but not until 1.17

**Comment by Epic428** [comment]
Found the tag:items: is a crafttweaker thing. May be implemented in 1.17
