### ISSUE TITLE
Enigmatica 6 - Icy Bee

### ISSUE THREAD

**Issue by Johannason** [Team-Resourceful/ResourcefulBees#101]
The Icy bee is a strange one in Enigmatica 6.  
Its info page does not show any preferred flowers, nor does it appear to produce any combs.  
But it can be bred with the Blaze bee to create an Obsidian bee!  
Except... it's breeding item is a snowball. Snowballs are thrown. I just beaned my Icy bee with a snowball, which enraged *all* my bees. The Blaze bee was teleported to who-knows-where by one of my armor enchantments, it's gone now.  
I can't figure out how to give snowballs to the Icy bee without smacking it, and i need the Obsidian bee to get to the Wither bee.

**Comment by Epic428** [comment]
E6 team will be rewriting quite a few of the bees I would wait to see if they fix this when they rewrite. There’s not really anything we can do to prevent the snowballs from being thrown as that’s the vanilla logic for them.

**Comment by Johannason** [comment]
That's fair. I only noticed after posting this, that the RB mod isn't responsible for individual bee types.  
I also found that an Apiary Breeder works just fine, effectively gating Obsidian and Wither bees behind a Nether Star.
