### ISSUE TITLE
Water Bottle instead of Honey Bottle

### ISSUE THREAD

**Issue by Tomatoh** [Team-Resourceful/ResourcefulBees#103]
Is there a way to output a water bottle using "bottleOutput" ? tried a few ways and I know the item code is minecraft:potion{Potion:"minecraft:water"}

**Comment by Epic428** [comment]
It probably isn’t working bc of the nbt tag and how our system is designed. Our recipe system is only setup to go based off the registry ID. I’ll have to look and see about incorporating nbt support to handle that kind of output.

**Comment by ThatGravyBoat** [comment]
Added in 84031640b04b2868671a5516be85f440257ebf4b
