### ISSUE TITLE
Honey bottles not obtainable on tier-1 beehives.

### ISSUE THREAD

**Issue by Simpleuser-git123** [Team-Resourceful/ResourcefulBees#104]
**Describe the bug**
I am not sure whether this should be a suggestion or a bug report, but I cannot use a bottle on tier-1 beehives to make honey bottles. Everything else works just fine like shearing the hive to get honeycombs, the only problem is the bottle.

1. Grab a glass bottle.
2. Click on a tier-1 beehive.

**Expected behavior**
I expected to hear the *plop* sound and the bottle to become a honey bottle, but it stays as a glass bottle instead.

![2021-01-01_21 03 22](https://user-images.githubusercontent.com/71519956/103450004-ab138580-4c75-11eb-857d-d4877240509a.png)

 - Forge 35.1.4
 - Version 0.5.7 beta

**Comment by ThatGravyBoat** [comment]
This is an intended feature as we want players to use the centrifuge to get their honey.
