### ISSUE TITLE
Bees wont go back in apiary they were imported in

### ISSUE THREAD

**Issue by SoulEvans07** [Team-Resourceful/ResourcefulBees#111]
**Describe the bug**
Bees imported into an apiary go out after "ticks left" reaches 0, gets pollen from required block then flies around without going back to the apiary.

**To Reproduce**
1. Create apiary with creative build function.
2. Add diamond block in the base of the apiary, inside the center of the floor.
3. Import diamond bee to apiary.
4. Unlock bee.
5. Wait for it to go out and collect pollen. 
6. See that it won't go back, even after 30 minutes.

**Expected behavior**
Bee go back into the apiary and leave combs in apiary storage.

**please complete the following information:**
 - All the mods 6 modpack, version 1.3.7
 - Forge Version: 1.16.4 - 35.1.13
 - Mod Version: 0.5.5b

**Additional context**
- I tried it with 9 bees, all did the same with a custom built structure, but I only tested the diamond one with the basic glass structure. I don't know if it's changes anything but after I picked the pollinated bee with the jar and put it back the apiary it produced combs but wouldn't go back the apiary again so I tried adding "fresh" bees thinking that maybe some meta data screwed my bees up, but still got the same results. 
- After reading [[1.16.4] Bees won't go in new hives if they're carrying pollen #110 ](https://github.com/Resourceful-Bees/ResourcefulBees/issues/110) I even removed all beehives from the area and tried with Tier 4 apiary too, but still didn't fix the issue.

**Comment by Epic428** [comment]
I’m literally in dev testing things and I can confirm that bees do in fact go back in the apiary as they are supposed to.

**Comment by Epic428** [comment]
fixed in d0e4f1d39dff5b113cae2c2b1add2d8157d65706
