### ISSUE TITLE
Water bees do not spawn in the world. I spent a dozen hours or so in rivers looking and only found 100s of mason bees. I'm playing atm6. I also noticed water bee isnt even listed in your wiki.

### ISSUE THREAD

**Issue by servireettueri** [Team-Resourceful/ResourcefulBees#113]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5']
 - Mod Version [e.g. '0.2.0']

**Additional context**

**Comment by Epic428** [comment]
That’s Bc our mod let’s pack devs build their own custom bees. Are you on the most recent version of the mod? If not update and it should be fixed though nests won’t spawn in already generated chunks.

**Comment by Rumaan3012** [comment]
I have found water bees on an official server in ATM6. It is a right PITA, but they are there. Follow some rivers and look for bee hives on the river.

**Comment by Vaerys-Dawn** [comment]
Pack related issues should be sent to the pack dev unless you are absolutely sure it's related to something the base mod does please don't report it here.

Closing issue. 

P.s. Atm6 water bees should spawn in river biomes, which you should be able to see via JEI.
