### ISSUE TITLE
Beehive upgrading

### ISSUE THREAD

**Issue by IminhaK** [Team-Resourceful/ResourcefulBees#116]
**Is your feature request related to a problem? Please describe.**
Sort of. It is sometimes frustrating to have to destroy a hive to upgrade it which risks angering bees or having to hope they all leave before you break it.

**Describe the solution you'd like**
An item that can be used on a hive to upgrade it to the next tier, keeping contents and bees. Crafted using the same materials as upgrading the hive but with a space in the middle where the hive would normally be or an "upgrade base" item

**Describe alternatives you've considered**
Maybe a way to lock a hive so bees do not go back into a specific hive so that it can be easily emptied then broken and upgraded?

Forgive me if I'm missing something major here.

**Comment by Vaerys-Dawn** [comment]
we're planning to get this in, hopefully before 1.17

**Comment by Epic428** [comment]
added in latest build
