### ISSUE TITLE
Apiary Bug

### ISSUE THREAD

**Issue by MassImpacter** [Team-Resourceful/ResourcefulBees#117]
Hi i playing whit ATM6 and i built a tier 4 apiary(the structure is valid) and the bees dose not seem to go back to the apiary automaticly after 
pollination! I don't know if it's a bug or just i did somthing worng!

Thanks in advance!

**Comment by mthp1999** [comment]
I have this aswell, I am guessing that it was fixed in the update that came out a couple days ago, but atm6 has not updated the mod as of yet.

**Comment by Epic428** [comment]
Update the mod to 0.5.8b
