### ISSUE TITLE
Bees suffocate near walls

### ISSUE THREAD

**Issue by ChrumkaveKura** [Team-Resourceful/ResourcefulBees#122]
There is a bug where once the bee reaches adulthood, it displaces itself a little bit and if it's anywhere near any blocks, it get's stuck and suffocates.  All of the requirements are kept and there is no reason for it to suffocate other than the displacement. This way bees have to be placed somewhere else before they reach adulthood manually and have to be controlled every few minutes to see if they didn't suffocate which makes for a lot of unnecessary work

1. Breed bee.
2. Wait for bee to reach 1 sec to adulthood
3. Bee displaces itself lightly once reaching adulthood
4. Bee gets stuck in a block and dies

 - Forge Version 1.16.4 - 35.1.29
 - ResourcefulBees1.16.3-1.16.4-0.5.8b.jar

**Comment by ThatGravyBoat** [comment]
Sadly not much we can do as its a problem with vanilla for years https://bugs.mojang.com/browse/MC-9568
