### ISSUE TITLE
require chinese translation updata!

### ISSUE THREAD

**Issue by Holy-Fak** [Team-Resourceful/ResourcefulBees#123]
i am a chinese player, i really love is mod !!
then i found chinese lang doc been a long time didn't update.

and i took some time to do about this 

here is my chinese translation doc for latest version!

[zh_cn for resourceflubees.zip](https://github.com/Resourceful-Bees/ResourcefulBees/files/5822113/zh_cn.for.resourceflubees.zip)

![QQ20210116014211](https://user-images.githubusercontent.com/63405709/104760313-2445c900-579c-11eb-8db5-bc604a2d7fbf.png)

![QQ20210116014221](https://user-images.githubusercontent.com/63405709/104760327-29a31380-579c-11eb-9d67-d52659510cd2.png)

![QQ20210116014221](https://user-images.githubusercontent.com/63405709/104760340-2f005e00-579c-11eb-8d2d-8602387d5b66.png)

for better chinese players exprience!

**Comment by Epic428** [comment]
Awesome! Thank you! I will be sure to include it! 😁
