### ISSUE TITLE
Apiary Export bees back out, multiple clicks

### ISSUE THREAD

**Issue by akutamatata** [Team-Resourceful/ResourcefulBees#124]
**Is your feature request related to a problem? Please describe.**
Exporting bees, shift clicking the item will cause it to go into the Import slot, which you then have to click again to return to inventory.

**Describe the solution you'd like**
Shift clicking any of the slots in the GUI will return items to your inventory.

**Comment by Vaerys-Dawn** [comment]
definitely see how this can be annoying, may not be fixed in the next patch but it's on our radar

**Comment by ThatGravyBoat** [comment]
Fixed In dev 5eaab710c03fec042fe3649276f6725d226053ff
