### ISSUE TITLE
Bee Type searchable

### ISSUE THREAD

**Issue by akutamatata** [Team-Resourceful/ResourcefulBees#125]
**Is your feature request related to a problem? Please describe.**
Difficult to find and store bees.

**Describe the solution you'd like**
Make the filled bee jars searchable by bee type. Therefore storing bees in IronChests, Refined Storage, and Applied energetics, can be searched for and found.

**Comment by Vaerys-Dawn** [comment]
Theoretically possible if we change the name of the item on collect/spawn via breeding, will get back to you on that,

**Comment by Vaerys-Dawn** [comment]
should be possible in next major patch, bee jars now append the bee's name to the jar name, will display nickname of the bee if it has one instead
