### ISSUE TITLE
Apiary bred bees fail to load color

### ISSUE THREAD

**Issue by akutamatata** [Team-Resourceful/ResourcefulBees#126]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
When breeding bees in the apiary, they default to the color white rather than their type's color.

**To Reproduce**
1. Place two bees with their resource in an apiary, wait for them to breed
2. check apiary storage
3. Bee is colored white rather than any other - perhaps this is only for config added bees, I'll test and comment.

**Expected behavior**
1. in place of 3 from above: Bee is colored the correct type

**Screenshots or Crash Logs**
For this example, using the steps above I bred in ATM6 to get a allthemodium bee, and it was colored white, however if I release it and recapture or import it into an apiary - it will load the correct color.
![InInventory](https://user-images.githubusercontent.com/37421153/104855553-ccb27500-58e3-11eb-9684-9b37af7aab89.PNG)
![GlitchedBee](https://user-images.githubusercontent.com/37421153/104855414-0e8eeb80-58e3-11eb-9a90-4b98f05ed0b6.PNG)
![IntendedResult](https://user-images.githubusercontent.com/37421153/104855415-0e8eeb80-58e3-11eb-92e4-6e27ab427a69.PNG)
**please complete the following information:**
 - Forge Version 35.1.36
 - Mod Version 0.58b

**Comment by Epic428** [comment]
Is it only on the breed output that the jar isn’t colored correctly? I assume a piece of nbt data isn’t being applied causing the issue. ~~I would be willing to bet if you release the bee and capture it’ll be fine.~~ didn’t see the part where you said recapture was fine lol

**Comment by akutamatata** [comment]
It seems that it might be an issue with modded ones, obsidian was bred fine. Yeah it's on the breed output, exporting goes to another slot so nothing else 'produces' bee items in the apiary structure.

**Comment by akutamatata** [comment]
> Is it only on the breed output that the jar isn’t colored correctly? I assume a piece of nbt data isn’t being applied causing the issue. ~I would be willing to bet if you release the bee and capture it’ll be fine.~ didn’t see the part where you said recapture was fine lol

- ya I know it can be fixed, but it's clearly an unintended mechanic.

**Comment by Epic428** [comment]
No worries. I’ll check what tag I’m missing on the breed output so it works correctly. Thank you for the report!

**Comment by akutamatata** [comment]
> No worries. I’ll check what tag I’m missing on the breed output so it works correctly. Thank you for the report!

Thanks!

**Comment by Vaerys-Dawn** [comment]
fixed in dev
