### ISSUE TITLE
Glass bottle duplication in multiblock centrifuge

### ISSUE THREAD

**Issue by desp4life** [Team-Resourceful/ResourcefulBees#127]
As stated in the title, glass bottles are duplicated if less than 9 are provided when processing a honeycomb block with the multiblock centrifuge.

Steps to reproduce:
-Place less than 9, but at least one glass bottle in the centrifuge
-Add honeycomb block to process
-In the event a bottle of honey is created, it creates 9 regardless of input amount (does consume all input bottles)

Expected:
Either don't process at all if not enough empty glass bottles are provided or (preferably) make as many bottled outputs as empty glass bottles are provided for.

Details:
This was tested with 1 and 5 empty glass bottles (both yielded 9 output bottles). Tested using wither honeycomb block in ATM6 version 1.4.0, which includes version 0.5.8b of this mod.

Notes:
I have not tested this using other honeycomb blocks or available centrifuges provided by this mod, other than stated above.

**Comment by Epic428** [comment]
Hmmm nice catch! That’s an oversight on my part after rewriting the centrifuge logic.

**Comment by Vaerys-Dawn** [comment]
fixed in dev, will be out in the next major patch
