### ISSUE TITLE
[1.16.4] Smoker displays misleading animation with Resourceful Bees Hives

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#128]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/892

**Describe the bug**
The smoker displays a misleading particle effect when used on a resourceful bee hive where it shows the smoking particles when shift right clicked on a bee hive while hive isn't actually smoked. Just standard right clicking on a bee hive does smoke it, but it doesn't display the smoking particles.

**To Reproduce**
1. Place RB Beehive
2. Shift-right-click with a smoker - Observe particles, but the beehive is not smoked (the mod The One Probe makes this easier)
3. right-click with a smoker - Observe that it is smoked (the mod The One Probe makes this easier)

**Expected behavior**
For particles to show when correctly smoking the beehive

**please complete the following information:**
 - Forge-1.16.4-35.1.37
- ResourcefulBees1.16.3-1.16.4-0.5.8b

**Comment by Epic428** [comment]
Awesome I will have this fixed! Thank you!

**Comment by NielsPilgaard** [comment]
This is still an issue in `resourcefulbees-1.16.5-0.5.10b`:
- Right-clicking doesn't display smoke and hive is smoked. 
- Shift right-cliciking doesn't display smoke and hive is not smoked

**Comment by Epic428** [comment]
sneaking and right clicking won't smoke the hive however the smoke particles will now show correctly when right-clicking the hive. just made the fix in dev

**Comment by Epic428** [comment]
so gravy made some further tweaks and it now works with both sneak and normal right click
