### ISSUE TITLE
[1.16.4] Bees with sizeModifier 1.5 and above getting stuck in apiary walls

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#129]
**Describe the bug**
Larger bees seem to get stuck in the Apiary wall when they exit the apiary block and take suffocation damage (and eventually die). They also sometimes pop to the outside of the apiary enclosure due to getting stuck in the wall.

**To Reproduce**
1. Download Enigmatica 6 v0.3.6
2. Make a world, make an Apiary, put a Ghast bee in it
3. Wait for the Ghast bee to go into, and eventually out of the apiary block

**Expected behavior**
For the bee to stay inside despite being larger than normal

**please complete the following information:**
- Forge-1.16.4-35.1.37
- ResourcefulBees1.16.3-1.16.4-0.5.8b

**Additional context**
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/900

**Comment by Epic428** [comment]
This one is going to take some finessing to figure out a good solution. The bees should be spawning in the block space directly in front of the apiary entrance so I’m a bit curious how/why they are getting stuck in walls. Thank you for letting me know

**Comment by Dracos99** [comment]
maybe for the larger size bees, having them come out a number of blocks equal to their size multiplier (and if you cant do partial blocks, then round up)?

**Comment by Vaerys-Dawn** [comment]
closing, can not reproduce in dev, going to assume it's fixed? can you confirm this is still happening in patch 0.5.8b?

**Comment by NielsPilgaard** [comment]
I reported this with 0.5.8b, so yes.

**Comment by Vaerys-Dawn** [comment]
going to test this a bit more, just to be absolutely sure that this is fixed in dev, last thing we want is dead bees ;-;
