### ISSUE TITLE
Issues modifying default bees or creating new bees

### ISSUE THREAD

**Issue by bessiq** [Team-Resourceful/ResourcefulBees#13]
**Describe the bug**
- Renaming default bees does not display their name correctly in-game, as indicated in the screenshot. (In this example, I changed Coal.json to Sooty.json and Skeleton.json to Skeletal.json.) Also, their associated honeycombs/blocks are named incorrectly in JEI.
- New custom bees are not spawning in the world. (Attached their json files for review.)

**To Reproduce**
1. Set `generateDefaults = false` in resourcefulbees\common.toml.
2. Rename default bee json file (e.g. Gold.json to Golden.json).
3. Create new bee json file.
4. Bump up spawn weight to find bees more quickly, since idk how to summon any but the default bee.
5. Check JEI for associated honeycombs/blocks.

**Expected behavior**
- Customized bee names and associated honeycomb/block names display in-game properly.
- New custom bees should spawn in the world, and their honeycombs/blocks should be displayed in JEI.

**Screenshots**
![2020-06-04](https://user-images.githubusercontent.com/7315505/83822424-fd200880-a69e-11ea-8236-aac236831789.png)

**please complete the following information:**
 - Forge Version: 1.15.2 - 31.2.5
 - Mod Version: 0.2.2a

**Additional context**

I followed your surprisingly good wiki (sorry, such a rarity these days), and I feel like my configs are correct. But I could've easily missed something, so any feedback is welcome. One thing I just noticed is the default bee files have `mutationInput` and `mutationOutput` as parameters, whereas I configured my new bees going by the wiki, which doesn't mention those but instead mentions `baseBlock` and `mutationBlock`. Would changing the files to use the input/output parameters maybe fix those new bees at least?

Custom bee files:
[bees.zip](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4733262/bees.zip)

**Comment by Epic428** [comment]
The wiki needs to be updated. You have an experimental jar file which has a lot of structural changes and as such the wiki isn't going to be helpful. I'm hoping by tomorrow at the latest I can have a new curse version which will have even more structural changes than the copy I last gave you. When i release the new version to curse the wiki will get updated to reflect the changes.

Basically it's much better to create a new world and start from scratch with this newer update I'll be pushing. Goal is to get as much of the structural core changes out of the way now so future updates are far less likely to break something.

**Comment by Epic428** [comment]
In the mean time. yes you will need to change to `mutationInput` and `mutationOutput`. you will also need to specify two color variants for each bee if they use the dual color system. In addition bee skins won't work in your version but will in release. To fix the bee names displaying incorrectly: Every single bee will need to have a lang entry there's a spot on the wiki for it. We also will be releasing a web page where you can create new bees and download the json file with the data formatted correctly to minimize issues and make it easier. 

EDIT:

we also have a discord too. link is on the mod's curse page. you can get more immediate assistance there as well.

**Comment by bessiq** [comment]
Awesome, thanks for your help and sorry to keep bugging you! And I see the Language Files page now - I feel like a _derp_. I just automatically assumed it was something for localization.

And don't worry, I usually make a fresh world every time I restart the pack. I've changed the mutation parameters and will start working on the language files soon. The web page idea sounds cool, too!
