### ISSUE TITLE
Unable to make custom bees that produce resources from Mana and Artifice

### ISSUE THREAD

**Issue by blewbelle** [Team-Resourceful/ResourcefulBees#130]
The Custom Bee Feature is incompatible with Mana and Artifice due to the FirstPhaseValidator rejecting M&A's namespace "mana-and-artifice" because it contains hyphens, which are not included in the regex \w.

According to the minecraft wiki, hyphens are allowed in the namespace.

**To Reproduce**
1. Create a custom bee
2. Set any field that accepts items to an item from mana-and-artifice
3. Launch the game
4. Observe that mod loading has failed

**Expected behavior**
Not crashing

**Screenshots or Crash Logs**
![image](https://user-images.githubusercontent.com/10690571/104863994-b61d1580-5905-11eb-82d2-de7d1d66be94.png)

**please complete the following information:**
 - Forge Version [35.1.37]
 - Mod Version [0.5.8b]

**Comment by Epic428** [comment]
I am aware of the issue and need to change the regex to handle the hyphens in their ~~unstandardized~~ unconventional mod name.


edit: hmmm did not know hyphens were actually allowed.....

**Comment by Vaerys-Dawn** [comment]
closing, should be fixed in the next major patch see: #131
