### ISSUE TITLE
Interacting with Multiblock centrifuge uses Items

### ISSUE THREAD

**Issue by akutamatata** [Team-Resourceful/ResourcefulBees#132]
**Describe the bug**
When interacting the a centrifuge multiblock without an empty hand your player will attempt to use what is in their hand. If you have a block it will place it but quickly unplace. If you have food it will start eating and continue eating. If you have an ender pearl it will use the pearl and teleport you.

**To Reproduce**
1. Interact with a centrifuge multiblock when eating or placing a block, or with an ender pearl

**Expected behavior**
You open the GUI without using the item in hand

**please complete the following information:**
 - Mod Version 0.58b

**Comment by Epic428** [comment]
Interesting bc previously it would simply place the block. I’ll take a look at it again and see why it’s doing this now 🤔
