### ISSUE TITLE
Serious bugs in the multi-block centrifuge

### ISSUE THREAD

**Issue by KuroPeach** [Team-Resourceful/ResourcefulBees#133]
When the sorting of quark is turned on, they will be combined to brush any items. Quark seems to be planning to block the display of sort buttons on the centrifuge interface. I think the root of this problem lies in the centrifuge. The quark shielded centrifuge is only a temporary solution, not a permanent solution. [Quark#2881](https://github.com/Vazkii/Quark/issues/2881)
Maybe the description is not correct, my English is not good, sorry
![1610590358_10167_tWss](https://user-images.githubusercontent.com/19620848/104537851-b2636780-5655-11eb-953e-ed661d9d5d67.gif)
[imgur](https://imgur.com/a/RkARIao)

**Comment by Epic428** [comment]
so is that sort button only supposed to sort the player inventory and somehow it is also pulling from the centrifuge?? I'm trying to make sense of what is actually causing this bug so I can fix it.

**Comment by akutamatata** [comment]
> so is that sort button only supposed to sort the player inventory and somehow it is also pulling from the centrifuge?? I'm trying to make sense of what is actually causing this bug so I can fix it.

Likely what is happening is somehow the sort mod is sorting the items, attempting to put it into the inventory of the block and then placing it back into the inventory of the player. Perhaps allowing items to be put into the Output section, or moved around would fix this?

**Comment by KuroPeach** [comment]
By the way, the player can put any item in the centrifuge input grid, I forgot to mention it before

**Comment by Epic428** [comment]
That is by design bc you can make data pack recipes for the centrifuge

**Comment by NielsPilgaard** [comment]
> so is that sort button only supposed to sort the player inventory and somehow it is also pulling from the centrifuge??

It's a button that pulls all items out of the inventory that has the button. It tends to cause dupes.

**Comment by Epic428** [comment]
Ah ok. I’ll have to look into it a bit more at some point. For now it seems Vazkii has the centrifuges added to the blacklist so the button doesn’t show up.

**Comment by KuroPeach** [comment]
player find new bug, Use botania's digging lens to destroy the centrifuge, Can get double the items in the input slot. 


![QQ图片20210128234309](https://user-images.githubusercontent.com/19620848/106162799-77b80e00-61c3-11eb-8ad8-88dcc72b9a4d.png)
![QQ图片20210128234316](https://user-images.githubusercontent.com/19620848/106162812-7ab2fe80-61c3-11eb-9fe2-f8477d59e131.png)
![QQ图片20210128234324](https://user-images.githubusercontent.com/19620848/106162821-7be42b80-61c3-11eb-875c-42c2187c5995.png)
![QQ图片20210128235143](https://user-images.githubusercontent.com/19620848/106163143-cfef1000-61c3-11eb-91ec-c622fd9e7f0b.png)

**Comment by Epic428** [comment]
Can you provide a bit more context as to exactly what’s happening? I’ve never used botania as a quarry so never used the digging lens. Just trying to understand it a bit better

**Comment by Epic428** [comment]
Based on the screenshots I’m assuming the axe is being spit out of the centrifuge but because the centrifuge stores it’s inventory when it is broken so when you place it back down there’s a second copy of the axe in the centrifuge. Am I following correctly? I can double check the loot table for the centrifuge is right but it almost seems to me like it’s a bug on botania side esp if normally breaking the block doesn’t produce the same result

**Comment by KuroPeach** [comment]
I also rarely use this lens. Its role seems to be to accurately collect blocks. This player uses it to destroy the centrifuge. The centrifuge will retain the NBT, but the items in the input slot will fall out. There is also one in the centrifuge with NBT.

**Comment by Epic428** [comment]
Yeah so that seems more like a botania bug to me. I’ll double check everything on our end just to make sure.

**Comment by KuroPeach** [comment]
ok we shuld @Vazkii ：）

**Comment by Epic428** [comment]
You don’t happen to know that actual name of the lens offhand do you? I looked in botania code for digging lens but I don’t see a digging lens

**Comment by KuroPeach** [comment]
After thinking about it, we can add a judgment to the centrifuge, and do not allow the input of items that do not conform to the synthetic formula, so as to eliminate such bugs

**Comment by Epic428** [comment]
I’m not exactly sure what you said lol

**Comment by KuroPeach** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/common/item/lens/LensMine.java

Sorry, my English is not very good, sometimes the translation software is not very accurate

**Comment by Epic428** [comment]
Ah ok I got it. No worries. Thanks for link too!

**Comment by RoyalReject** [comment]
Weird question how do you get so many inputs in the centrifuge

**Comment by Epic428** [comment]
> Weird question how do you get so many inputs in the centrifuge

What does this have to do with the GitHub issue?

**Comment by draganot** [comment]
Found a similar bug, whenever you use that sort inventory button directly on the centrifuge it doubles any items in the centrifuge input slots.

https://user-images.githubusercontent.com/35406024/108361173-c0a62580-71b7-11eb-8fe1-d48988363ad4.mp4

**Comment by ThatGravyBoat** [comment]
we could not find how this was happening and quark added the centrifuges to the ignore list so you can add the screens to the list yourself by copying it from the default quark config

**Comment by Epic428** [comment]
Closing this due to blacklist configs added to quark

**Comment by frank89722** [comment]
This issue still happened when using quark inventory sort, quark inv sort can bind on a hotkey.
![r](https://user-images.githubusercontent.com/10683361/119254408-b6e1f300-bbe8-11eb-943f-32f7cec6076e.gif)

**Comment by Epic428** [comment]
If the classes are set in the configs properly then you will need to make an issue on quarks github advising them that their key bind doesn’t respect the config. I have no clue why it happens and why they needed to add us to a blacklist config and when I asked how I could resolve the issue I was given no response.
