### ISSUE TITLE
Adding biomes to bee information

### ISSUE THREAD

**Issue by Finnchen123** [Team-Resourceful/ResourcefulBees#134]
**Is your feature request related to a problem? Please describe.**
I personally like searching the world for bees and I rly enjoy this mod but when I search for hours and don't find the bee I'm looking for it is rly frustrating. After that I search the config for this bee and look up the biome or biome type I need to find.

**Describe the solution you'd like**
I would like the biomes to bee listed when a bee spawns in the world. Just adding another row with this information could bee rly helpful.
**Describe alternatives you've considered**
I mean it is not rly an alternative but my idea is not rly necessary. It can bee omitted if other things are more important or it is intended to search all life long.

**Additional context**
I absolutely love this bee mod * happy bee noises *.

**Comment by ThatGravyBoat** [comment]
If you look at the bee in JEI it already tells you what biomes it spawns in

**Comment by ThatGravyBoat** [comment]
You just have to click on the bee in JEI

**Comment by Finnchen123** [comment]
Thx for helping me out. I rly should learn to look at my screen properly. My brain just automatically removed the JEI arrows at the top but I found them now :)
