### ISSUE TITLE
Reduce Storage blocks

### ISSUE THREAD

**Issue by Dracos99** [Team-Resourceful/ResourcefulBees#135]
**Is your feature request related to a problem? Please describe.**
Multiple apiary storage blocks connected randomly to an equal number of apiary blocks starts to get crowded and looks bad.

**Describe the solution you'd like**
I would like multiple Apiary blocks to interface with a single storage block. Then give the upgrades the ability to expand the number of apiaries it can connect to.

**Describe alternatives you've considered**
An alternative to the upgrade items would be tiered storage blocks that could connect to multiple apiaries while leaving the upgrades unchanged.

**Comment by Epic428** [comment]
This probably won’t happen. Because the blocks link together so you can switch between their gui’s. It would make it impossible to know which apiary the button should go to if it could be linked to multiple.

**Comment by Dracos99** [comment]
understandable with the existing implementation. A solution to the button could be changing the button to tabs or a list of apiaries connected, but that might lead to a whole gui redesign where the entire multiblock is interacted with as a single structure and apiaries/storage/breeding blocks just have a additive effect on the single pane of gui

**Comment by Vaerys-Dawn** [comment]
closing, like oreo said, this probably wont happen because of how our apiary system works, if we decide to rework them in the future we may choose to allow this, but don't get your hopes up.
