### ISSUE TITLE
bees being angry

### ISSUE THREAD

**Issue by blackwing12344** [Team-Resourceful/ResourcefulBees#136]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
whenever you break a tiered beehive, smoked or not, the bees will get angry, sting you, and die. I tried it with the smoker and a campfire and neither work.

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5']
 - 1.16.4
 - Mod Version [e.g. '0.2.0']
from modpack All The Mods 6
**Additional context**

**Comment by Vaerys-Dawn** [comment]
NAB https://minecraft.gamepedia.com/Tutorials/Honey_farming#Avoiding_Bee_Anger

you can break a hive with silk touch and that will pick the hive up with the bees inside and not cause anger. other than that, you need to make sure no bees are around before breaking hives.
