### ISSUE TITLE
Items "dissapear" when piping into apiary breeder

### ISSUE THREAD

**Issue by Vaerys-Dawn** [Team-Resourceful/ResourcefulBees#137]
**Description:**
When you hopper in items to the apiary breeder it'll put the items in slots that may not be rendered,

**Reproduction Steps:**
1. create apiary
2. add apiary breeder
3. fill input item stacks
4. place hopper or other method or piping in items
5. if no breeder upgrades are inputted, the items will look like they are vanishing
6. when placing breeder upgrades in, the items are now in other inventory slots, in my case they were in the jar slots

**Expected behavior**
1. no items other than bee jars should be allowed in their respective slots
2. when no breeder upgrades are added, no items should be allowed to be piped into the breeder unless it fills a visible slot

**Screenshots or Crash Logs**
https://i.imgur.com/CnqBc35.gif

**Versions:**
 - Forge Version [e.g. '1.16.4- 35.1.32']
 - Mod Version [e.g. '1.16.4-0.5.9b - NBT_mutation branch']

**Comment by Epic428** [comment]
Hmmm something must be off with the inventory... it’s been a while since I did this and it likely deserves a clean up. The whole apiary could use a bit of a rewrite tbh

**Comment by Vaerys-Dawn** [comment]
fixed in dev
