### ISSUE TITLE
Removing bee json keeps bee in apiary

### ISSUE THREAD

**Issue by Pdiddy973** [Team-Resourceful/ResourcefulBees#138]
**Describe the bug**
When removing a bee json, if it is in a apiary before you remove it. Will be stuck in the apiary after it was removed. Making the bee unable to be removed from the apiary and taking up one of the slots permently.

**To Reproduce**
1. Make sure bee to remove is in apiary
2. Remove bee json from config
3. Bee is now not removable from apiary
4. Re adding json will allow you to remove it and work normally again

**Expected behavior**
When removing bee json, it would remove the bee and not get stuck

**please complete the following information:**
 - Forge Version [not sure can look when I can]
 - Mod Version [.5.8b]

**Comment by Epic428** [comment]
That should be a pretty simple fix
