### ISSUE TITLE
Some random feature ideas

### ISSUE THREAD

**Issue by bessiq** [Team-Resourceful/ResourcefulBees#14]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solutions you'd like**
- If configured, some bees can emit light. I know moving light sources has always been a problem to pull off, so I understand it might not be feasible. But if not, maybe bees could have some kind of effect similar to the enchanted item effect, possibly with color variants like Quark runes? I think the glowing potion effect would be kinda weird, but the ability to give bees potion effects in general might be neat!

- Spawn blocks: in addition to biome spawning, perhaps make it so a bee can only spawn on a certain block type? E.g. Wither Bees could be set to only spawn on Nether Bricks, so you'd only see them around Nether fortresses. Could also consider spawning based on registered structures, like minecraft:fortress?

- sizeModifier: I saw this parameter in the coal bee file, so can this can be used for any of them?

- Individual bee spawn weights: this seems like something you are probably already planning on, but thought I'd mention it. I know a kind of weighting can be achieved with the allowed biomes if anything.

Thanks for your consideration!

**Comment by ThatGravyBoat** [comment]
>sizeModifier

Yes the `sizeModifier` can be used on all bees the coal bee was just a bee that it was being tested on.
> Individual bee spawn weights
> Spawn blocks

For individual bee spawn weights and spawn blocks it would add a significant performance decrease due to the amount of checks we would have to do so we will not be doing that.

 > If configured, some bees can emit light.

We can look into but if it requires too much performance we will not be doing it.

Also can you clarify  the statement "but the ability to give bees potion effects in general might be neat!" because right now we give some of the bees potion effects and also have it so some of the bees give you potion effects like for example the wither bee will give you the wither effect if it attacks you.

**Comment by bessiq** [comment]
All fair points and understandable. Just out of curiosity, what is the min/max on the sizeModifier?

As far as the potion idea, it was just a random thought tbh. I've been messing with InControl a lot and it has a feature that allows you to spawn a mob with a potion effect, and you can also set the duration and strength. I don't know that I would really feel the need to config a bee with, say, Absorption III or Water Breathing, but like I said it was just a thought. :)

Appreciate the quick and thorough responses.

**Comment by ThatGravyBoat** [comment]
> what is the min/max on the sizeModifier?

The Min and Max is a min of 0.5 and a max of 2.0

As for the potion effect idea we'll leave this issue open as a feature request and look into later down the line but for now we will not be looking into adding potion effects for bees.

Thanks for the bug reports and feedback very appreciated 👍

**Comment by ThatGravyBoat** [comment]
There is currently a small problem with the size modifier where it will also increase the size in jei causing it to look weird in the jei gui.

**Comment by Epic428** [comment]
Jei size modifier issue has been fixed and is in release version.

**Comment by ThatGravyBoat** [comment]
Thanks for the suggestions 👍 
  - Glowing Bee Effect can be used in the next update.
  - Enchanted Bee Effect can also be used in the next update.
  - Individual Bee spawn weight is also going to be in the next update.
