### ISSUE TITLE
moving bees

### ISSUE THREAD

**Issue by Iplay2L8** [Team-Resourceful/ResourcefulBees#140]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Bees will not reset home hive if moved.  Requires tier 1 hive to be placed and bee to enter then leave to set home coordinates. if moving to tier 2-4 bee will not enter new hive. Must collect all bees in hive and replace with tier 1 and "set home" for each new bee then break hive and replace with tier 2-4 in exact spot tier 1 hive was in before releasing all bees set to the hive.
**To Reproduce**
1. place tier 1 hive and release bees.
2. collect bees and replace hive tier 2-4
3. bees will enter new hive.
4. collect bees
5. move the tier 2-4  hive to other x,y,or z coordinates bees.
6. bees will return to original x,y,z of tier 1 hive and look for hive
7. bees will NOT enter empty available tier 2-4 hives nearby
8. place tier 1 hive to other x,y,or z coordinates  bees will enter hive "reseting home coordinates"
9. repeate step 2  to upgrade hive tiers
**Expected behavior**
bees should either look for empty hive when respawned from bee jar. Or releasing bee by clicking hive should set home coordinates.
**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version forge-35.1.28
 - Mod Version ResourcefulBees1.16.3-1.16.4-0.5.8b

**Additional context**
used in Sky Bees modpack original resourcefulBees1.16.3-1.16.40.5.7b same problem
upgraded mod and problem still exists

**Comment by Epic428** [comment]
I think I’m following your reproduction steps properly and assuming I am it’s working as intended. Bees store the hive position in their nbt data. So they always try to go to that location. However if they don’t find a hive there it should reset itself to null and start looking for a new location.

**Comment by Iplay2L8** [comment]
they have not been i have to do it manually.  new bees spawned or breed find a new hive but one moved with a jar just keeps returning to the original spot and spinning.  tried by moving hive up and over 1 block and they could not pathfind to it

**Comment by Epic428** [comment]
Are they spinning around in circles where the flower used to be or where the hive used to be? In either case if the block at the position where the hive used to be is no longer a hive it should immediately stop trying to use that location and begin looking for a new one. I’ll do some testing in the morning and see if I can reproduce the issue.

**Comment by Epic428** [comment]
bees will now reset their flower and hive position when picked up with a jar which will alleviate this issue.
