### ISSUE TITLE
[0.5.8b] Manual centrifuge too loud

### ISSUE THREAD

**Issue by CurePindal** [Team-Resourceful/ResourcefulBees#141]
**To Reproduce**
The sound of the manual centrifuge is too loud and significantly above most other ingame sounds.
Would be nice if it could be made a tad more gentle. thx.

**Expected behavior**
Manual centrifuge sound volume ~25% lower

**please complete the following information:**
 - forge-1.16.4-35.1.37
 - ResourcefulBees1.16.3-1.16.4-0.5.8b

**Comment by Epic428** [comment]
I’ll fiddle around with the volume of the sound..... actually.. maybe I’ll make it a client Config option. The issue though is that it’s technically two sounds being played. It’s the lodestone and fence gate.

**Comment by Epic428** [comment]
OK so I was going to add a client config option but realized the sound is played for everyone from the server and client config would be useless. Also the sound volume is at 50% already and the fence gate close sound, specifically, is half the volume it normally is. As such the sound should be relatively quiet in comparison to other in-game sounds and no changes will be made. I would double check your setup and volumes in MC.
