### ISSUE TITLE
[1.16.5] Placing Apiary Storage using replacement spell client crash

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#142]
**Describe the bug**
Using an Ars Nouveau replace block spell to place an Apiary Storage block results in a client crash. 

**To Reproduce**
1. Make an Ars Nouveau Touch -> Replace spell using a Spellbook
2. Have an Apiary Storage block in your hotbar next to the Spellbook
3. Use the spell on a plank or similar
4. Client crashes

**Expected behavior**
I expected that the Apiary Storage Block replaced the Spruce Plank

**Screenshots or Crash Logs**
 https://gist.github.com/Flabort/50397672278c572909732e863b5376b3

**please complete the following information:**
 - Forge Version 1.16.5-36.0.10
 - Mod Version ResourcefulBees1.16.3-1.16.4-0.5.8b

**Additional context**

**Comment by Epic428** [comment]
Interesting it seems to be crashing on the apiary storage GUI and it’s crashing Bc a button is null which makes no sense..... I’ll have to fiddle with that mod and figure out what’s happening

**Comment by Epic428** [comment]
It's been some time but I was able to take a look at this and figure out the cause and a solution. It also affects several other blocks of ours and I just need to test a couple more to make sure I got all the problem ones before I can mark this closed.
