### ISSUE TITLE
Can't adjust rf input for centrifuge

### ISSUE THREAD

**Issue by Profilename1** [Team-Resourceful/ResourcefulBees#144]
In the config you can adjust the rf usage rate for the centrifuge but not the rf input rate. This means you can potentially set rf usage higher than it's possible for the centrifuge to take it, making it unusable.

**Comment by Vaerys-Dawn** [comment]
fixed in dev, thanks for letting us know, it's currently set at 100rf/t will be customisable in the next update (which may not come for a while unless we need to push out a bunch of bug fixes)

**Comment by Vaerys-Dawn** [comment]
might I suggest making the recipe times longer to compensate?
as the centrifuge energy costs are per tick not per recipe, so setting them to be longer will mean they need more energy to complete
