### ISSUE TITLE
Removing bee json issue

### ISSUE THREAD

**Issue by Pdiddy973** [Team-Resourceful/ResourcefulBees#145]
**Describe the bug**
similar issue as to #138 , but it is not fixed in the new version

**To Reproduce**
1. have bee go into apiary
2. remove bee json
3. bee is stuck in apiary still, and spamming console. seems about 1 per type removed a tick

**Expected behavior**
removed bees to not show in apiary, and no console spam

**Screenshots or Crash Logs**
the error is - [Server thread/WARN] [minecraft/EntityType]: Skipping Entity with id resourcefulbees:bronze_bee
**please complete the following information:**
 - Forge Version [36.0.13]
 - Mod Version [.5.9_2b]

**Additional context**
![BeeConsoleSpam](https://user-images.githubusercontent.com/68764896/106721147-4e87eb00-65d2-11eb-9c15-19108abfcd0d.gif)

**Comment by Pdiddy973** [comment]
already mentioned in the discord chat, but restarting the server does not resolve the issue.

**Comment by ThatGravyBoat** [comment]
Fixed in ef91349ce90b972de81ccff0caaf084b385231ea
