### ISSUE TITLE
Bees Taking damage when coming out of apiary

### ISSUE THREAD

**Issue by Pdiddy973** [Team-Resourceful/ResourcefulBees#146]
**Describe the bug**
Bees are taking damage when flying out of apiary 

**To Reproduce**
1. have bees go in/out apiary 
2. wait till it happens, does not always happen
3. see GIF

**Expected behavior**
bees to be protected at all costs

**please complete the following information:**
 - Forge Version [36.0.13]
 - Mod Version [.5.9_2b]

**Additional context**
![BeeDamage](https://user-images.githubusercontent.com/68764896/106727356-63b44800-65d9-11eb-86a1-1d88b3bc4342.gif)

**Comment by Vaerys-Dawn** [comment]
fixed in 1f1418eea8b7a6e3e2c1116808a41214eb60b4f8
