### ISSUE TITLE
Crash with custom bee

### ISSUE THREAD

**Issue by agentwolf88** [Team-Resourceful/ResourcefulBees#147]
I try to create a custom bee. What is the problem?

Custom bee https://paste.ee/p/KrSqF
Crash log https://paste.ee/p/BI7mQ

**Comment by Vaerys-Dawn** [comment]
Seems to be related to using colour names rather than colour codes, nothing seems to be broken on your end

in the mean time you can use #800080 for purple and #FFC0CB for pink

**Comment by Vaerys-Dawn** [comment]
@Epic428 i feel like this is crashing because the colour system isn't properly setting the colours after init and the invalid colours are causing a NPE

**Comment by Epic428** [comment]
I’ll have to do some testing with this one. I don’t understand why the color would be null. I looked through the crash log but it doesn’t really help other than pointing out a render issue.

**Comment by Epic428** [comment]
fixed in 0d826a12a0371f868ed5cf2d4c1ba08a33b0556c
