### ISSUE TITLE
Bee AI broken when two apiary blocks inhabit same x,z coordinate at different y levels

### ISSUE THREAD

**Issue by madkat** [Team-Resourceful/ResourcefulBees#149]
Resourceful Bees Version: 1.16.3-1.16.4-0.5.8b

When you build two apiaries in the same vertical space, the bees will always try to reach the apiary block at the lowest y coordinate. Any bees in a higher y position apiary multiblock become useless.

While reproducing, I ensured there was an air gap between the multiblock structures, just in case there was some edge case around shared sides:
![apiary_positions](https://user-images.githubusercontent.com/645840/107137455-a91a9300-68c1-11eb-801c-5801ce9989d0.png)

**Comment by Epic428** [comment]
Hmm I understand what’s happening. I’ll need to figure out a good way to handle it. It’s because all bees scan the blocks in the same order and the apiary is close enough that it can go in but it can’t get to it obviously. Just gotta figure out how to efficiently tell it to pick a different one Bc it can’t get to it.

**Comment by madkat** [comment]
I'm also trying to track down a different AI issue that seems tied to apiary blocks/positions. Any new bees imported into the apiary will never return to the apiary block, but existing bees continue to function. Removing and replacing the block in the same position will exhibit the same problem, as will putting any other apiary in that position. Moving positions seems to clear it up.

I have found this problem in several separate apiaries, but have not figured out what triggers the behavior. If I have a block with the problem again, would dumping NBT data be useful for triage?

**Comment by Epic428** [comment]
NBT of the bee in question would be useful to some extent. But I also need to look into a couple other random issues with the apiary as well so I’ll be doing a more thorough examination this weekend.

**Comment by Epic428** [comment]
I tried to reproduce this in dev but I couldn't get the bee to try and target the inaccessible apiary. I will continue to monitor this and see if I can work out a solution.
