### ISSUE TITLE
Bees Editor cuts off text

### ISSUE THREAD

**Issue by WenXin20** [Team-Resourceful/ResourcefulBees#15]
**Describe the bug**
The Bees Editor text is cut off in certain places.
My screen resolution is set to 1366 x 768.

**To Reproduce**
1. Set resolution to 1366 x 768
2. Go to [Bees Editor](https://dungeon-derps-development.github.io/Mods/ResourcefulBees/editor.html)

**Expected behavior**
Clear text, with no cut offs.

**Screenshots**
![Annotation 2020-06-06 111139](https://user-images.githubusercontent.com/12000593/83949331-c1915580-a7e8-11ea-8abf-15f04383d5c0.png)

**Comment by Epic428** [comment]
I'm not sure that can (or will) particularly be fixed. 1366x768 is an odd resolution these days that not many sites support directly from my understanding. I understand it is mostly used with small laptops. I'll continue to leave the issue open in case one of the other devs decides to try and add support. but with a massive amount of devices at 1080p+ resolution, support may not come. 

Edit: also sorry for the very late reply. I didn't make the bee editor, one of the other devs did and I've been focusing more on content updates and bug fixes on my side recently.

**Comment by WenXin20** [comment]
That's fine, I got a new laptop anyways that has a higher resolution, so feel free to close this. :)
