### ISSUE TITLE
With biome mods, bee nests spawn in weird places like middle of ocean

### ISSUE THREAD

**Issue by Odey555** [Team-Resourceful/ResourcefulBees#150]
**Describe the bug**
Bug nests spawn in ocean biome, right above surface of water.

**Expected behavior**
Bee nests should not spawn on water. 

**Screenshots or Crash Logs**
![image](https://user-images.githubusercontent.com/1361563/107291534-186dbf80-6a47-11eb-92ce-015ae3b568e2.png)

**please complete the following information:**
 - Forge Version [**forge-1.16.5-36.0.13**] 
 - Mod Version [**0.5.8b**]

**Additional context**
Using it in ATM6 modpack

**Comment by Epic428** [comment]
This is not a bug

**Comment by tehbiga** [comment]
Could you elaborate?

Why would floating bee hives in the middle of the ocean be a feature?

**Comment by Vaerys-Dawn** [comment]
see #143

**Comment by ThatGravyBoat** [comment]
we will be adding 3 stripped logs under so its not just floating there and looks like a bee made a nest on driftwood but it's a feature as it's used for bees that spawn in ocean biomes.

**Comment by tehbiga** [comment]
Thanks for the explanation!
