### ISSUE TITLE
resourcefulbees:ıcy_honeycomb_block

### ISSUE THREAD

**Issue by cembohan** [Team-Resourceful/ResourcefulBees#151]
I'm trying to install sky bees pack, the only problem I have is resourcefulbees cannot load properly. I tried going through files but I cannot find where the error is happening so I cannot fix it manually. If you can help me locate & fix it that would be great. I first loaded the modpack, then I tried installing the 1.16.4 version from resourcefulbees forge page, im still getting the same error. here is the screenshot of the related crash file: 
![Screenshot_8](https://user-images.githubusercontent.com/64208179/107525706-2860dd00-6bc8-11eb-94d5-ee449781827e.png)

**Comment by Epic428** [comment]
oooof I thought I got all these so this error wouldn't happen. It's crashing bc your computer language is set to Turkish and regex doesn't play nice with the dot-less `i`. you could remedy it temporarily by changing you language to English or any other language.

I'll see which strings I missed forcing to EN_US and have fixed for next update

**Comment by cembohan** [comment]
Alright I'm gonna try to load it with English. Thanks for the response

**Comment by Epic428** [comment]
I just went through and tweaked a ton more `.toLowerCase()` calls to force the text to english so this should no longer be an issue.
