### ISSUE TITLE
memory not updating 

### ISSUE THREAD

**Issue by djnugets** [Team-Resourceful/ResourcefulBees#154]
my skeleton bees (atm6) arnt updating their memorys

**Comment by Epic428** [comment]
A bit more context would be useful. This is akin to saying my foot hurts

**Comment by Vaerys-Dawn** [comment]
No its more akin to saying something hurts.

We don't where to start looking, i'd suggest pastebining your logs and give us reproduction steps for how you found this in the first place.

We also have a issue template which you didn't use, we need the mod version, the forge version and it would be best to also let us know what version of atm6 you are running.

**Comment by Epic428** [comment]
:p I've been looking into it on discord. but I agree it is more like saying "something hurts"

**Comment by Epic428** [comment]
closing per https://discord.com/channels/738561073916936333/738562486113927218/809629195776032778
