### ISSUE TITLE
Putting honey bottles in the generator just empties them

### ISSUE THREAD

**Issue by Random832** [Team-Resourceful/ResourcefulBees#155]
**Describe the bug**
Putting a honey bottle in the Honey Generator empties the bottle and puts the empty bottle in the output but does not produce any water or RF.

**To Reproduce**
1. Place a Honey Generator
2. Place honey bottles in the input slot

**Expected behavior**
Honey transferred into generator's fluid tank

**please complete the following information:**
 - Forge Version 1.16.5 - 36.0.22
 - Mod Version 0.5.9_3b

**Comment by Vaerys-Dawn** [comment]
could you please tell me which honey exactly it was?

**Comment by Vaerys-Dawn** [comment]
okay, nevermind testing shows basic honey bottles failing to fill, custom honey and catnip honey works fine
