### ISSUE TITLE
Cant Have 2 Same Bees in Same Apiary At A Time

### ISSUE THREAD

**Issue by Asian-Rabbit** [Team-Resourceful/ResourcefulBees#158]
The mod pack "Sky Bees" wont allow 2 bees of same species in the same apiary at the same time. 
If 1 is in the apiary it block same specie from entering.
I left 1 of its kind in for breeding and quick access, but it block the same specie to enter to deposit its honey. 
Due to this dilemma, i have to take them out to allow honey deposit to occur.
Any why of changing the config.
I'm not sure what the file is located or what its called

**Comment by Vaerys-Dawn** [comment]
Not a bug, this has never been a possibility, apiaries only allow one species a time, this is an intentional restriction
