### ISSUE TITLE
Bees not binding to nest

### ISSUE THREAD

**Issue by Floweynt** [Team-Resourceful/ResourcefulBees#159]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
Bees are not biding to nest

**To Reproduce**
1. Go use the skybees mod
2. breed bees
3. bees dont ever bind to nest

**Expected behavior**
bees bind to nest

**Screenshots or Crash Logs**
https://imgur.com/a/wlEaRIV

**please complete the following information:**
1.16.4 - forge-35.1.37

 - Mod Version [e.g. '0.2.0']

**Additional context**
The hive is not full

**Comment by Vaerys-Dawn** [comment]
Please update resourcefulbees to the latest version. 0.5.9_3b and if possible bring this up with the pack dev, any version of forge past 35.0.20 will break nests past t1

**Comment by Floweynt** [comment]
0.5.9_3b requires 1.16.5, im in 1.16.4

**Comment by Vaerys-Dawn** [comment]
it should work fine in 1.16.4

**Comment by Vaerys-Dawn** [comment]
wait... do i have to smacc oreo?

**Comment by Vaerys-Dawn** [comment]
well in any case 0.5.8b should work fine, it has the fix needed for those hives

**Comment by Floweynt** [comment]
Any reason why forge ver > 35.0.20 breaks? I have to go change a lot of mods to actually change forge version

**Comment by Vaerys-Dawn** [comment]
@Epic428

**Comment by Vaerys-Dawn** [comment]
also 0.5.8b should def run on 1.16.4

**Comment by Floweynt** [comment]
yea it works, some other mods dont

**Comment by Vaerys-Dawn** [comment]
leave the other mods/forge version in the pack as is, update resourcefulbees to 0.5.8b, that's all you should need to do

**Comment by Floweynt** [comment]
The mod was on 0.5.8b before

**Comment by Vaerys-Dawn** [comment]
are you sure it wasn't on 0.5.7b as that is the issue that has bees not using hives past t1

**Comment by Floweynt** [comment]
oh well, lemme try with 0.5.8b

**Comment by Floweynt** [comment]
turns out, another mod is messing with it lol

**Comment by Epic428** [comment]
The latest version cannot work on 1.16.4 due to the forge version requirement.

**Comment by Vaerys-Dawn** [comment]
> turns out, another mod is messing with it lol

can you tell us which mod was messing with it?

**Comment by Floweynt** [comment]
performant

**Comment by Floweynt** [comment]
prob an optimization so that some event doesn't get called

**Comment by Vaerys-Dawn** [comment]
that sounds right, we've run into MAJOR issues with performant before, if you can contact or are the pack dev please disable it.
