### ISSUE TITLE
Bee Editor inverts check mark box

### ISSUE THREAD

**Issue by WenXin20** [Team-Resourceful/ResourcefulBees#16]
**Describe the bug**
After creating the first bee, if the Breedable box was previously checked, I cannot input parent names. If the box is then unchecked, I can input parent names. Same with the biome list. 
I had to refresh the page to fix it.

**To Reproduce**
1. Create a new bee with both Breedable and Biome list checked.
2. Create a second bee
3. Try to input new parents/biomes.

**Expected behavior**
If checked, appropriate boxes should be enabled.

**Comment by ThatGravyBoat** [comment]
Fixed
