### ISSUE TITLE
Ghast Bee Mutation JEI tab uses Vanilla Ghast Egg

### ISSUE THREAD

**Issue by merlerm** [Team-Resourceful/ResourcefulBees#163]
**Describe the bug**
The JEI tab for entity mutation for the Ghast Bee recipe is currently pretty odd. It uses vanilla ghast bee spawn eggs for both the "input" Beeper Bee and the "output" ghast bee, so it's not found when looking for "recipes" for the ghast bee but is instead found when checking "recipes" or "uses" for the vanilla ghast spawn egg

**To Reproduce**
Open JEI and check for uses on the ghast vanilla spawn egg

**Expected behavior**
I would expect this information to the under the ghast bee "item", so when players checked how to obtain it they would see the information there. Using the eggs (currently the wrong eggs, but even the correct eggs) wouldn't work as well imo, since players wouldn't likely check there but look directly for the bee.

**Screenshots or Crash Logs**
![2021-02-20_12 47 49](https://user-images.githubusercontent.com/62080872/108594541-e4fe2f80-737a-11eb-8270-5eef60586e7d.png)
![2021-02-20_12 52 51](https://user-images.githubusercontent.com/62080872/108594546-e7608980-737a-11eb-8e9a-cfd7bdc055de.png)

 - Forge Version [1.16.5-36.0.40]
 - Mod Version [1.16.5-0.5.10b]
 - JEI Version [1.16.4-7.6.1.71]

**Additional context**
I'm experiencing this in the Enigmatica 6 modpack, but if you think I should reproduce the issue with only the mods installed let me know and I will try. It looks like a mod issue to me so I thought I'd report over here straight away

**Comment by Epic428** [comment]
It’s not really a bug per se. ghast spawn eggs were used specifically in the code though I understand the issues that presents and I’ll look at changing it up.

**Comment by merlerm** [comment]
I would've expected this to be intentional but I wasn't 100% sure so I filed it under the bug category. I still think it would be much better to use the entity items to be more clear, since lots of players have reported confusion on this to us and I can see why ^^ thanks for looking into it

**Comment by Epic428** [comment]
Ah no worries. There’s no built in way to easily display all entities in jei and we had the functionality in place for a while just no jei screen. I’m still trying to think of a better way to display the entity to entity mutations. The spawn eggs were used just as a temporary solution though the side effects of doing so weren’t identified until now.

side note: our next update will be a pretty beefy update and will still be several days out but there’s some changes to mutations and jei coming with that already.

**Comment by Epic428** [comment]
Fixed in 93696519287e60ddbf486466bf878e26802346e2
