### ISSUE TITLE
Block Mutation from Bottled Bee

### ISSUE THREAD

**Issue by cameronfowler** [Team-Resourceful/ResourcefulBees#164]
When a bee with the ability to mutate a block (I tested this specifically with a diamond bee) pollinates a flower and mutates a block, you can pick the bee up with a jar, and place it on another block to mutate it rather than having to wait for the bee to go back to a hive to mutate another block.  This can be done as many times as you want with the same bee, somewhat negating the need for it to produce honeycomb in the first place.

**Comment by ThatGravyBoat** [comment]
are you 100% sure the bee didnt already have more mutations it could do because by default a bee can do 10 mutations before needing to go to a hive and then pollinate at a flower.

**Comment by cameronfowler** [comment]
Didn't know that it could do 10, but I just tested again and did it to more than 20 blocks successfully.  I have broken the hive each time in case that is required to replicate the bug, but I imagine it probably isn't required.

**Comment by ThatGravyBoat** [comment]
ok will look into it

**Comment by Epic428** [comment]
I figured out the issue. the number of mutations wasn't being saved in the nbt of the bee so every time it went into a jar the count reset to zero. This is now fixed in dev.
