### ISSUE TITLE
Obsidian Honeycomb doesnt have any output

### ISSUE THREAD

**Issue by rjulib00** [Team-Resourceful/ResourcefulBees#166]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
the obsidian honeycomb (block and honeycomb) lost their output in the centrifuger

**To Reproduce**
obsidian honey comb put into the centrifuger

**Expected behavior**
be able to get something (obsidian blocks)

**please complete the following information:**
 - Forge Version [e.g. '1.16.5 - 36.0.40]
 - Mod Version 1.16.5-0.5.10b

**Comment by ThatGravyBoat** [comment]
we dont provide a obsidian bee by default so this would be a bee added by a pack dev and also pack devs can set chances for things to be given in the centrifuge so they may have made it so that obsidian honeycomb doesnt always give obsidian.

**Comment by NielsPilgaard** [comment]
For reference I believe this was in Enigmatica 6, and the issue is resolved in-dev :)
