### ISSUE TITLE
Multiple Apiaries Confuse Bees in Same Structure

### ISSUE THREAD

**Issue by desagas** [Team-Resourceful/ResourcefulBees#167]
With the majority of bees, including vanilla, and default RB bees, in a few different packs, like ATM6 1.5.2 and Sky Bees, when you have multiple apiaries using the same structure, many duplicate bees will not find a hive they can go into, rather, they wait for the same apiary to become available, and likewise, they try to pollinate the same flower. So, what happens, bees can despawn and production is slowed down. The bees are unable to recognize if an apiary is empty, and adjust to find another home, or if they can actually get to a flower they want to pollinate. Rarely, it is important to note, they will find another home, but this is extremely rare, and the majority of the time, they do not.

**To Reproduce**

I have three apiaries, tier 4, any side, doesn't matter if they are all together, side by side, stacked, or scattered around the housing of the apiary, the result is the same. Right now, specifically, in ATM6 1.16.5-1.5.2, I have three all in the second block from the bottom, on the north face. I have three each of wither bees, Minecraft bees, and netherite bees. What happens is this: for the majority of time observing the apiary, only one of each species will enter any of all the apiaries, and the remaining 2 will float around, waiting for that exact same apiary to empty, completing ignoring the empty apiary directly beside it.

All apiaries in my example are validated. I have tried inserting with the apiaries, and just releasing them into the apiary.

**Expected Behavior**

If a bee can not enter a hive or an apiary, because it has a bee of the same type (apiary) or it is full (apiary or hive), they would search their immediate surroundings to find a hive they can enter, even if it is only a double check, and left alone after that. Thus, when there is an empty apiary beside a full apiary, the bee would enter the empty apiary.

It would also be very nice if when importing a bee into an apiary, if there was a tag assigned to that bee to link it to that apiary, so that it did not have to "guess" which apiary it should try to enter.

**Screenshots **
![2021-02-24_23 34 18](https://user-images.githubusercontent.com/8404632/109113073-df954200-76f8-11eb-834e-072a758d7673.png)

**please complete the following information:**
 - Forge Version 1.16.5.36.0.21
 - Mod Version resourcefulbees-1.16.5-0.5.9_3b

**Comment by desagas** [comment]
Note: I have noticed that two apiaries are fine, but the third is where things go wrong. Also, it does not matter if each additional apiary has its own storage and breeder ... as all apiaries now share the same storage block anyways, well, at least they do in the version described above. I have tried it both ways, three apiaries, three breeders and three storage blocks, and just three storage and three apiaries, no configuration seems to fix this.

Also, if the line of sight is obstructed, ie, have 3 apiaries with a wall between each, all in the same 5x5 internal space, Apiary, wall, apiary, wall, apiary .... then they do not get confused. I believe that this may be more the extended minecraft bee, than it is your code.

**Comment by Vaerys-Dawn** [comment]
I would personally avoid using multiple apiary blocks in a single structure, it's not surprising that this sort of issue happens when the setup is like this.

**Comment by Epic428** [comment]
Also with the new dipper being added it will alleviate a lot of these “bees only use a certain hive” issues since it will allow you to designate a hive and flower for a bee

**Comment by Vaerys-Dawn** [comment]
closing, see #174
