### ISSUE TITLE
İts not loading

### ISSUE THREAD

**Issue by Yvzslmayd** [Team-Resourceful/ResourcefulBees#168]
When loading screen its crashing its annoying me and its doing for all modpacks sky bees, all the mods 6 

Do not say exnihilo crash its not i tried
[crash-2021-02-26_22.00.56-fml.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6051829/crash-2021-02-26_22.00.56-fml.txt)
crash from sky bees

**Comment by ThatGravyBoat** [comment]
change your computer language to english as your language of your computer replaces lowercase i with the dotless I

**Comment by Yvzslmayd** [comment]
I will try

**Comment by WilxGaming** [comment]
"exnihilomekanism-1.16-1.0.0.0.jar " in your crash report, replace it

**Comment by Yvzslmayd** [comment]
> "exnihilomekanism-1.16-1.0.0.0.jar " in your crash report, replace it

It worked thanks

**Comment by Yvzslmayd** [comment]
> change your computer language to english as your language of your computer replaces lowercase i with the dotless I

It worked thank you so much
