### ISSUE TITLE
[Enhancement] Apiary redstone interaction. 

### ISSUE THREAD

**Issue by Jkosio23** [Team-Resourceful/ResourcefulBees#169]
I was thinking that maybe adding the feature of having a redstone signal on the Apiary block could lock any bees entering the hive, and when a redstone signal is removed, all bees inside are released. I don't know how it would interact with the manually imported bees, but sometimes if I exit my single player world with the bees too close to the walls, they wind up in the walls on world load. It would be a neat way to get all the bees situated rather than having to wait in the Apiary gui or having to break into the Apiary to jar them up manually.

**Comment by Vaerys-Dawn** [comment]
closing due to full apiary rewrite in 1.18
