### ISSUE TITLE
RGBees Dying when in bee keep area.

### ISSUE THREAD

**Issue by AdamL29** [Team-Resourceful/ResourcefulBees#170]
https://pastebin.com/CiGxjzN4

https://user-images.githubusercontent.com/70981954/109442438-80377a80-79f5-11eb-9002-904787cae866.mp4

We are playing in 0.3.13 Enigmatica 6 - E6 - 1.16.5 using CurseForge version 0.167.2.7

**Comment by AdamL29** [comment]
This bee was not attacked and did not sting us.

**Comment by Vaerys-Dawn** [comment]
fixed in 8678d73

**Comment by Vaerys-Dawn** [comment]
hopefully
