### ISSUE TITLE
A way to check how many bees are in a beehive

### ISSUE THREAD

**Issue by tgodoib** [Team-Resourceful/ResourcefulBees#173]
I found very difficult to keep count on how many bees are in a hive, especially if there are a lot of them. The only data i can manage to easily verify is the honey level. Right now, to count my bees i have to wait for all of them come out og the hive, and move them away. I think this is too much work for something that should be simple though.

Perhaps a way to make this info avaible for other mods such as Wawla, or any others that add the block data on top of the screen would be the way to go.

Or even an item that would give the player some extra info about the hive when you right click.

**Comment by ThatGravyBoat** [comment]
This is a design choice we have it this way to get the player to upgrade to the apiary as the apiary tells you all the info needed.
