### ISSUE TITLE
When Pollination Block both Directly Above/Diagonal and Directly Below, Bees Always Choose Above

### ISSUE THREAD

**Issue by desagas** [Team-Resourceful/ResourcefulBees#174]
Same version data as in https://github.com/Resourceful-Bees/ResourcefulBees/issues/167,

When RBs have both their pollination block above their heads or diagonally, and below their heads, directly, the RBs will always choose the block above their heads to pollinate, which means they will never collect pollen when they only have the block directly infront of the apiary available to move. They pathfind to blocks that should be not accessible to them, and never change this path.

Based on #167 and this, it seems as though, unlike other Minecraft mobs, bees do not dynamically update their pathfinding when they can not make it to their destination.

Below is a screen shot of my setup. Apiary highly sectioned off, to allow maximum use of space, you can see every bee that has its pollination block above its head refuses to pollinate:

![2021-03-07_10 42 33](https://user-images.githubusercontent.com/8404632/110249162-0a219f00-7f32-11eb-8982-0b193047641f.png)

**Comment by Vaerys-Dawn** [comment]
not really a bug? more so an observation on how search order works?

**Comment by Vaerys-Dawn** [comment]
the pathfinding problem is kinda a bug? but it's really hard to fix

**Comment by Epic428** [comment]
Not to mention our bees follow vanilla logic for the most part. With the exception of a few spots where performance is optimized significantly over vanilla which means most bugs you see with resourcefulbees also exist with vanilla bees

**Comment by ThatGravyBoat** [comment]
I just tested this in dev and had the opposite happen where the bee would always go to the block below, also in the next update there will be a "tool" that you can craft where you can right click on a bee and set their flower pos so it will fix this issue.

**Comment by desagas** [comment]
@ThatGravyboat --> LOVE ... yay, thats awesome. That will fix most of the problems. Will you have one where you can bind them to a specific apiary?

**Comment by desagas** [comment]
I figured it was backing off the the vanilla code, which is not really a RB bug, but a bug about bees in general.

**Comment by Vaerys-Dawn** [comment]
closing, not really a bug, and in the next patch we will be adding the option to set which hive/flower a bee uses so it's not really needed to be fixed. vanilla is really hard to "fix" so yeah...

**Comment by ThatGravyBoat** [comment]
yes the same item will allow for the bee to be bound to an apiary or hive too

**Comment by desagas** [comment]
Awesome, definitely looking forward to it!

**Comment by ThatGravyBoat** [comment]
make sure your apiary isnt going across chunk borders as that can cause alot of issues with pois(the system the bees use to go to a hive)
