### ISSUE TITLE
REMOVE PERFORMANT (read this if you are having any issues with bees finding hives/flowers)

### ISSUE THREAD

**Issue by Vaerys-Dawn** [Team-Resourceful/ResourcefulBees#175]
Performant is a mod that claims to improve fps and performance, in actuality, it completely breaks bee AI, if you have the mod installed please remove it.

In the next update if you have performant the game will crash, we consider performant to be EXTREMELY incompatible with our mod.

**Comment by ingitsuthar** [comment]
I am using Enigmatica 6 0.4.2 version and I have not installed the performant mod,
In JEI, I am not able to see the flowers for any bees. and sometimes even bees are not showing
here are some screenshots

![1](https://user-images.githubusercontent.com/26589475/111076503-e8409300-84c2-11eb-91ff-724d2cf3130b.JPG)
![2](https://user-images.githubusercontent.com/26589475/111076505-e8d92980-84c2-11eb-8c46-b7f4c50f0a54.JPG)

**Comment by Epic428** [comment]
There’s a mutation on the wither bee that is breaking jei. We have a mod update set to release Tuesday which will fix the issue

**Comment by Epic428** [comment]
warning added in latest build
