### ISSUE TITLE
Just a little change to a name

### ISSUE THREAD

**Issue by Garthis** [Team-Resourceful/ResourcefulBees#176]
Not a big issue just a missed pun I would like to see corrected. The Zombie Bee really should be called the Zombee instead. After all, you have RGBees and I discussed it with the mod pack group in discord and everyone thought it was a good pun.

**Comment by Epic428** [comment]
it is set that way by default however pack devs can customize their own bees, if the lang generator runs though it uses the json name. the default json name is zombie which causes it to generate a new lang overriding the default. so it's possible the lang got changed by the pack at some point. you could probably find it in a kubejs script or something somewhere in the pack and remove the entry and it would be fine.
