### ISSUE TITLE
Cannot get villager to choose profession

### ISSUE THREAD

**Issue by jackwright-ual** [Team-Resourceful/ResourcefulBees#177]
I have placed some tiered beehives, and a nitwit will not recognise that 

I'm using resourcefulbees-1.16.5-0.5.10b.jar

**Comment by Epic428** [comment]
https://minecraft.gamepedia.com/Villager#Nitwit

> Nitwit villagers wear robes that are green on top. **_They cannot acquire a profession, trade, or gather around bells_**, but are still able to breed. They are not equipped with a level stone since they cannot trade.
