### ISSUE TITLE
Custom bee following like a pet!

### ISSUE THREAD

**Issue by xenoflot** [Team-Resourceful/ResourcefulBees#178]
**Describe the bug**
One particular variety of bee in the pack I'm playing is following me around as if I was holding their preferred food. I can't see anything in the JSON along those lines, so I'm mentioning it here.

From testing on the pack's official server and in SSP, I've found this happens with bees found in the wild, spawned in bees, bred bees and bees released from jars. I tried secured a test bee with a lead and released it. Killed myself and the problem remains even with empty inventory.

This only appears to affect one particular specie. That suggests it's something specific to that bee's JSON but I can't spot it!  Here is a paste of the buggy Signalum Bee and the non-buggy Lumium Bee https://pastebin.com/T7hhmpX9
If you can spot what's causing it, please let me know and I'll forward it on to the pack dev.

**To Reproduce**
1. Release/spawn a bee
2. It will fly up to you
3. Move
4. It will fly up to you

**Expected behavior**
Bees to ignore me unless I annoy them.

**Screenshots or Crash Logs**
Xeno and his groupies: https://cdn.discordapp.com/attachments/790909542787579935/818771235055075388/unknown.png

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5'] **1.16.5 - 36.0.39**
 - Mod Version [e.g. '0.2.0'] **resourcefulbees-1.16.5-0.5.10b**

**Additional context**

**Comment by ThatGravyBoat** [comment]
its because you put redstone_dust as the item and since that item doesnt exist it nulled out and in minecraft the registry makes nulls air so its gonna think that its feeding item is air, to fix this issue put the proper id for redstone

**Comment by xenoflot** [comment]
Perfect. Many thanks!
