### ISSUE TITLE
Please do not reload sources during server start

### ISSUE THREAD

**Issue by shedaniel** [Team-Resourceful/ResourcefulBees#179]
Please do not reload sources during server start, the following snippet of code makes server start extremely slow, because it will reload resources twice.

https://github.com/Resourceful-Bees/ResourcefulBees/blob/ad13d9d62e02d42723836441e0cf2c72dbc3bb1b/src/main/java/com/resourcefulbees/resourcefulbees/data/DataPackLoader.java#L37

**Comment by Epic428** [comment]
Thank you for the information! I knew about the server times being crap from it, but we weren't sure of an alternate method. Gravy seems to have found one however and pushed the changes.
