### ISSUE TITLE
More JEI integration

### ISSUE THREAD

**Issue by AlleCraft** [Team-Resourceful/ResourcefulBees#18]
I would like the bee effects pages to open by clicking with JEI ("U" button) on the bee spawn eggs 
![2020-06-09_01 50 46](https://user-images.githubusercontent.com/51967599/84091302-5320e300-a9f4-11ea-8a4c-9c865af3af05.png)

**Comment by Epic428** [comment]
Added the ability to see breeding page of jei using spawn eggs. will be in next version with apiary which I should be releasing tonight.
