### ISSUE TITLE
breeding in apiary doesnt use any resources 

### ISSUE THREAD

**Issue by djnugets** [Team-Resourceful/ResourcefulBees#180]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
breeding the uranium bee in ATM6 doesn't use and materials 
**To Reproduce**
1. go to atm6 
2. make a uranium bee in an apiary breeder 
**Expected behavior**
it should use the jars iron and catalyst glands 
**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5']
 - Mod Version [e.g. '0.2.0']

**Additional context**

**Comment by Epic428** [comment]
This is quite an interesting bug considering how the apiary breeder works. I’ll take a look at it and see about fixing it for the update release.

**Comment by Epic428** [comment]
I can't reproduce this on the latest version of ATM6
