### ISSUE TITLE
Cyclic Solidification Chamber Compatibility

### ISSUE THREAD

**Issue by Eadinize** [Team-Resourceful/ResourcefulBees#182]
1.16.5
Resourceful Bees Honey will not work as honey with the Cyclic Solidification chamber for any use.

**Comment by Epic428** [comment]
I’ll have to look at cyclic code and see what they do but I’m positive it’s an issue on their end Bc our honeys are added to the forge honey fluid tag. So if cyclic used the tag it would accept our fluid which I’m assuming it does not.

**Comment by Lothrazar** [comment]
Looking into it.  How do you tag your honey fluids? I dont see any tags in https://github.com/Resourceful-Bees/ResourcefulBees/tree/ad13d9d62e02d42723836441e0cf2c72dbc3bb1b/src/main/resources/data/forge/tags/blocks

**Comment by Vaerys-Dawn** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/tree/master/src/main/resources/data/forge/tags/fluids

**Comment by Vaerys-Dawn** [comment]
you were looking at a version from about 5 months ago

**Comment by Epic428** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/blob/master/src/main/resources/data/forge/tags/fluids/honey.json

we use the fluid tag not the block tag. the fluid can access the block though if it's needed for some reason

edit: ninja'd by dawn

**Comment by Epic428** [comment]
fixed in referenced issue
