### ISSUE TITLE
[1.16.5] Bee Smoker doesn't use durability

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#184]
**Describe the bug**
The Bee Smoker never uses durability

**To Reproduce**
1. Use the Bee Smoker on a hive
2. Observe that it never loses durability

**Expected behavior**
For the durability to drop.

**please complete the following information:**
 - Forge Version 1.16.5-36.0.46
 - Mod Version resourcefulbees-1.16.5-0.5.10b

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/1649

**Comment by Epic428** [comment]
This is in dev no changes made to smoker. Are you in creative mode by chance?

https://user-images.githubusercontent.com/291578/110848370-049ebe80-827c-11eb-94f3-cf25321a900d.mp4

edit: oh I see someone else is having an issue

**Comment by NielsPilgaard** [comment]
I was in creative mode actually :P But it persists in survival. It only uses durability if I use the smoker directly into the air.

**Comment by Epic428** [comment]
interesting. 

```java
int damage = player.getItemInHand(hand).getDamageValue();
int maxDamage = player.getItemInHand(hand).getMaxDamage();

if (flag == 1 && damage < maxDamage) {
   player.getItemInHand(hand).hurtAndBreak(1, player, player1 -> player1.broadcastBreakEvent(hand));
   flag = 0;
} else {
   flag++;
}
```

This is the logic that damages the item. the specific line that does the damaging is a vanilla method. I just have it set to use a durability point every other tick so you can continuously hold it without eating durability too quickly

**Comment by Epic428** [comment]
I also can't seem to replicate the damage issue going from creative to survival

**Comment by NielsPilgaard** [comment]
The smoking behaviour in your video is also different from ours, so I think it's likely you fixed something with the Smoker that isn't released.

**Comment by Epic428** [comment]
OH YEAH! that's right because we fixed the animation issue which may have inadvertently fixed this issue as it would've been unknown at the time

edit: I forgot we've done so much for this next update. I just need to make sure these server bugs are worked out and I think we should be good to work on forge 36.0.48 pending one additional test on some modifications

**Comment by Epic428** [comment]
fixed in latest build
