### ISSUE TITLE
Crash when trying to load in latest forge version

### ISSUE THREAD

**Issue by CelestialSkies95** [Team-Resourceful/ResourcefulBees#185]
**Describe the bug**
Minecraft won't load

**To Reproduce**
Try to load

**Expected behavior**
Loading correctly

**Screenshots or Crash Logs**
It doesn't seem to have made a crash report so I've just attached the log
https://paste.ee/p/bt7Mb

**please complete the following information:**
 - Forge Version [1.16.5 - 36.0.55']
 - Mod Version [1.16.5-0.5.10b]

**Additional context**
It loads fine on 36.0.40, but I need higher for a modpack I'm trying to add it into.

**Comment by Epic428** [comment]
Fixed in dev. It’s due to forge updating internals and switching to official Mojang mappings. Use version 36.0.46 or less for the moment
