### ISSUE TITLE
Crash on launch with forge >= 36.0.48

### ISSUE THREAD

**Issue by starmun-0010** [Team-Resourceful/ResourcefulBees#186]
**Description**
Resourceful bees causes crash on game lauch with forge version 36.0.48 or greater.
No crash report is being generated but the latest log is attached.

**To Reproduce**
1. Create a new minecraft instance.
2. Install forge >= 36.0.48
3. Install resourceful bees mod
4. Launch the game

**Expected behavior**
Game should launch without crashing.

**Screenshots or Crash Logs**
[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/6138659/latest.log)

**please complete the following information:**
 - Forge Version >= [36.0.48]
 - Mod Version [0.5.10b]

**Comment by ThatGravyBoat** [comment]
fixed in dev, the update will release soon to not crash on > 48.
this is due to forge changing their mappings to the official mappings
