### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by Opsord** [Team-Resourceful/ResourcefulBees#187]
Hi there!
Im making a personal modpack with a bunch of mod that i like, but, when i try to install resourcefull bees it wont even open minecraft, idk if its the version or something else, if someone could help me i would be thankful.

This is the log:
[New Paste 1.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6144969/New.Paste.1.txt)

**Comment by Epic428** [comment]
Because of forge changes in 36.0.48 our mod crashes on mixins. It’s fixed in dev and update will be released tomorrow.

Edit: current version will only work up until 0.46. But I heard it also works on 0.53 for some reason. Haven’t tested that myself personally.
