### ISSUE TITLE
Issues with fifty shades of bees

### ISSUE THREAD

**Issue by Pdiddy973** [Team-Resourceful/ResourcefulBees#188]
few issues with he bee book:

seems to be missing crafting recipe 
![image](https://user-images.githubusercontent.com/68764896/111577062-012d9a80-8788-11eb-8d31-6d19d765502b.png)

crash when opening beecon options page
https://pastebin.com/d6QdmXzb

multi block centrifuge only shows casing recipe, not controller
![image](https://user-images.githubusercontent.com/68764896/111576677-54531d80-8787-11eb-98a6-af5b5e852532.png)

Should add elite centrifuge?
![image](https://user-images.githubusercontent.com/68764896/111576593-2a016000-8787-11eb-836a-59930156f86b.png)

may want to update to say beepedia shows trait info
![image](https://user-images.githubusercontent.com/68764896/111576788-86fd1600-8787-11eb-98ce-2d455ca57b22.png)

no beepedia or bee box page
![image](https://user-images.githubusercontent.com/68764896/111576819-9714f580-8787-11eb-8df2-b8599b2e5de7.png)

**please complete the following information:**
 - Forge Version [36.1.0]
 - Mod Version [0.6.2b]

**Comment by Pdiddy973** [comment]
the issue with multi block centrifuge only shows casing recipe, not controller is fixed, was a pack related issue

**Comment by Epic428** [comment]
All are fixed in dev except beecon page which will at least stop crashing now

**Comment by Vaerys-Dawn** [comment]
fixed in 4b61345c983aee6ee56cddf1d9253a6cc6e47169
