### ISSUE TITLE
Updating beehive in-world doesn't work

### ISSUE THREAD

**Issue by iarspider** [Team-Resourceful/ResourcefulBees#189]
**Describe the bug**
Updating beehive in-world doesn't work: the texture stays the same, and breaking the upgraded block reverts it back to whatever tier was befoew

**To Reproduce**
1. Get a T1 beehive and upgrades
2. Click with T2, T3, T4 upgrades
3. Notice that the texture doesn't change (while the information shown by TheOneProbe does update)
4. Break the beehive - you get T1

**Expected behavior**
Texture should change; breaking the upgraded beehive should drop the upgraded version

**please complete the following information:**
 - Forge Version 1.16.5-36.1.0
 - Mod Version 0.6.2b

**Additional context**

**Comment by Vaerys-Dawn** [comment]
Can you tell us which hive you used, screenshot the hive hovered in the F3 menu

**Comment by ThatGravyBoat** [comment]
I already have a fix

**Comment by alexporth** [comment]
@ThatGravyboat how did you fix the issue? I have the same problem.

**Comment by Epic428** [comment]
It should be in the latest alpha version of our mod.

**Comment by alexporth** [comment]
I am playing this mod in the Sky Bees mod pack so I guess I should post an issue in their repository. Thanks for the info.
