### ISSUE TITLE
Grass Bee Nest Crash

### ISSUE THREAD

**Issue by WenXin20** [Team-Resourceful/ResourcefulBees#19]
**Describe the bug**
While on my server, the server crashed because of a Grass Bee Nest that probably generated nearby. Not sure how to reproduce the crash or what caused it.

**To Reproduce**
1. Load a world
2. Crash?

**Expected behavior**
No crashes

**please complete the following information:**
 - `Forge v31.2.5`
 - `Resourceful Bees v0.2.4a`

**Additional context**
[Crash Report](https://gist.github.com/WenXin20/c71947cd7e09fc823a2ce4ee5a80e848)

**Comment by Epic428** [comment]
This is fixed in my dev version. For some reason it tries to set the honey level to 6 and there's no blockstate for that level. I'm not sure exactly why it does that. So instead I'm just going to clamp the value between 0->5 so it's not an issue.
