### ISSUE TITLE
Crash report from centrifuges

### ISSUE THREAD

**Issue by nigel239** [Team-Resourceful/ResourcefulBees#192]
**A clear and concise description of what the bug is.**
Game crash, I believe whenever you hook up a centrifuge to a refinedstorage import- and exporter.

[rbees2.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6211478/rbees2.txt)

**Expected behavior**
It would work, no?

 - Forge Version 1.16.5 36.1.0
 - Mod Version is 0.6.2B

**Comment by Vaerys-Dawn** [comment]
Please update to latest. This should be fixed in the most recent live build
