### ISSUE TITLE
book missing info

### ISSUE THREAD

**Issue by Spongman** [Team-Resourceful/ResourcefulBees#194]
ResourcefulBees1.16.3-1.16.4-0.5.8b

I can't find any information in the book on how to proceed with this mod. i have collected some nests, but there are no bees coming out of them. i see in JEI there's a recipe for an 'Empty Bee Jar', but i can't find any mention of this in the book. Am i supposed to do something with this? Am i missing a section in the book? it seems that all the crafting reipes require honeycomb, but i don't know how to get these.

**Comment by Epic428** [comment]
Update to the latest version of the mod. 99.99% of 1.16.4 mods will work on 1.16.5 so there’s no reason to still be on that version. The newest has the missing pages. As for how the mod works I recommend reading up on vanilla bees and learn how they function Bc we run parallel to vanilla and extend off of it. Meaning if you know how vanilla works then you know how we work.

**Comment by Spongman** [comment]
unfortunately i'm running on a server that can't update. is there a web version somewhere?

**Comment by Epic428** [comment]
There is not a web version for the book. No. But essentially bees needs flowers to pollinate from so when they go in the hive/apiary they can generate a honeycomb. Flowers can be found in jei by rightclicking the bee in jei. You can also find other important information about the bees there. Bee jars will capture bees for transporting or long term storage or importing to an apiary. Centrifuges will convert honeycombs into resources

**Comment by Epic428** [comment]
Smoke hives with campfires or smoker or use a beecon if available to prevent bees from getting angry and use a scraper or, if enabled in configs, shears to harvest combs from a hive. Apiary is fully automated and a video is available on YouTube for setting it up.

**Comment by Spongman** [comment]
oh ok, so the jars are for bees, not honey. that was my confusion. i installed the latest version locally here and i don't see any mention of jars, or their use, in the book.

**Comment by Epic428** [comment]
The jars show up in the essential tools category.

**Comment by Spongman** [comment]
ok. so i finally found some bees, which was a little tricky since i had broken all the nests i could find near my base. and i put them near my base and they started using the nests i had placed there and making honey, which i harvested. great! but then i converted all my nests into tier-1 hives and left them alone for a while... but then i came back later and all the bees have gone. i waited for a full day/night cycle but they didn't return.

**Comment by Epic428** [comment]
Did you build an enclosure around your hives? Bees, vanilla included, have a tendency to wander off on their own. It’s is HIGHLY recommended to build an enclosure around where your bees are working.

**Comment by Spongman** [comment]
i didn't build an enclosure, but i didn't have to when they were using the nests - they all stuck around and filled the nests with honey. i converted 11 nests to hives and they all say 'Honey Level: 0'. does that mean not a single bee completed a flower/hive cycle after i converted them? this seems more like some difference in behavior between nests and hives.

**Comment by Epic428** [comment]
All of the hives use the exact same logic. Literally the only difference is the tier and tier modifier values used for calculating the max number of combs/bees. I can also say with absolute certainty that upgrading the hives in world bees will still use them Bc I did so on our ATM6 server with zero issue. Other than the fact that T2 is converting 1.5 to 1.0 due to me getting the value as an int vs a float. Which has since been fixed in dev.

**Comment by Epic428** [comment]
Honey level 0 does however mean the bees aren’t producing combs. Try jarring the bees and releasing them again to reset their flower and hive pos and see if fixes it.

**Comment by Spongman** [comment]
that's the thing, though. i can't re-jar the bees - they're gone.

maybe it's the order i did things:
- break remote nests
- place nests at base
- jar remote bees
- unjar bees at base, (at this point i waited several day/night cycles and got a stack or so of honeycombs from the nests)
- break nests at base, convert to hives, place hives, (at this point i waited some more, i probably left the area, and might have travelled to the nether once or twice)
- bees gone. (i don't think they just wandered off, as i had initially broken all the nests near my base and at this point the only bees i could find were quite some distance away (~300 blocks), and i did't see any of my bees i had brought from the nether).

**Comment by Epic428** [comment]
If the bees aren’t enclosed there is a chance they will wander off. Even more so of that happening if you break the hives to upgrade them and the bees have no where to go. The bees, vanilla included, have an AI task specifically called “Wander” if that task triggers or if they can’t pollinate/enter a hive or do any other task like breed,etc then they wander. Sometimes they switch to that task even if they can do the others. So **always**  build an enclosure for your bees.
