### ISSUE TITLE
Chunk Loading Issue

### ISSUE THREAD

**Issue by MeAndMyOats** [Team-Resourceful/ResourcefulBees#195]
**Describe the bug**
I have force loaded the chunks where my apiaries are located two different ways, FTB chunks and using mekanism anchor cards, either do not seem to work. If i am not in the same chunk as my apiaries my bees seem to stop producing combs.
**To Reproduce**
1.Load game
2. run outside of chunk borders where my apiary is located

**Expected behavior**
Dont know if this is intended or not but if not, bees to produce combs when outside of chunk range.

**Screenshots or Crash Logs**
n/a

**please complete the following information:**
 - Forge Version is 36.0.46

**Additional context**
All the mods 6 v 1.5.4b

**Comment by Epic428** [comment]
I’ll do testing with chunkloading but afaik there should be zero issue with chunkloading since we don’t do anything to require a player be near the bees. If anything is affecting it then it would have to be vanilla itself.

**Comment by MeAndMyOats** [comment]
so what do you suggest i try ? move my bees or look for vanilla bees and remove them ? And thanks for the quick reply. I love this mod Btw

**Comment by Epic428** [comment]
Honestly I would do more testing with it. There’s no reason they shouldn’t be doing work as it’s no different than having a standard mob farm. Until I can reproduce the issue and figure what causes it there’s not much I can recommend atm as much as I would like to. Maybe having them close by where you spend most of your time would be better for the moment.

**Comment by MeAndMyOats** [comment]
i have them right next to my base, and even if im exactly one chunk away they just spin on their flowers but will not produce any combs until i get into the chunk they reside in. I did remove all of the vanilla bees and still nothing, i will try to recreate it in a creative world.

**Comment by Epic428** [comment]
They shouldn’t only produce honeycombs when you’re in the chunk with them. I find that very odd and something I would like to investigate a bit further.

**Comment by Epic428** [comment]
I also know from our ATM6 server that from what I’ve seen the bees produce combs when I’m in different chunks close by. I don’t have the area force loaded though so I will test that out and see what I can find.

edit: this is one of the biggest reasons for us having a public server. I’ve only ever played the mod from a dev perspective. So I need to experience things as a player to get a better idea of what’s still buggy

**Comment by MeAndMyOats** [comment]
It seems to me (in my creative world i set up a tier 4 apiary and 2 bees), the bees will enter the apiary but once i get outside of the chunk area they stay inside. Thanks for you quick reply if you figure anything out please let me know :)
Edit: here is a screenshot about 3 chunks away the bees dissapear and stop producing combs, the chunk is force loaded
.[
![2021-03-27_22 16 48](https://user-images.githubusercontent.com/81493183/112740349-47ce8200-8f4a-11eb-9f2b-dc2c64969746.png)
](url)

**Comment by Epic428** [comment]
Thanks for the screenshot. I will def look further into this. Bees should produce in loaded chunks regardless if the player is nearby or not. So I’d like to reproduce and test.

**Comment by MeAndMyOats** [comment]
One last update, ive been messing around trying to find a work around, so i have found out that for some reason the bees will produce combs while i am in a different dimension. Just not if im more than 2 or 3 chunks away in the overworld.

**Comment by Epic428** [comment]
That is the weirdest thing ever. Def something I will factor into my testing.

**Comment by Andy3link** [comment]
I seem to have the same issue in my SP atm 6 pack. And as author says it produces combs when I'm in a different dim. An other note. 1 of my 4 tier 4 apiarys seem to kill or just let my 9 bees disappear.
