### ISSUE TITLE
Duplication Glitch Within the Elite Centrifuge Controller

### ISSUE THREAD

**Issue by BeanGabe** [Team-Resourceful/ResourcefulBees#197]
**Describe the bug**
I'm playing the Sky Bees modpack, and when I put an item into the elite centrifuge controller and click the "Sort Container" button, it duplicates the items in its input slots, and seemingly takes a stack of items out of its output slots. It doesn't seem to sort the container in any way. I tested this with honeycombs and honeycomb blocks of multiple types, along with other items that aren't used by the centrifuge (i.e. bread), and everything seemed to be duplicated just the same, with the exception of unstackable items. I also tested this with items in all slots of the centrifuge and it duplicated items in every slot. I did not test this with the normal centrifuge controller, though I'd imagine it works the same.

**To Reproduce**
1. Go to the Elite Centrifuge Controller.
2. Put an item into the input slot. (Let items enter the output slots too if you want to see that part)
3. Press the "Sort Container" button
4. Items in input slots will double and one stack of items will be removed from the outputs.

**Expected behavior**
I expected that when I pressed the "Sort Container" button, my honeycombs would be spread among the 6 input slots in the elite centrifuge controller.

**Screenshots or Crash Logs**
![2021-03-28_23 47 00](https://user-images.githubusercontent.com/81547612/112788498-a6662f80-9020-11eb-9e23-4e0d38b36865.png)
![2021-03-28_23 47 13](https://user-images.githubusercontent.com/81547612/112788500-a6fec600-9020-11eb-83cc-9084dec684b9.png)
![2021-03-28_23 47 17](https://user-images.githubusercontent.com/81547612/112788501-a6fec600-9020-11eb-982b-6940f2f3f166.png)
![2021-03-28_23 47 20](https://user-images.githubusercontent.com/81547612/112788502-a7975c80-9020-11eb-9a1c-49c186091436.png)
![2021-03-28_23 47 22](https://user-images.githubusercontent.com/81547612/112788503-a7975c80-9020-11eb-9f83-f2c3b7ae937f.png)
![2021-03-28_23 47 26](https://user-images.githubusercontent.com/81547612/112788504-a7975c80-9020-11eb-986c-dc4cd0e9d300.png)

Above are pictures of the inventory of the elite centrifuge controller after pressing the "Sort Container" button a few times

**please complete the following information:**
 - Forge Version 1.16.5-36.0.46
 - Mod Version 0.5.10b

**Comment by BeanGabe** [comment]
Realizing now that the Sort Container button is from a different mod, but it still seems to be a problem nonetheless.

**Comment by Epic428** [comment]
Yes there’s an open issue for it. Quark I believe was supposed to have added a check so the duplication doesn’t happen. But it might be a different mod this time that’s doing it. I do need to figure out why these mods seem to be pulling two containers or inventories on the controller block Bc that I think is the reason for the bug.

**Comment by Epic428** [comment]
See #133

**Comment by Epic428** [comment]
what version of quark are you using? I just downloaded the latest version of our mod and quark and I don't have a sort button like you do so I'm curious if your version doesn't have the black list fix

**Comment by BeanGabe** [comment]
Quark is on version r2.4-308

**Comment by ThatGravyBoat** [comment]
what version of sky bees?

**Comment by BeanGabe** [comment]
It's just called Final Version

**Comment by BeanGabe** [comment]
I just updated the pack to Final Version 2 which has Resourceful Bees version 0.6.5b and Quark version r2.4-308, and it still seems to have the same issue

**Comment by ThatGravyBoat** [comment]
It's an issue with the pack not having our mod in the ignored screens in the quark config the pack dev said they would update it to include our screens in the ignored screens which are default with quark.
