### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by ghost** [Team-Resourceful/ResourcefulBees#198]
Can you add some more features from Forestry? <3 (like Frames, genetics, multifarm, tree selection, big apiary)

**Comment by Vaerys-Dawn** [comment]
We already have apiaries, frames/genetics may happen it's not high on our priority list, multi farms and tree selection? No clue what that means but it's probably not going to be getting added

**Comment by Epic428** [comment]
We’re not targeting becoming a forestry clone. Yes there’s overlapping elements in the mods but overall our goal is not to recreate forestry. It’s specifically to provide pack developers ways of customizing resource bees with more fine-grained control. That said you very likely won’t see the tree farms and whatnot that you saw in forestry. You may see genetics but with how our system is currently designed I see few places where genetics like forestry had makes sense.
