### ISSUE TITLE
Fifty Shades of Bees Manual - Bug on Link to Beecon Options

### ISSUE THREAD

**Issue by jeddell** [Team-Resourceful/ResourcefulBees#201]
**Describe the bug**
Reading through the 'Fifty Shades of Bees" Manual for this Mod, I clicked on The Ender Beecon Options link and then the 'Beecon Options' link in the following page and it instantly shut down the game. I have repeated this to confirm the bug

**To Reproduce**
1. Go to 'Fifty Shades of Bees manual'
2. Click on 'Ender Beecon' > 'Beecon Options'

**Expected behavior**
I expected to see a new page in t he manual to open

**Screenshots or Crash Logs**
Have attached the Crash Report

**please complete the following information:**
 - Forge Version forge-36.1.0
 - Mod Version All the Mods 6 - 1.5.5

**Additional context**
[crash-2021-04-01_10.29.54-client.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6240199/crash-2021-04-01_10.29.54-client.txt)

**Comment by Epic428** [comment]
Make sure you’re on the latest version. We fixed that bug a couple versions ago

**Comment by Epic428** [comment]
Actually you can just update your pack
