### ISSUE TITLE
Honey generator does not send power to Immersive Engineering wires

### ISSUE THREAD

**Issue by LavaMunkee** [Team-Resourceful/ResourcefulBees#203]
**Describe the bug**
The honey generator does not send power it generates to Immersive Engineering wires however, other blocks in the mod can receive power from the mod. I have tested with other mods and am able to export.

**To Reproduce**
1. Give honey to a honey generator
2. Put any level of wire connector from Immersive Engineering on a face of the generator
3. Connect the connector to another one of the same type connected to something that uses power (e.g garden cloche) with a wire

**Expected behavior**
No power will be moved, the buffer of the honey generator will fill and the machine will remain powerless.

**please complete the following information:**
 - Forge Version 1.16.5, 36.1.0
 - Mod Version 0.6.6a

**Comment by Epic428** [comment]
I assume IE doesn’t use the normal energy capability with their wire connectors then. Otherwise it should work. I’ll have to see what they’re doing and what needs to be done for it to work.

**Comment by ThatGravyBoat** [comment]
Fixed in 8283f6af6887f76e7c8c6c4a29ec528ff3bdea96
