### ISSUE TITLE
Some blocks will not be listed in JEI Bee Flowers when set as a Flower

### ISSUE THREAD

**Issue by lerokko** [Team-Resourceful/ResourcefulBees#204]
**Describe the bug**
I made some custom bees and I am at the stage where I wanted to assign them flowers to which to go. Works fine. I can use block tags or single blocks. However if I for example set the Flower to betterendforge:lumecorn from the Better End mod. The bee still has a "Bee Flowers" tab in JEi and also correctly startss interacting with the block (flies towards it) but the block is not shown inside JEI. The slot is empty. Would there be a way to fix this. Like a config option to display the supported blocks as a text in the info tab instead.

**To Reproduce and mods used**
- Install forge 1.16.5 36.1.2
- Install Resourceful Bees 116.5-0.6.5b
- Install Betterendforge 1.16.4 1.5.1
- Install JEI 1.16.5 7.6.1.75
- Add betterendforge:lumecorn to any bee as Flower
- Got to the 

**Expected behavior**
Not sure but if the block selected for a bee as a flower does not have an item form maybe just a placeholder with a missing texture so that the name can still be displayed to the player. Because right now a player would think there is now compatible flower/block.

**Comment by lerokko** [comment]
I just saw that resourceful bees shows the seeds of some flowers. The Lumecorn has a seed but Resourceful Bees does not detect it.

**Comment by ThatGravyBoat** [comment]
That is because the lumecorn block does not have an item so we cant show it in JEI

**Comment by lerokko** [comment]
Dude fr? I wrote that lumecorn has a lumecorn seed that drops when you break it and you can use the seed item to place it. can you please let me know if the non-recongintion of the seed as the item to place the lumecorn is an issue with resourceful bees or with betterend? Resourceful bees clearly CAN detect some items that are used to place a block but this mechanic does not work for the lumecorn rod.

**Comment by ThatGravyBoat** [comment]
So lumecorn and lumecorn seed are 2 seperate things in their code so I bet if you do lumecorn_seed instead of lumecorn it will show the item the problem is that the lumecorn block doesnt have an item attached to it. As you can see in the bottom image.
![image](https://user-images.githubusercontent.com/26934102/113504916-0e7fae80-9516-11eb-93dc-e2980f2ef44d.png)
Its just very hard to display something for when there is not an item for a block because of how jei is setup.

**Comment by ThatGravyBoat** [comment]
Ok im adding a thing to just replace the item with a barrier with the name of the block but I would suggest to them to add an item for the lumecorn block so it can look nice in JEI

**Comment by lerokko** [comment]
Thank you! This is awesome. I will try to add the seed. Will the Flower field accept an item tag as an input. Cause minecraft would not allow a block tag containing an item and vice versa.

But thanks for letting me know that. So the problem seems to be betterends implementation, right?

**Comment by ThatGravyBoat** [comment]
So we do the same thing with the item tags where we just get each block and get the item corresponding so if you make a tag with both the seed and the block in JEI it will only show the seed for now until the fix I just did gets put on curse forge. and yes it seems to be a problem with how betterend does their lumecorn block but its not really a problem with how they do their block it's just that getting the corresponding item from a block is the easiest way to do it and the best was for us and the players to be able to set flowers so we just only get the item from the block but yes if they add a block item for their lumecorn block it will work. If I understand it right their lumecorn thing is like a big mushroom?

**Comment by ThatGravyBoat** [comment]
and most times blocks that dont have items will not be accessible to the player so that was also part of the thought process.

**Comment by lerokko** [comment]
Ok, so i can use an item tag for Flowers and you will get the blocks that those items correspond to (like i can add seeds and resourceful bees would make the bees go to the block that is placed by the seeds). And the JEI tab will try to display the item used to place the block if I use block tags.
Problem is till that I can not put lumecorn and lumecorn_seed in the same tag, but I guess this is a betterend problem at this point it should have the seed attached to the block in the first place.

The lumecorn is a glowing flower its like a bunch of rod stacked and all in different block statest to indicate stem, chalice, and the a few blocks of flower (looks like a huge single cob of corn). Breaking the stem block drops the seed. Placing the seed result in a single stem block in the lowest growth stage.

**Comment by ThatGravyBoat** [comment]
No it would be a block tag of lumecorn and lumecorn_seed and in JEI it will only display the lumecorn seed because thats the only block with an item.

**Comment by ThatGravyBoat** [comment]
and you would set your flower to that block tag

**Comment by lerokko** [comment]
Ahh, gotcha. I got confused. I was under the assumption that the seed would place a lumecorn block not a lumecorn_seed block. I check yeah, now it makes sense. I will do that. Only thing is that bees now will also flock to the seed but that's a minor nitpick.

**Comment by lerokko** [comment]
Also, I think it would be better to maybe have a missing texture (or a custom one, or the structure void icon). Anything but the barrier texture cause less experienced players may assume that this entry has been disabled or something like that.
