### ISSUE TITLE
Polination block quesion

### ISSUE THREAD

**Issue by trogarus** [Team-Resourceful/ResourcefulBees#207]
Assuming the code is correct for a bee producing combs, combs set true, and the correct pollination block in an apiary right next to a bee, what wold cause the bee to seem confused and unable to find the pollination block? The resourceful_honeycomb_block.json also has the proper comb resources listed.

**Comment by ThatGravyBoat** [comment]
send the bee json

**Comment by trogarus** [comment]
There you go. Thanks again for the time and help. :)

**Comment by trogarus** [comment]
OK, didn't seem to add the files. Will have to open and paste.

Silver.json

{
  "flower": "thermal:block_silver",
  "hasHoneycomb": true,
  "maxTimeInHive": 600,
  "ColorData": {
    "isBeeColored": true,
    "honeycombColor": "#C6BDC7",
    "primaryColor": "#C6BDC7",
    "secondaryColor": "#8D8A8D",
    "modelType": "ORE"
  },
  "MutationData": {
    "hasMutation": false
  },
  "CentrifugeData": {
    "hasCentrifugeOutput": true,
    "mainOutput": "thermal:ingot_silver"
  },
  "SpawnData": {
    "canSpawnInWorld": false,
    "biomeWhitelist": "tag:OVERWORLD"
  },
  "BreedData": {
    "isBreedable": true,
    "parent1": "Mutant",
    "parent2": "Gravel",
    "breedWeight": 0.1,
    "feedItem": "thermal:ingot_silver",
    "feedAmount": 1
  },
  "TraitData": {}
}

Nickel.json

{
  "flower": "thermal:block_nickel",
  "hasHoneycomb": true,
  "maxTimeInHive": 600,
  "ColorData": {
    "isBeeColored": true,
    "honeycombColor": "#9B9292",
    "primaryColor": "#9B9292",
    "secondaryColor": "#CABBBC",
    "modelType": "ORE"
  },
  "MutationData": {
    "hasMutation": false
  },
  "CentrifugeData": {
    "hasCentrifugeOutput": true,
    "mainOutput": "thermal:ingot_nickel"
  },
  "SpawnData": {
    "canSpawnInWorld": false,
    "biomeWhitelist": "tag:OVERWORLD"
  },
  "BreedData": {
    "isBreedable": true,
    "parent1": "Mutant",
    "parent2": "Gravel",
    "breedWeight": 0.1,
    "feedItem": "thermal:ingot_nickel",
    "feedAmount": 1
  },
  "TraitData": {}
}

**Comment by trogarus** [comment]
Here's this as well

resourceful_honeycomb_block.json

{
"replace": false,
"values": [
"resourcefulbees:aluminum_honeycomb_block",
"resourcefulbees:blaze_honeycomb_block",
"resourcefulbees:bronze_honeycomb_block",
"resourcefulbees:coal_honeycomb_block",
"resourcefulbees:cobblestone_honeycomb_block",
"resourcefulbees:constantan_honeycomb_block",
"resourcefulbees:copper_honeycomb_block",
"resourcefulbees:creeper_honeycomb_block",
"resourcefulbees:diamond_honeycomb_block",
"resourcefulbees:dragon_honeycomb_block",
"resourcefulbees:dust_honeycomb_block",
"resourcefulbees:electrum_honeycomb_block",
"resourcefulbees:elementium_honeycomb_block",
"resourcefulbees:emerald_honeycomb_block",
"resourcefulbees:ender_honeycomb_block",
"resourcefulbees:fluorite_honeycomb_block",
"resourcefulbees:ghast_honeycomb_block",
"resourcefulbees:glass_honeycomb_block",
"resourcefulbees:gold_honeycomb_block",
"resourcefulbees:gravel_honeycomb_block",
"resourcefulbees:iron_honeycomb_block",
"resourcefulbees:lapis_honeycomb_block",
"resourcefulbees:lead_honeycomb_block",
"resourcefulbees:manasteel_honeycomb_block",
"resourcefulbees:netherite_honeycomb_block",
"resourcefulbees:netherrack_honeycomb_block",
"resourcefulbees:nether_quartz_honeycomb_block",
"resourcefulbees:nickel_honeycomb_block",
"resourcefulbees:obsidian_honeycomb_block",
"resourcefulbees:osmium_honeycomb_block",
"resourcefulbees:pigman_honeycomb_block",
"resourcefulbees:prismarine_honeycomb_block",
"resourcefulbees:quartz_enriched_iron_honeycomb_block",
"resourcefulbees:raw_uranite_honeycomb_block",
"resourcefulbees:redstone_honeycomb_block",
"resourcefulbees:refined_glowstone_honeycomb_block",
"resourcefulbees:refined_obsidian_honeycomb_block",
"resourcefulbees:rgbee_honeycomb_block",
"resourcefulbees:rubber_honeycomb_block",
"resourcefulbees:salt_honeycomb_block",
"resourcefulbees:sand_honeycomb_block",
"resourcefulbees:silicon_honeycomb_block",
"resourcefulbees:silver_honeycomb_block",
"resourcefulbees:skeleton_honeycomb_block",
"resourcefulbees:slimy_honeycomb_block",
"resourcefulbees:snowball_honeycomb_block",
"resourcefulbees:soulsand_honeycomb_block",
"resourcefulbees:steel_honeycomb_block",
"resourcefulbees:sulfur_honeycomb_block",
"resourcefulbees:terrasteel_honeycomb_block",
"resourcefulbees:tin_honeycomb_block",
"resourcefulbees:uranium_honeycomb_block",
"resourcefulbees:wither_honeycomb_block",
"resourcefulbees:wither_skeleton_honeycomb_block",
"resourcefulbees:zombie_honeycomb_block"
]
}

**Comment by trogarus** [comment]
Added information for clarity.

Tier 4 apiary with storage, breeding, and breed time updates (storage and breeding block plus apiary), validates as other bees in the apiary seem fine and produce combs. 9 bees in apiary, all different types (no duplicates).

**Comment by trogarus** [comment]
One further question while we're here. Can we nest folders in the bee folder? Say for instance I wanted to separate bees by mod in a modpack. For instance, a Minecraft folder, a Mekanism folder, a Thermal folder, etc. can they be nested and still work without changing code, or would code need to be changed for the mod to find the nested folders?

**Comment by Vaerys-Dawn** [comment]
No code changes needed to use nested folders, it'll work with no problems.

**Comment by trogarus** [comment]
> 
> 
> No code changes needed to use nested folders, it'll work with no problems.

Thanks much. Will be nice to organize bees according to mod :)

**Comment by Epic428** [comment]
Is this ok to be closed or still an issue?

**Comment by trogarus** [comment]
Today I figured out that this was operator error. To explain simply, mods involved have the following tag format:

minecraft:metal_block/metal_ingot format
thermal:metal_block/metal_ingot format
mekanism:block_metal/ingot_metal format
immersiveengineering:storage_metal format
botania:metal_block/metal_ingot format

I inadvertently switched the thermal format, which caused the confusion issue, and it took me days to notice it.

Sorry about that. Once again, thanks for the work your team puts into this mod.

**Comment by Epic428** [comment]
Ah perfect! Let us know if you have any other issues!
