### ISSUE TITLE
Tier 4 locked apiary and breeding module loop

### ISSUE THREAD

**Issue by trogarus** [Team-Resourceful/ResourcefulBees#208]
**Describe the bug**
Locked apiaries seemingly cause a bee breeding loop.

**To Reproduce**
1.Lock the bees in the apiary
2. Place separate bees in breeding module with appropriate feeding materials and bee jar for bread bee
3. Bee breeding icons seem to follow through the breeding process but loop back without breeding
4. These are seperate bees not locked in the apiary and unlocking the other bees from the apiary allow for the breed process to complete.

**Expected behavior**
Bees would still breed despite other bees being locked in the apiary.

**Screenshots or Crash Logs**
No crash

**please complete the following information:**
 - Forge Version 1.16.5 36-1-3
 - Mod Version ResourcefulBees-1.16.5-0.6.5b.jar

**Comment by Epic428** [comment]
While the apiary structure is needed for the breeder block to be used they function independently of each other and locking bees in the apiary should have zero impact on the ability for bees to breed. I’ll see if I can reproduce just to rule out nothing funky but by design there should be no issue

**Comment by Epic428** [comment]
We cannot reproduce this issue. the only thing we can think of is that your apiary output is full in which case it'll loop but not consume items.

**Comment by trogarus** [comment]
Tried this again yesterday. Still seems to be a problem. Same process, same result, and unlocking the bees in the apiary completed the breeding function as stated in original issue. Just an update.

**Comment by trogarus** [comment]
No, apiary is drained by mekanism pipes to collect combs. I can tell you that it is not full, and operates fine when unlocking the bees in the apiary. Bee in jar then shows up in my collection system. Not sure what is causing it, unless it's some funky mod interaction issue.

**Comment by Epic428** [comment]
Can you provide me with more details or a video of it happening or a world that I can see the issue first hand? Bc everything I’ve tried to reproduce the issue I was unable to do so. Apiary locking/unlocking has absolutely nothing to do with the breeder. Their logic isn’t even tied together.

As an example it’s like saying if I lock the front door of my house then my kitchen faucet doesn’t let water out but if I unlock it then it does.

**Comment by Epic428** [comment]
I’m not sure what your code reading ability is like but this is all of the code that is has to do with processing a breed in an apiary. None of the processing code has a single reference to the apiary TileEntity checking for if a bee is locked or unlocked. 

https://github.com/Resourceful-Bees/ResourcefulBees/blob/master/src/main/java/com/resourcefulbees/resourcefulbees/tileentity/multiblocks/apiary/ApiaryBreederTileEntity.java

https://github.com/Resourceful-Bees/ResourcefulBees/blob/0965a127a466a689a451f8b17f30d87d7034844b/src/main/java/com/resourcefulbees/resourcefulbees/tileentity/multiblocks/apiary/ApiaryStorageTileEntity.java#L235
