### ISSUE TITLE
Vanilla bees interaction

### ISSUE THREAD

**Issue by bloche1871** [Team-Resourceful/ResourcefulBees#21]
**Is your feature request related to a problem? Please describe.**
Vanilla bees cannot breed with resourceful bees, vanilla bees cannot use beehives from this mod, and resourceful bees cannot use vanilla beehives.

**Describe the solution you'd like**
Vanilla bees should be able to breed with resourceful bees and they should be able to use each others' beehives. It should be possible to define vanilla bees as one of the parents when defining a custom bee species.

**Comment by Epic428** [comment]
Sorry It's taken me so long to respond to this. I took a break for a week or two and spent the past two weeks working hard on a new Apiary Multiblock.

I don't personally see the benefit of having vanilla bees utilize our mod's beehives. For the amount of resources our mod produces it doesn't make sense to have equally as many vanilla honeycombs produced. It wouldn't be hard to add the compatibility it just doesn't make sense for what our mod does. Making our bees use vanilla would require us to coremod vanilla hives, and honestly that makes even less sense than the former scenario. 

Lastly, I could see the benefit of having vanilla bees as a parent for the breeding mechanics but haven't decided how I want to handle it. I could make "Vanilla" a reserved keyword that could never be used as a bee type, and go that route, which may be the best option. Alternatively, you could technically rip the vanilla bee textures and make your own "vanilla" bee that has all the same capabilities as a vanilla, generates the same honeycombs, etc if you really wanted and the bee would also be breedable in that instance. Personally, I find the latter option a bit more hacky for what it's worth. If you've any other ideas feel free to comment them.

**Comment by ThatGravyBoat** [comment]
Vanilla bees can now use our modded hives.

**Comment by ThatGravyBoat** [comment]
as of 1.16.3 dev.
