### ISSUE TITLE
Compatibility with performant

### ISSUE THREAD

**Issue by Jordan231111** [Team-Resourceful/ResourcefulBees#211]
**Is your feature request related to a problem? Please describe.**
I hope this mod can be compatible with performant again in future updates.
**Describe the solution you'd like**
This mod being compatible with performant
**Describe alternatives you've considered**

**Additional context**

**Comment by Vaerys-Dawn** [comment]
we do not ever plan on adding compatibility with performant, it is a very messy mod that completely breaks how AI and ticking (things that do things every second) objects/entities in the game work, this mod is very heavily entity focused, if you want any performance increases while using this mod, use fewer bees.

**Comment by Vaerys-Dawn** [comment]
if you still want to use performant while playing with this mod we have a toggle in the config that bypasses the warning
