### ISSUE TITLE
Invalid Honeycomb Color 9090A3

### ISSUE THREAD

**Issue by jondmarien** [Team-Resourceful/ResourcefulBees#213]
Mod Version: 1.16.5-0.6.6a
Minecraft Version: 1.16.5
Minecraft Version ID: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_242, AdoptOpenJDK
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
Memory: 1148139384 bytes (1094 MB) / 3060793344 bytes (2919 MB) up to 6203899904 bytes (5916 MB)
CPUs: 4
FML: 36.1
Forge: net.minecraftforge: 36.1.4

[crash-2021-04-10_00.28.45-fml.txt](https://github.com/Resourceful-Bees/ResourcefulBees/files/6289222/crash-2021-04-10_00.28.45-fml.txt)

**Comment by ThatGravyBoat** [comment]
Change the honeycomb color to `#9090A3` instead we dont support values that dont start with # or are one of the preset colors.

**Comment by jondmarien** [comment]
this isnt my choice its in a pack bro
idk how to fix that

**Comment by ThatGravyBoat** [comment]
what pack?

**Comment by jondmarien** [comment]
Brass

**Comment by ThatGravyBoat** [comment]
well then put it on their issue tracker as its not an issue with us its an issue with them not using the proper color format

**Comment by Nuclearsmilz** [comment]
okay well my bad like, i thought this was a bug for the mod guess i cant play a pack then thanks

**Comment by jondmarien** [comment]
If they can easily change it by adding a '#' then what file do i have to edit for that?

**Comment by ThatGravyBoat** [comment]
in the config folder there is a folder called `resoucefulbees` and in there is a folder called `bees` and I would assume it may be a problem with all the the bees but there should be a json called osmium.json you need to open it and find where it says `honeycombColor` and change it to be `#9090A3` instead of `9090A3`

**Comment by jondmarien** [comment]
thank you

**Comment by ThatGravyBoat** [comment]
Did it work fine?

**Comment by jondmarien** [comment]
i will let you know in a bit i just gotta check the files

**Comment by jondmarien** [comment]
yep, it was the Osmium.json file. thank you
