### ISSUE TITLE
Prismarine Bee Nests

### ISSUE THREAD

**Issue by leyxcx** [Team-Resourceful/ResourcefulBees#214]
**Describe the bug**
This might be intended, but prismarine bee nests generate way too often, leaving parts of oceans covered in them 

**To Reproduce**
/locate any ocean biome and fly around

**Expected behavior**
The nests to be rarer or more spread out, they appear every other chunk most of the time

**Screenshots or Crash Logs**
![10042021(2)](https://user-images.githubusercontent.com/67163463/114268809-3d86aa80-9a57-11eb-86d2-55d0b4146f8f.png)
![10042021(1)](https://user-images.githubusercontent.com/67163463/114268812-437c8b80-9a57-11eb-83a6-dd9effda05a5.png)
![10042021](https://user-images.githubusercontent.com/67163463/114268814-47a8a900-9a57-11eb-8568-2348a78cc7b1.png)
![10042021(3)](https://user-images.githubusercontent.com/67163463/114268888-a2420500-9a57-11eb-8e87-09b0f3abe4aa.png)

**please complete the following information:**
 - Forge Version: 1.16.5 36.1.4 
 - Mod Version: 0.6.5

**Comment by Epic428** [comment]
I’ll have to add explicit checks for ocean biomes to reduce the generation rates there. There’s less configured features for oceans than other biomes so it means ours generate more frequently as a result. But tbh it’s probably good to have since you need 1024 nests for an apiary

**Comment by krokots** [comment]
Just to confirm, I have this issue too. And that's with the lowest spawning option.
![2021-07-27_20 56 39](https://user-images.githubusercontent.com/25055882/127212516-329279f7-2fc3-464e-8d5b-b88057a18d60.png)

**Comment by Vaerys-Dawn** [comment]
fixed a while back
