### ISSUE TITLE
Ender & RGB bees

### ISSUE THREAD

**Issue by Dragonianz** [Team-Resourceful/ResourcefulBees#217]
I am playing Sky Bees version 3 fixed on forge 36.1.3

The issue is when running ender or rgb honeycomb through any centrifuge, nothing happens, the centrifuge just stops until i remove the honeycomb out.
Ender should produce dragonsbreath , ender pearl & wax
RGB should produce

**Comment by Epic428** [comment]
Are you sure they have centrifuge recipes and not crafting recipes?

**Comment by Dragonianz** [comment]
double checked the Beepedia in game, I was wrong about RGB but the Ender does get its Ender Pearls and Dragon Breath from being run through a centrifuge.

**Comment by ThatGravyBoat** [comment]
did you put glass bottles in the centrifuge? because some recipes require bottles

**Comment by Epic428** [comment]
Yeah one of our discord members informed me that the Ender bee combs only have recipes using bottles in the centrifuge.

**Comment by Epic428** [comment]
Closing this since it’s a pack design issue and not an issue with us specifically
