### ISSUE TITLE
Honeycomb recipes don't work in Multiplayer Servers

### ISSUE THREAD

**Issue by AlexVaughn** [Team-Resourceful/ResourcefulBees#219]
When on a multiplayer server (paid service, not LAN), creating resources from honeycombs via any centrifuge is not producing anything. Honeycombs aren't even consumed by the machine. I noticed this while playing All the Mods 6. I play tested the same modpack in single player creative mode and everything seems to work fine.

1. Load into a multiplayer server
2. Place any honeycomb (other than the vanilla minecraft one) into any centrifuge.
3. Attempt to process the honeycomb
4. Nothing happens

You should be able to place honeycombs, such as diamond honeycombs, into a centrifuge and a diamond ore would be produced.

 - Forge Version: forge-36.1.2
 - Mod Version: ResourcefulBees-1.16.5-0.6.6a
 - Modpack: All the Mods 6: 6-1.5.10b

**Additional context**
IMPORTANT: The recipes for turning honeycombs into resources via centrifuge are non-existent (In the JEI)

**Comment by ThatGravyBoat** [comment]
Fixed in dev
