### ISSUE TITLE
Bee Compass

### ISSUE THREAD

**Issue by TemperedFool** [Team-Resourceful/ResourcefulBees#220]
**Is your feature request related to a problem? Please describe.**
Finding Bees! Once things like BOP, BYG, or other biome mods get added, bees end up spawning in a number of different biomes.

**Describe the solution you'd like**
A Bee Compass. Similar function to Nature's Compass, but rather than select a specific biome, you select a bee and it points to the nearest valid spawn location.

**Describe alternatives you've considered**
Just legging it around and searching. This works fine, but there's a lot of world out there, and if bees have a selection of relatively rare or infrequent biomes it can be tricky to find them.

**Additional context**
We're using BYG + a few other biome mods & Terraforged in E6 - makes for very nice world gen, but a pretty large biome list. Maybe this issue is specific to us, but in trying to spread out where bees spawn somewhat logically (say Sand bees in sandy biomes and Water bees in wet non-ocean ones) it can be a bit tricky to figure out exactly where to look for them.

**Comment by Vaerys-Dawn** [comment]
not going to implement as it would basically be just the same implementation as natures compass
