### ISSUE TITLE
Bees disappear from Apiary Breeder

### ISSUE THREAD

**Issue by fightmesun** [Team-Resourceful/ResourcefulBees#221]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**
1. Insert breeding pair of jarred bees (ex: glow and stoned) along with the items to start the breeding (hemp, glowstone, and empty jars)
2. Add two breed time upgrades 
3. Watch as the progress bar fills up.
4. When filled, everything disappears. 

**Expected behavior**
A third bee (a copy of one of the parents or one of the mutations) to show up in the last slot and for the breeding apir to still be in the intial slots.

**please complete the following information:**
 - Forge Version 16.5 36.1.2
 - Mod Version  0.6.7b

**Additional context**
At first I was breeding a rgbee and a redstone bee and I thought I had accidentally killed them. I was fighting some mobs and I have a chain lightning ability from astral sorcery. So I tried to breed another redstone bee with the glowing and stone bee and those disappeared as well. I have a multiblock centrifuge connected to it and I checked it and extractor just in case. I also checked the storage and they weren't there either

**Comment by Vaerys-Dawn** [comment]
while attempting to find this bug I found a crash that might be related, could you update 0.6.7_1b and tell me if this bug still happens?

**Comment by Vaerys-Dawn** [comment]
I just uploaded the file so it may take a second to process

**Comment by fightmesun** [comment]
i did and now it turned to a full on crash xD

**Comment by Vaerys-Dawn** [comment]
can you please upload the crash log

**Comment by fightmesun** [comment]
oh yeah that would help. Sorry about that

https://paste.atlauncher.com/view/e7c1687c-8b85-4706-9dbe-0324b7d19354

**Comment by Vaerys-Dawn** [comment]
looks like you are still using the old version hence the crash

**Comment by Vaerys-Dawn** [comment]
you may have to wait til the pack updates, as CTiers and creative apiary don't work with the updated version

**Comment by fightmesun** [comment]
CTiers?

**Comment by starforcraft** [comment]
> 
> 
> you may have to wait til the pack updates, as CTiers and creative apiary don't work with the updated version

They do, I made a fix 1 day ago

**Comment by Vaerys-Dawn** [comment]
no, you did not, it still won't be compatible with 0.6.7.1b, you need to change the dependency to 

```[[dependencies.ctiers]]
    modId="resourcefulbees"
    mandatory=true
    versionRange="[1.16.5-0.6.7,)"
    ordering="NONE"
    side="BOTH"```

**Comment by starforcraft** [comment]
> 
> 
> no, you did not, it still won't be compatible with 0.6.7.1b, you need to change the dependency to
> 
> ```
>     modId="resourcefulbees"
>     mandatory=true
>     versionRange="[1.16.5-0.6.7,)"
>     ordering="NONE"
>     side="BOTH"```
> ```

It is compatible with 0.6.7.1b I don't need to change that

**Comment by Vaerys-Dawn** [comment]
🤦 oh, so you did...

**Comment by Vaerys-Dawn** [comment]
anyhow, closing this, should be fixed in latest
