### ISSUE TITLE
cintrufugator doesnt work for me with mod honey combs

### ISSUE THREAD

**Issue by pabloax** [Team-Resourceful/ResourcefulBees#223]
I´m doing anything wrong? i introduce the honeycombs in the centrifugator and it just work with the original honey combs, but not with the one form mods.

some screenshots:

https://prnt.sc/11nnzo5

https://prnt.sc/11no02f

**please complete the following information:**
 - Forge Version  1.5.7
 - Mod Version

**Comment by Vaerys-Dawn** [comment]
what version of the mod are you running on, if it's 0.6.6, update to 0.6.71b

**Comment by pabloax** [comment]
> what version of the mod are you running on, if it's 0.6.6, update to 0.6.71b


Author epic_oreo
ResourcefulBees-1.16.5-0.6.5b.jar

**Comment by Vaerys-Dawn** [comment]
yeah, update to latest, that bug should be fixed in latest.

**Comment by pabloax** [comment]
> yeah, update to latest, that bug should be fixed in latest.

Im playing on a server i dont know if this is gonna mess up something, the mod is from all the mods 6.

**Comment by Vaerys-Dawn** [comment]
the server needs to update the pack
