### ISSUE TITLE
Can not create a new world with Resourceful Bees + Caves and Cliffs Mod

### ISSUE THREAD

**Issue by agentwolf88** [Team-Resourceful/ResourcefulBees#224]
**To Reproduce**
Install CAC+MOD+[1.16.5]+[2021.2-pre4]
Install ResourcefulBees-1.16.5-0.6.7.2b
Start game
Create a new world

**Screenshots or Crash Logs**
[debug-1.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/6343373/debug-1.log)

**please complete the following information:**
 - Forge Version 1.16.5 - 36.1.4
 - Mod Version 0.6.7.2b

**Comment by Epic428** [comment]
Have you modified the valid_apiary tag in any way? It’s crashing on the tag which is unrelated to the mod that you’ve mentioned and I know the default version of the tag wouldn’t cause a crash

**Comment by agentwolf88** [comment]
I have edited the spwan data of "dungeon.json" from "biomeBlacklist": "tag:nether", to "biomeBlacklist": "tag:nether,tag:ocean"
The Dungeon Bee is spawning on warm ocean in my modpack.

**Comment by Epic428** [comment]
Well the crash is for the valid_apiary tag. But your syntax for the biome blacklist is also incorrect. It should be “tag:nether, ocean”

**Comment by agentwolf88** [comment]
Ok. I have deleted the config of RB but world creation does not work. What can i do? :(

**Comment by Epic428** [comment]
Can you provide a new log?

**Comment by Epic428** [comment]
![22783E48-6A26-4B6C-A8D8-6CE856A18734](https://user-images.githubusercontent.com/291578/115421279-cfb24f80-a1c9-11eb-95ec-b86d54c9c19a.png)


This is a screenshot of the error message in your first log. I’d bet anything that it’s the same error in your other logs. Are you playing on a mod pack or custom pack?

**Comment by Epic428** [comment]
Generally you would see that crash if one of the entries is bad. I’m not at home on my pc and doing this from mobile so I can’t search the log easily. But I bet further up it’ll actually say what broke in the tag.

**Comment by agentwolf88** [comment]
I play with two mods. RB and Caves and Cliffs Mod. Here my logfiles.

[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/6344658/latest.log)
[debug.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/6344659/debug.log)

**Comment by agentwolf88** [comment]
Minecraft say the mod is incompatible.

![Unbenannt](https://user-images.githubusercontent.com/9948479/115424062-9f38d880-a1fe-11eb-9827-612e5c69278c.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/9948479/115424067-a233c900-a1fe-11eb-8431-3792b88163c2.PNG)

**Comment by Epic428** [comment]
![A7E8C637-D3C4-474D-85AB-4EE5390EFE93](https://user-images.githubusercontent.com/291578/115432261-2d4b9980-a1d4-11eb-95aa-e221c4210cf7.png)

read the text in the screenshot that I sent you. Bc you have 3 broken tags likely Bc the item IDs that you are referencing in the tags are not correct. It has nothing to do with our mod. Our data pack is fine. You have broken tags that are causing other broken tags. Either Bc you made changes in a datapack or Bc the caves and cliffs mod has a broken entry in the forge:stone tag. 

closing this issue as it is not something we need to fix
