### ISSUE TITLE
Bees not entering apiary

### ISSUE THREAD

**Issue by m0V1NGt4RG3T** [Team-Resourceful/ResourcefulBees#225]
running direwold20 1.16 pack v1.8.0
added resourceful bees v1.16.5-0.6.5b, bees would pickup pollen and enter hives as expected.
trying to fix centrifuge bug, updated to resourceful bees v1.16.5-0.6.7.2b after update gold and diamond bees are flying around apiary but will not collect pollen / re-enter apiary. have tried removing bees, reimporting them through apiary as well as releasing them into apiary manually.
regular bees in apiary will gather pollen but also not enter apiary.

all bees are configured as default by mod.

apiary multiblock works and I'm able to import / export / breed and access inventory.

previously bees that would not use apiary could be corrected by using the dipper, that no longer corrects issue either.

**Comment by Epic428** [comment]
If you are using our default mod version with no changes to any configs then check the flowers for the bees as they have been changed

**Comment by m0V1NGt4RG3T** [comment]
My apologies they do collect pollen, I missed the particle effects coming off of them.
I had already placed the storage blocks in the apiary.

ill try rebuilding the multiblock but here is screenshot of it currently.
![image](https://user-images.githubusercontent.com/82681722/115409550-d89e2380-a1bf-11eb-8346-ea84ba2a5006.png)

**Comment by m0V1NGt4RG3T** [comment]
breaking wall(s) of the multiblock did nothing.
removed the main apiary block and replaced it, all bees are once again functioning normally.
