### ISSUE TITLE
Bees forgetting bound flower after entering apiary

### ISSUE THREAD

**Issue by thirtythieves** [Team-Resourceful/ResourcefulBees#228]
**Describe the bug**
I set multiple bee's flower positions using the honey dipper. This worked until they entered and exited my apiary, in which they all attempted to pollinate the same flower.

**To Reproduce**
1. Set Bee's flower using the honey dipper(while in apiary)

**Expected behavior**
I was expecting them to not forget the flower while using an apiary.

**please complete the following information:**
 - Forge Version - 1.16.5 36.1.0
 - Mod Version 0.6.5b

**Comment by Epic428** [comment]
update your mod version to the latest
