### ISSUE TITLE
Bee Not Spawning Underground

### ISSUE THREAD

**Issue by TemperedFool** [Team-Resourceful/ResourcefulBees#229]
**Describe the bug**
Using the Min/Max Y level to target a bee underground does not seem to be causing bees to spawn. To be honest, it doesn't seem like any bees are spawning underground. I tested this by loading an instance with just Resourceful Bees and World Stripper - stripping many chunks while looking for bees to spawn. I was flying around in peaceful, so the bees aren't being competed out by hostile mobs.

**To Reproduce**
1. Install an instance with just Resourceful Bees and World Stripper
2. Use the bee JSON supplied below
3. Search for bees underground

**Expected behavior**
I'm hoping to be able to target some bees underground, and require players to go caveing to find them.

**Screenshots or Crash Logs**
None - Bee JSON at the bottom.

**please complete the following information:**
 - Forge Version - 36.1.4
 - Mod Version - 0.6.7.1b

**Additional context**
Example Bee JSON:

```
{
    "flower": "ALL",
    "maxTimeInHive": 2400,
    "sizeModifier": 0.75,
    "hasHoneycomb": true,
    "traits": ["can_swim"],
    "baseLayerTexture": "ores/coal/coal_bee",
    "ColorData": {
        "honeycombColor": "#303030",
        "isBeeColored": false,
        "isRainbowBee": false,
        "isGlowing": false,
        "isEnchanted": false,
        "modelType": "ORE"
    },
    "CombatData": {
        "isPassive": false,
        "removeStingerOnAttack": true,
        "inflictsPoison": true,
        "attackDamage": 1
    },
    "MutationData": {
        "hasMutation": true,
        "mutations" : [
          {
            "type": "BLOCK",
            "inputID": "tag:forge:stone",
            "outputs": [
              {"outputID": "emendatusenigmatica:coal_ore", "weight": 10}
            ]
          }
        ]
    },
    "CentrifugeData": {
        "hasCentrifugeOutput": true,

        "mainOutput": "emendatusenigmatica:coal_chunk",
        "mainOutputWeight": 0.5,
        "mainOutputCount": 2,

        "secondaryOutput": "resourcefulbees:wax",
        "secondaryOutputWeight": 0.5,
        "secondaryOutputCount": 3,

        "bottleOutput": "resourcefulbees:coal_honey_bottle",
        "bottleOutputWeight": 0.02,
        "bottleOutputCount": 1,

        "mainInputCount": 1
    },
    "SpawnData": {
        "canSpawnInWorld": true,
        "biomeWhitelist": "tag:OVERWORLD",
        "biomeBlacklist": "tag:OCEAN",
        "minGroupSize": 2,
        "maxGroupSize": 3,
        "spawnWeight": 50,
        "minYLevel": 12,
        "maxYLevel": 75,
        "lightLevel": "ANY"
    },
    "BreedData": {
        "isBreedable": true,
        "feedItem": "tag:forge:storage_blocks/coal",
        "feedAmount": 1,
        "childGrowthDelay": -24000,
        "breedDelay": 6000
    },
    "TraitData": {
        "hasTraits": true
    }
}
```

**Comment by Epic428** [comment]
Just wanted to put some info on this issue. I didn’t look into it specifically yet but I did happen to look at entity spawn placements and did a quick comparison with the zombie. We use the same height map and spawn rules so I’m not entirely sure what’s keeping them from spawning underground. I need to look a little bit deeper in the hostile mob classes to find out.

**Comment by TemperedFool** [comment]
I don't want to discount the idea that I've made a mistake here - would be happy enough to hear "it works over in this pack with these settings". Only reason I think it might not be me is the world stripper + only RB testing I did.

**Comment by Epic428** [comment]
I’m not sure that much testing has been done on the y-level restricted spawning tbh. It was kind of a “hey we can check this value here, let’s do it” thing. I just happened to be looking at the method for something else and figured I’d take a peek quick but wasn’t able to find anything that was different between our bees and a zombie.

**Comment by Epic428** [comment]
Dawn and I tested this a while back and we’re able to confirm that bees do spawn underground they are just exceedingly rare. Not sure if I should leave this open or close.
