### ISSUE TITLE
1.16.5 How disabled this message?

### ISSUE THREAD

**Issue by ghost** [Team-Resourceful/ResourcefulBees#230]
Hi, what option in config disabled this message? Link in message not found

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/36424845/115504421-97ba1380-a280-11eb-8ba1-5f2d47598510.png)

** Mod version **
ResourcefulBees-1.16.5-0.6.7.2b
Forge-1.16.5-36.1.9

**Comment by agentwolf88** [comment]
Delete "performant" mod.

**Comment by ThatGravyBoat** [comment]
it says right there the bypassPerformantCheck config value
