### ISSUE TITLE
Apiary Bees import !

### ISSUE THREAD

**Issue by G4mer0815** [Team-Resourceful/ResourcefulBees#232]
why can't I put all of the bees in the apiary right away? I have to wait for the cooldown first? bug?
What i mean apiary import cooldown.

**Comment by Epic428** [comment]
You can only have one of each bee type inside of the apiary block at a time. If you want to import additional bees to the structure you’d have to unlock the bee and wait for it to pop out before you can import the next one. Hence the “unique” aspect to the block in its tool tip

**Comment by G4mer0815** [comment]
hm this is crap!

**Comment by ianwijma** [comment]
@G4mer0815 any plans to make this a config option to enable / disable this?

**Comment by Epic428** [comment]
No

**Comment by ianwijma** [comment]
What if I work on a PR to make this possible? or would it be out of scope of the project? :)

**Comment by Epic428** [comment]
It would go against the design intent of the apiary not to mention it would require being rewritten since I purposefully use a hashmap vs an arraylist.

**Comment by ianwijma** [comment]
Aahh okay, that's alright.
