### ISSUE TITLE
Blacklist oceans as default for dungeon bees

### ISSUE THREAD

**Issue by Zygus42** [Team-Resourceful/ResourcefulBees#234]
I'm finding that for my server there are still too many special bees spawning even though I have set the number in config to the maximum (100), which represents 1/100 according to the config notes.   Would love it if you could increase the max number in the config.

**Comment by Epic428** [comment]
that value is specific to nest generation only, not bee spawning. if you want to reduce the bee spawns then you need to change their spawn weight to be like that of the oreo bee

**Comment by Zygus42** [comment]
Well, 1 bee seems to come with each nest, so if there are less nests, there will be less bees - no ?  And there are way too many nests at 1/100 - particularly in the ocean biomes:
![2021-05-10_16 15 42](https://user-images.githubusercontent.com/20757445/117627700-036e0d00-b1ab-11eb-982a-03372d98012a.png)

And if I wanted to change the bee spawn individually, there doesn't seem to be a file for the Oreo bee I can look at in the Bees folder - what am I missing here ?

**Comment by Zygus42** [comment]
Further to this, when I change the file for Dungeon bees to have a blacklist for oceans, it resets the file back to base whenever I restart the game.

**Comment by Epic428** [comment]
Oreo and kitten bee are hardcoded dev bees that can’t be modified. Only way to change them is to turn off Easter egg bees and recreate them. Nests always spawn with 0-3 bees in them and only the bees that can spawn in the biome the nest generated in will spawn. Ocean biomes have like no world gen features. As such our nest feature is likely to get selected more frequently. I can’t change the feature based on the biome Bc. That would be absurd for our kind of mod. Instead I can reduce the frequency a nest will generate on a water source block as a compromise.

**Comment by Zygus42** [comment]
At the moment the only bee spawning in the ocean is the dungeon bee, which then also take damage from water and die, leaving tons of empty prismarine nests.  Doesn't make a lot of sense.  But I've tried adding oceans to the spawn biome blacklist, and it resets the dungeon bee file and reverts all my changes back to basic settings when I restart the game.

**Comment by Zygus42** [comment]
All of this might well be because some other mod is mucking with your gen - I'm not really sure.

**Comment by Epic428** [comment]
Ah I knew I forgot something in my last reply. Turn generate defaults to false in our Config to overwrite default bees

**Comment by Zygus42** [comment]
Yay - that combination worked.  I would suggest you blacklist oceans as the default settings for dungeon bees.  Thanks for the assist.

**Comment by Epic428** [comment]
Will do

**Comment by Epic428** [comment]
Updated title to reflect what needs to be fixed as a result of the above conversation

**Comment by Vaerys-Dawn** [comment]
dungeon bees should now no longer spawn in ocean hives as hives now check for y level of the bee for spawning.

They may still spawn the hives tho. 

"don't care if they're empty" - gravy
