### ISSUE TITLE
JEI integration problems

### ISSUE THREAD

**Issue by NinjaChicken2017** [Team-Resourceful/ResourcefulBees#236]
If you right or left click on a bee in JEI/NEI it doesnt bring anything up

**Comment by Epic428** [comment]
What mod version and pack? Bc it works and has worked for a very long time. So if nothing is showing up it’s most likely Bc nothing exists.

**Comment by NinjaChicken2017** [comment]
pack: sky bees
mod Version: 1.16.5-0.6.5b

**Comment by Epic428** [comment]
Update the mod to 0.6.7.2b. When you do the sieve be is missing a # in front of one of its colors. You’ll also need to target a newer forge version as well.

**Comment by NinjaChicken2017** [comment]
ok, thanks ill try that

**Comment by Epic428** [comment]
No problem. Let me know if you still have issues. That latest mod version has jei syncing issues fixed as well as some other major improvements to the bees that make it worth updating.
