### ISSUE TITLE
Bees fight over same block when others are available

### ISSUE THREAD

**Issue by AndrewR73** [Team-Resourceful/ResourcefulBees#237]
Minecraft Version: 1.16.5
Forge Version: forge-36.1.3/forge
Mod Version: ResourcefulBees-1.16.5-0.6.5b
Pack: Sky Bees ("Final Version 3 fixed.zip")

**Describe the bug**
Bees fight over same block when others are available

**To Reproduce**
Create an Apiary structure, place at least 2 blocks of each type and at least 2 bees of matching type, the bees will "fight" over one block/flower for pollination despite having other blocks/flowers to go to.

**Expected behavior**
Each bee should seek out a block/flower of its matching type, but if that block/flower is in use it should then attempt to pollinate from another block/flower not in use (if available).

**Screenshots or Crash Logs**
In this screenshot here, I have 2 bees of each type, with 2 blocks of each "flower" type as well. Despite that however, the bees will fight over the same block instead of one bee going to one block and the other bee to the other block.
![2021-05-04_16 38 33](https://user-images.githubusercontent.com/8558973/117202339-4f880e80-adb3-11eb-90a1-b88818eedc39.png)
*Note the Copper and Lead bees in this shot for example

In this screenshot, in a different Apiary, instead of separating the blocks of the same type, I placed them together thinking maybe the bees would find/see them easier... but this was not the case. Again, the fighting over the same block(s) occurs:
![2021-05-05_09 40 14](https://user-images.githubusercontent.com/8558973/117202348-531b9580-adb3-11eb-85e5-c4a5ad4da5d5.png)
*Note the Wither bees head-to-head, and in the upper right the Zombie, Gravel, and Cobblestone bees are all fighting for the same poppy and bouncing off each other.

**Additional context**
Some additional "sciencing" of the issue, it appears the bees are fighting over the block/flower of their type that is furthest North and/or West, and see only that block as viable despite how many are available or not in use. Not for certain on this, but this seems the case most often.

**Comment by darling** [comment]
see #235

**Comment by Epic428** [comment]
^^^ closing
