### ISSUE TITLE
Hive Upgrades

### ISSUE THREAD

**Issue by Floppa-8765** [Team-Resourceful/ResourcefulBees#238]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**
1. Get a bee hive upgrade (in my case tier 2 to tier 3 then tier 3 to tier 4)
2. Click on your hive
3. the hive works as the tier upgraded to but does not change texture to it or name
**Expected behavior**
Bee hive upgrades

**Screenshots or Crash Logs**
![image](https://user-images.githubusercontent.com/51796333/117497423-77f44200-af46-11eb-8c8d-6bb40e99b251.png)

**please complete the following information:**
 - Forge Version [1.16.5 36.1.2]
 - Mod Version [1.16.5-0.6.7.2b]

**Additional context**

**Comment by Floppa-8765** [comment]
sorry about the mahou, dont know how to hide it

**Comment by Epic428** [comment]
yeah I can't change the name bc there's no way to get the data I need in the method that changes the name. the hives are being removed and as such the name won't matter. instead the hive upgrades will be used on the pretty nests. texture also won't be changed bc the registry id for the block doesn't change only an internal value. again this won't be an issue with the removal.
