### ISSUE TITLE
Any bees that are spawned in with a spawn egg refuse to breed.

### ISSUE THREAD

**Issue by TahoeBennie** [Team-Resourceful/ResourcefulBees#239]
**Describe the bug**
Whenever you try to breed bees that were spawned in with a spawn egg, it does not work and the bees ignore each other until they are able to breed again for the same process to happen over and over except any time past the first, the bees only accept 1 item instead of the usual 5 of something.

**To Reproduce**
1. Spawn in two bees with spawn eggs
2. Give them their correct items to breed

**Expected behavior**
The bees should breed together and make the corresponding bee type of what they breed for.

**please complete the following information:**
 - Forge Version 1.16.5 - 36.1.2
 - Mod Version 0.6.7.2b

**Additional context**
Bees wont breed if they are spawned in by a spawn egg instead of found in the world (except in the apiary breeder)

**Comment by Epic428** [comment]
In my experience and testing I have not had this issue but I will confirm again once settled at our new house and pc is back up and running.

**Comment by derrickmehaffy** [comment]
I can confirm this on `0.9.9.4` when using the breeder it will go through the whole cycle and just start over (doesn't consume resources or jar, no output).

In testing I spawned in 1 water bee and 1 lava bee to make an obsidian bee and let it run for about 3 hours.

(Modpack used was All the Mods 6 v1.8.2)

**Comment by derrickmehaffy** [comment]
I can also confirm this on v0.9.9.8 using All the Mods 6 v1.8.9

Breeding them outside of the apiary breeder works fine but if they are inside the breeder it will just restart.

**Comment by ThatGravyBoat** [comment]
I just tested in atm 1.8.10 with rbees version 9.9.8 and it worked fine in the breeder and in-world.
Here are some reasons why your apiary breeder may not work:

1. You don't have the apiary breeder part of a valid apiary structure.
2. You don't have the breeding items in the correct slots.
3. The apiary storage is full so therefore they cannot complete their breed.
