### ISSUE TITLE
Empty Bee Jar stacking

### ISSUE THREAD

**Issue by burshaz** [Team-Resourceful/ResourcefulBees#24]
Just crafted bee jars do not stack with jars that have been used once. A metadata thing?

Resourceful Bees 1.16.1-0.3.2a

**Comment by Epic428** [comment]
Most likely an nbt issue. I’ll take a look at it. In a little bit. I use them heavily in creative mode and they stack so crafting must be doing something wonky as they should stack to 16

**Comment by Epic428** [comment]
This has been fixed and will be available when the next version releases. A workaround until then would be to capture a bee and import it into the apiary as that always creates a new jar itemstack vs reusing the old one.
