### ISSUE TITLE
Actual Bee Ingredients in JEI have different ID than shown in tooltips

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Team-Resourceful/ResourcefulBees#240]
**General Information / Description**

- Forge version: 36.1.0 (userdev)
- Mod version: 0.6.4b

(Note that I only picked this up while adding a method allowing for custom information tabs in JEI to KubeJS)

According to advanced tooltips (F3 + H), the fake Resourceful Bees "items" / ingredients in JEI have an ID pattern of `resourcefulbees:${type}_bee`. Their *true* internal ID for use with JEI Integration (Ingredient Helper etc.) however is `bee:${type}`.

This can (it already has, for that matter) cause confusion downstream when people want to add, say, a custom bit of info to bees, as they're never actually exposed to that internal ID (I myself had to figure that out through the debugger), so I propose streamlining the two for better compatibility with pack and script developers (I assume without having read into it toooo much that the `EntityIngredient` just copies the registry ID of whatever entity it represents?), for example by changing both of them to be the Entity ID instead.

**Screenshots or Crash Logs**
![image](https://user-images.githubusercontent.com/12750501/117864511-2ecd2680-b295-11eb-8c33-bb86a193c09c.png)
(JEI / Minecraft shows Entity ID on tooltip)

![image](https://user-images.githubusercontent.com/12750501/117864492-2a087280-b295-11eb-8c53-07d92dd33473.png)
(Actual ID is different)

**Comment by Vaerys-Dawn** [comment]
that's not JEI's Ingredient ID that's the entity ID, this is intentional and not a bug

**Comment by Vaerys-Dawn** [comment]
we display the entity ID because people may be interested in said id for entity mutations or entity spawning, the average user will not even begin to wonder what the JEI ingredient ID is so we don't show it.

**Comment by MaxNeedsSnacks** [comment]
Fair enough. The main problem was that some users wanted to add additional information to some bees and expect whatever they see on the tooltip to "just work"™️, so it might be useful to put this somewhere still...

(Example made by an Enigmatica 6 dev to illustrate why it may be useful to streamline these):

```java
events.listen('jei.information', (event) => {
  var rbees = [
    'resourcefulbees:brass_bee',
    'resourcefulbees:bronze_bee',
    'resourcefulbees:constantan_bee',
    'resourcefulbees:electrum_bee',
    'resourcefulbees:enderium_bee',
    'resourcefulbees:invar_bee',
    'resourcefulbees:lumium_bee',
    'resourcefulbees:signalum_bee'
  ];
  var entityType = java("com.resourcefulbees.resourcefulbees.compat.jei.JEICompat").ENTITY_INGREDIENT;
  event.addForType(
    entityType,
    rbees,
    [
      "Alloy Bees are made through Block to Item Mutations. Click this Bee's spawn egg in JEI for specifics."
    ]
  );
});
```

**Comment by Vaerys-Dawn** [comment]
we're going to be adding a Lore section to bee jsons that will show up on the entity ingredient and in the beepedia.

what exactly are you asking for?

**Comment by MaxNeedsSnacks** [comment]
I was basically just asking for the actual entity ingredient IDs to be visualised somewhere for the purpose of developing scripts and making packs (like the KubeJS script above, which refers to [this](https://github.com/KubeJS-Mods/KubeJS/blob/5b2d5d0092caef29528e91778068212829edbd02/forge/src/main/java/dev/latvian/kubejs/integration/jei/InformationJEIEventJS.java#L36) method), but the main use case I found for this (custom JEI info tab as seen below) would already have a valid alternative if you guys plan to add lore to your bees as well

![image](https://user-images.githubusercontent.com/12750501/117972798-da28ba80-b32b-11eb-8313-bcd5534249ac.png)

**Comment by ThatGravyBoat** [comment]
We changed it in our current rewrite where we switch to codecs, it seems i by accident switched the unique id with the resource id when i wrote it so they now match properly in dev
