### ISSUE TITLE
Machines cannot accept fluids from Create pipes

### ISSUE THREAD

**Issue by fd347657835178** [Team-Resourceful/ResourcefulBees#241]
**Describe the bug**
The mod Create (https://www.curseforge.com/minecraft/mc-mods/create) adds pipes to carry fluids and pumps to move fluids between blocks. The centrifuge can be drained of honey using a pump, but the pump cannot fill beecons or honey tanks.

**To Reproduce**
1. Install create-mc1.16.5_v0.3.1c and ResourcefulBees-1.16.5-0.6.7.2b
2. Fill a Create tank with Honey (from buckets or by pumping it from a centrifuge)
3. Attach a pump to the tank and power it with a cog such that it is extracting (indicated on the pump with an arrow)
4. Place a honey tank or beecon on the receiving end of the pump
5. The honey tank or beecon will not fill up. Replacing the beecon or honey tank with a Create tank will result in the pump moving honey from one tank to the other.

**Expected behavior**
The pumps should be able to insert honey into Resourceful Bees machines in the same way that they extract honey.

**Screenshots or Crash Logs**
![Extracting from Centrifuge](https://imgur.com/EdNhaIq.png)
The Create tank can fill with honey pulled by pump from the Centrifuge.

![Can't insert into Beecon or Honey Tank](https://i.imgur.com/2evNa2n.png)
The Create pump cannot fill a Honey Tank or Beecon, either when fed through pipe (shown) or when placed directly next to the pump (not shown).

**please complete the following information:**
 - Forge Version 1.16.5 - 36.1.0
 - Mod Version 0.6.7.2b

**Additional context**
This is a cross-mod compatibility issue but I reported it here instead of in Create's issues because the pump does partially work with the Resourceful Bees machines. If you suspect that Create needs an adjustment to fix this, let me know and I will open an issue there instead.

**Comment by fd347657835178** [comment]
A little more information: I tried filling a honey tank from bottles and emptying it with a pump, that did not work either. So the fluid storage in the honey tank is inaccessible in either direction. I'm no modding expert but the (not working) Beecon and Honey tank are both using InternalFluidTank to expose an IFluidHandler, while the (working) Centrifuge is using a MultiFluidTank instance, so comparing those may be useful.

**Comment by Epic428** [comment]
Afaik create pipes work fine with our blocks but I will test and confirm this once I’m settled at our new house and have my pc back up and running.

**Comment by Vaerys-Dawn** [comment]
can reproduce but I cannot for the life of me find why this is breaking... it only happens with some of our containers and not others... it doesn't really make sense, as the difference between the containers should not affect the transfer of fluids. I would recommend bringing this up in the create GitHub as this issue seems to only be caused by create pipes

**Comment by TheOnlyMann** [comment]
https://cdn.discordapp.com/attachments/839993524170915870/877465683670208553/Minecraft__1.16.5_-_Singleplayer_2021-08-18_5_13_37.mp4

dump of normal stuff, havent tested pulling out fron normal centrifuges in this video but iirc ti works

**Comment by fd347657835178** [comment]
This issue is resolved in the latest Create version v0.3.2f

**Comment by Epic428** [comment]
yay!
