### ISSUE TITLE
Dragonic Bee has no flower

### ISSUE THREAD

**Issue by HaansJob** [Team-Resourceful/ResourcefulBees#244]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**
1. Go to 'Dragonic Bee in JEI'
2. Right Click on 'Dragonic Bee'
3. Notice the lack of 'Bee Flower'

**Expected behavior**
Every other bee in JEI has a labled Bee Flower as did the Dragonic Bee in ATM 6 1.6.1

**please complete the following information:**
 - Forge Version 1.16.5 
 - Mod Version ATM 6 1.6.3c

**Additional context**
Please fix

**Comment by Pdiddy973** [comment]
fixed in https://github.com/AllTheMods/ATM-6/pull/1627
