### ISSUE TITLE
does not load textures with shader

### ISSUE THREAD

**Issue by MAXIS05** [Team-Resourceful/ResourcefulBees#245]
I'm having trouble loading the hives textures, using beyond belief shaders 1.16.5, all hives appear as blocks of water, any ideas?  ResourcefulBees-1.16.5-0.6.7.2b
![2021-05-18_14 14 00](https://user-images.githubusercontent.com/84405421/118696406-a72b6e80-b7e4-11eb-9903-a297a462ea64.png)

**Comment by Epic428** [comment]
We don’t actively provide support for optifine. If you’re not using optiforge I recommend using it. Beyond that all I can says is either they work or they don’t.
