### ISSUE TITLE
Bee mutations create item with blank nbt tag

### ISSUE THREAD

**Issue by radiomike** [Team-Resourceful/ResourcefulBees#246]
**Describe the bug**
When doing a bee mutation, items produced have a blank nbt tag, which means they don't stack or behave properly with other mods. An example being compacting drawers from storage drawers.

**To Reproduce**
This is in ATM6 1.6.3c.
Set up bee to pollinate then do a mutation.
Check results of mutation with F3+H. 
Item has a blank nbt{} when it shouldn't have any.

**Expected behavior**
There should be no nbt tag added.

**Screenshots or Crash Logs**
Not applicable

**please complete the following information:**
 - Forge Version 36.1.16
 - Mod Version 1.16.5 - 0.6.7.2b

**Additional context**
Noticed in atm6 pack. Nothing obvious in config files. Also, initially noticed on modded items, but also present on vanilla ones too. Also noted that when looking in JEI at the mutation recipe, the nbt tag does not appear.

**Comment by radiomike** [comment]
Also tested this in new instance. 

-    Forge Version 36.1.16
-    Mod Version 1.16.5 - 0.6.7.2b

Only JEI as additional mod. 

1. Copied iron bee config to new bee name
2. edited new bee to BLOCK_TO_ITEM
3. edited output to "minecraft:iron_nugget"
4. Start instance and set up apiary and set up bee to mutate
5. checked mutated nugget and an additional empty tag is there

**Comment by Epic428** [comment]
Unfortunately given the current state of the core mod logic any fix to this will need to wait until our next release which will still be some time out as we’re completely restructuring the mod and we’ve rewritten the api.

**Comment by Vaerys-Dawn** [comment]
actually this is probably fixable. i'll have to test but I'm pretty sure if you're just copying the template without removing any of the default values, you're likely leaving `"nbt": {}`, which if I understand the code correctly may be adding an empty nbt object

**Comment by Epic428** [comment]
I thought there was a check to not apply nbt if it was empty or null. I’d have to go to an older branch and verify.

**Comment by Vaerys-Dawn** [comment]
hence
> i'll have to test this

**Comment by Epic428** [comment]
:p

**Comment by Vaerys-Dawn** [comment]
hmm, no, it's borked, the nbt tags for items seem to get applied regardless of whether there's a tag there or not, I swear I got that... oh well...

**Comment by Vaerys-Dawn** [comment]
fixed in 0.9.9
