### ISSUE TITLE
Beepedia crash

### ISSUE THREAD

**Issue by OwenBowen222** [Team-Resourceful/ResourcefulBees#248]
**Describe the bug**
The beepedia sometimes causes a client crash, typically upon clicking the traits menu of a bee, or occasionally just pressing enough buttons. 
This may be a hardware or modpack incompatibility but should be looked into nonetheless, as the crash log appears to indicate an issue with the base mod as far as I can tell.
Please review the crash log for more information.

**To Reproduce**
1. Open beepedia
2. Browse around for about 30 seconds - 1 minute, click some buttons (you're gonna want to aim for the "traits" button on different types of bees.)
3. Crash

**Expected behavior**
The beepedia should function as normal, and stay open consistently.

**Crash Logs**
https://pastebin.com/Ddesh3zA
https://pastebin.com/sMX7i2UZ (latest)

**please complete the following information:**
 - Forge Version: 36.1.23
 - Mod Version: 0.6.7.2b
 - Modpack: ATM6 1.6.4
**Additional context**
 - I am not using optifine or any other mod that would modify the rendering engine.
 - The issue could possibly be the result of a certain trait as it does not always happen.
 
If you find the issue, please let me know what it is, even if it is the modpack causing it

**Comment by Vaerys-Dawn** [comment]
one of the custom traits set up has an invalid beepediaItem causing it to crash, this is an issue with the pack itself so i'd recommend  bringing it up to the pack devs

**Comment by OwenBowen222** [comment]
> 
> 
> one of the custom traits set up has an invalid beepediaItem causing it to crash, this is an issue with the pack itself so i'd recommend bringing it up to the pack devs

Do you know which one and how I could fix it manually?

**Comment by Epic428** [comment]
I’m not sure which one it is but I have been informed the pack dev is aware of the issue and has fixed it for the next pack update

**Comment by Epic428** [comment]
Closing this due to being resolved by pack dev
