### ISSUE TITLE
Vary Mutation By Flowers

### ISSUE THREAD

**Issue by WACriminalG2** [Team-Resourceful/ResourcefulBees#252]
**Is your feature request related to a problem? Please describe.**
No problem, just an enhancement request.

**Describe the solution you'd like**
I think it would open up some interesting design space for pack developers if bees could have multiple possible flowers, and their mutation outputs varied dependent on which flowers were nearby. This would allow a single species of bee to assist in crop cross-breeding between multiple different crop pairings, for instance -- Wheat as flower mutates Tomato to Eggplant, but Potato as flower mutates Cucumber to Zucchini. Or whatever.

Could also be used for ore generation -- give the player access to the Ore Bee, which transforms stone into different ores depending on which flower you provide it.

**Comment by Epic428** [comment]
I’ll leave this open in consideration but I don’t believe it’s something that will be implemented

**Comment by Vaerys-Dawn** [comment]
too much complexity for people to understand and would be hard as all hell to explain
