### ISSUE TITLE
Cannot auto collect honeycombs from Hives

### ISSUE THREAD

**Issue by Apollon-Theos** [Team-Resourceful/ResourcefulBees#253]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Cannot collect honeycomb from tier_0, tier_1, tier_2 hives with Intergated Tunnels (both variants - item importer + item exporter, item interface + item exporter) and Industrial Foregoing (with transport belt + export upgrade).
Between machines or storages both mods works normally.

**To Reproduce**
1. Go to : any up to 2 tier hives and any transport system from mods "Integrated Tunnels" or "Industrial Foregoing"

**Expected behavior**
Collect honeycombs from hives to stogage box.

**Screenshots or Crash Logs**
not applicable, because game work, bees flying :)

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5'] 36.1.0
 - Mod Version [e.g. '0.2.0'] ResourcefulBees-1.16.5-0.6.7.1b

**Additional context**

**Comment by 0xC4DE** [comment]
Forgive me if I'm wrong, but I do not believe you are supposed to be able to pull items out of beehives (non apiary specifically) using those methods, rather using shears or honey bottles. Consider using something like a comparator hooked up to a dispenser to automatically sheer and some way to pick up item drops.

Update: Any conventional item pipes do not even connect to the nests, consider using an apiary or an automated harvester for nests to collect things.

**Comment by Epic428** [comment]
Yeah closing this as it is not a bug. There’s a reason the apiary exists and is designed the way that it is. It’s Bc vanilla hives and tiered hives are designed to not connect to hoppers and other transport methods
