### ISSUE TITLE
Hives are far too common

### ISSUE THREAD

**Issue by dinoman9877** [Team-Resourceful/ResourcefulBees#254]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Hives spawn far too often, even when made to spawn less frequently. (The config file said a _greater_ value would cause less hives to spawn.) But there seemed to be little to no effect in spawn frequency of hives. This not only makes the bees, even supposedly rare ones, obscenely common and easy to find, it also ends up making other mobs less likely to spawn. I can barely even find mooshrooms because bees are dominating the spawns of Mushroom Field biomes now.

**To Reproduce**
1. Go out far enough into the ocean where no land is around. Hives still spawn on the water and you can see just how frequently the game spawns them.

**Expected behavior**

**Screenshots or Crash Logs**
These hives all spawned within render distance of a single block.

![Screenshot (109)](https://user-images.githubusercontent.com/68574459/120191243-b4cef400-c1e7-11eb-849d-1ceeabb54991.png)
![Screenshot (110)](https://user-images.githubusercontent.com/68574459/120191257-b8627b00-c1e7-11eb-8258-38cb05d86117.png)

**please complete the following information:**
 - Forge Version 1.16.5 36.1.0
 - Mod Version 0.6.7.2b

**Additional context**

**Comment by Epic428** [comment]
See #234

**Comment by Epic428** [comment]
Closing as referenced issue has enough information to continue this.
