### ISSUE TITLE
Upgrade item doesn't upgrade Tier 1 to Tier 2

### ISSUE THREAD

**Issue by Jemsterr** [Team-Resourceful/ResourcefulBees#255]
Playing Sky Bees 3.3.3, ResourcefulBees-1.16.5-0.6.5b

Crafting the tier 2 hive upgrade item didn't upgrade the hive to tier 2, it remained a Tier 1 hive but now wild gold corners and a tag that said Tier 2.

![image](https://user-images.githubusercontent.com/17609227/120444288-d76d3280-c3ca-11eb-80e2-9ecf92f52c52.png)

**Comment by Epic428** [comment]
Closing per our discussion in discord. For those following our repository the issue was fixed in the last version of rbees released.
