### ISSUE TITLE
Only 1 bee at a time

### ISSUE THREAD

**Issue by Kiwetin** [Team-Resourceful/ResourcefulBees#256]
Is it normal that I can only import 1 bee at time and only 1 bee goes in the apiary and other bees need to wait for the bee to exit?

**Comment by Epic428** [comment]
Read the tooltip/  fifty shades of bees book/ and see the video tutorial linked in both our discord and the book previously mentioned.

yes. Only one bee of each type can exist inside the block at a time. You can have as many as you want in the structure itself.

**Comment by Kiwetin** [comment]
But I have all oreo bees is it normal?

**Comment by Epic428** [comment]
> yes. **Only one bee of each type can exist inside the block at a time. You can have as many as you want in the structure itself.**

Somebody’s not too good at reading

**Comment by starforcraft** [comment]
> Is it normal that I can only import 1 bee at time and only 1 bee goes in the apiary and other bees need to wait for the bee to exit?

Make a Creative Apiary :)
