### ISSUE TITLE
Cyclic Honey Bucket recipe

### ISSUE THREAD

**Issue by NightUndead** [Team-Resourceful/ResourcefulBees#257]
**Describe the bug**
When crafting a Cyclic Honey Bucket into a Resourceful Honey Bucket, the "original" bucket remains in the crafting grid, now empty.
Essentially, the recipe duplicates buckets

**To Reproduce**
1. Get Cyclic Honey Bucket
2. Craft to Resourceful Bees Honey Bucket
3. Profit, extra bucket gained'

**Expected behavior**
The bucket should be consumed in the crafting recipe.

**please complete the following information:**
 - Forge Version 36.1.3
 - Mod Version 1.16.5-0.6.7.2b

**Comment by Epic428** [comment]
Can you provide a screenshot of the recipe? I’m curious if it is our recipe or a cyclic recipe. There’s been some issues with cyclic fluids not having proper tags to be compatible with other honeys though that should have been fixed already in newer cyclic versions. Just need to confirm where the issue is and if it’s already been fixed or not.

**Comment by NightUndead** [comment]
I believe is it the ResourcefulBees/forge/src/main/resources/data/resourcefulbees/recipes/conversion_cyclic_bucket_to_bucket.json
that is responsible for this, but sure, here's a screenshot of the mouseover:
![image](https://user-images.githubusercontent.com/85498199/121023107-4075f100-c7a3-11eb-8f28-92cfd78d7c42.png)

**Comment by Epic428** [comment]
Ah ok. That recipe was given to me by someone else a long while back. So I’ll have to investigate it and see what needs changing if anything. Thanks for the report! Will prolly be a while before a fix is implemented since we’re rewriting the mod currently

**Comment by Vaerys-Dawn** [comment]
the issue seems to be that vanilla if it finds a container will automatically return the container if it's used in a crafting recipe (i.e. a bucket of water empties rather than also consuming the bucket)
i guess a fix could be adding a second bucket to the recipe?
