### ISSUE TITLE
Upgrade Tokens for Hives not working completely

### ISSUE THREAD

**Issue by Jynx2700** [Team-Resourceful/ResourcefulBees#258]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**
Upgrading Hives with the upgrade tokens as opposed to breaking and crafting into the new Tier causes the block to upgrade stats but the hive itself stays as the original tier and cannot be used for crafting without reupgrading

**To Reproduce**
1. Go to Tier hive...
2. Use upgrade...
3. Block is still original tier but it acts as new tier
4. Have to re-upgrade with crafting if you want to progress

**Expected behavior**
Block should upgrade completely

**Screenshots or Crash Logs**
![Hive Upgrades](https://user-images.githubusercontent.com/12675459/121059057-a3a55a80-c786-11eb-96fe-3f4a1753bfc7.png)

**please complete the following information:**
 - Forge Version 36.1.13
 - Mod Version 1.16.5-0.6.7.2b (Enigmatica 6 pack)

**Additional context**
This does not cause a crash or error from what I can tell, but it is not a graphical problem and is in fact making a Tier XYZ hive act like a more advanced hive despite it not taking the upgrade properly.

**Comment by Epic428** [comment]
Hives have been removed for the next version. This is no longer an issue

**Comment by ryanbarr** [comment]
Hey @Epic428, appreciate your work on resourceful bees.

I'd like to push back on "this is no longer an issue". Deprecation and removal of functionality in one minor or major version doesn't make an issue in another minor or major version go away.

In this case, I'm playing ATM6 and, not wanting to anger my bees, used the upgrades on my hives to Tier 4. After finally getting all I needed for my first Apiary, I put my bees in jars and picked up my hives. To my incredible disappointment, the hours of work I spent to get to this point was lost.

ATM6, and any other mod packs, will be plagued with this issue unless a patch version is added to this minor release or they manually upgrade to the next minor.
