### ISSUE TITLE
Auto gen names for bees/items

### ISSUE THREAD

**Issue by WhitePhant0m** [Team-Resourceful/ResourcefulBees#26]
**Is your feature request related to a problem? Please describe.**
It takes a lot of time to make lang files for the bees.

**Describe the solution you'd like**
Have a line in the json for the bee `"name": "Name Here"` to make auto generated lang file for the bees/items based on what was put in.

**Additional context**
Repeating this process isn't fun
![image](https://user-images.githubusercontent.com/33400200/89594932-e1caa880-d85b-11ea-824c-7030787b0131.png)

**Comment by ThatGravyBoat** [comment]
Implemented!
