### ISSUE TITLE
Missing Loot Tables for Congealer & Bottomless Honey Pot

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#260]
**To Reproduce**
1. Place congealer & Bottomless Honey Pot
2. Break them with a Pickaxe
3. Observe that nothing drops

**Expected behavior**
For the blocks to drop.

**please complete the following information:**
- 1.16.5-36.1.31
- ResourcefulBees-1.16.5-0.6.7.2b

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2397

**Comment by Epic428** [comment]
Oof I feel like this was mentioned in our discord some time ago. Easily remedied for the moment with a data pack but will be sure to include in our rewrite. Thanks for reporting!

**Comment by Vaerys-Dawn** [comment]
fixed in dev sorry about that... forgot that that was something I needed to do.
