### ISSUE TITLE
more Valid Apiary blocks for happy bees!

### ISSUE THREAD

**Issue by Eluinees** [Team-Resourceful/ResourcefulBees#261]
**Is your feature request related to a problem? Please describe.**
Oh, I was just wondering if more blocks could be added to the Valid Apiary tag. Specially for the "Aurora Block" from Twilight Forest

**Describe the solution you'd like**
More Valid Apiary blocks for gorgeous apiary designs!

**Describe alternatives you've considered**
Using cobblestone but it just wont do the trick, also i think it makes my bees depressed :(

**Additional context**

**Comment by Epic428** [comment]
Using a vanilla data pack you most certainly can add to it.

https://minecraft.fandom.com/wiki/Tag
https://minecraft.fandom.com/wiki/Data_Pack

These are relevant links to help with making a data pack and modifying tags.

And this is a link showing the default versions of both the item tag and block tag variants of the valid_apiary tag
https://wiki.resourcefulbees.com/en/1.16.3/extra_stuff/valid_apiary_tag/

The item tag version is for searching in jei and the block tag is what is actually used for the structure validation. I’m looking into alternative methods that would allow for more blocks to be used without the need for the tags.

**Comment by Epic428** [comment]
Closing due provided answer being sufficient
