### ISSUE TITLE
Beepedia crash with Optifine

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/ResourcefulBees#262]
**Describe the bug**
 While using the Beepedia to access potential Children of the Zombee, attempting to turn to page 2/3 causes a client crash.
This bug is most likely only present with Optifine.

**To Reproduce**
1. Download Enigmatica 6, add Optifine, start game
2. Open Beepedia, go to the Zombee
3. Go to page 3

**Expected behavior**
I expected no crash... sorta. Optifine is unreliable 😄 

**Screenshots or Crash Logs**
 https://pastebin.com/E0DPerC5

**please complete the following information:**
 - 1.16.5-36.1.31
 - ResourcefulBees-1.16.5-0.6.7.2b

**Additional context**
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2440

**Comment by Epic428** [comment]
hmm we can look into it to see if there's something about the beepedia that is incorrect and would cause the issue, but the overall stance and philosophy of the mod and team is that we don't support optifine. none of us use optifine and it's extremely difficult to provide explicit support for a mod that doesn't publish its source code and generally has issues regardless. If any issue is reproducible without optifine then it is definitely something that **needs** to be fixed, but not all issues that occur with optifine *will* be fixed.

**Comment by NielsPilgaard** [comment]
Here's some more context for you: https://github.com/NillerMedDild/Enigmatica6/issues/2440#issuecomment-865153819
It appears to happen without Optifine.

**Comment by Vaerys-Dawn** [comment]
need more information, there's a chance this is due to an invalid child entity and is likely a pack issue.

closing, if this is an issue with the main mod please reopen
