### ISSUE TITLE
[Bug]: Apiary not working properly

### ISSUE THREAD

**Issue by CubicalDisaster** [Team-Resourceful/ResourcefulBees#265]
### Bug Description

After importing bees into the apiary they go out to there designated blocks but once they deposit there honey combs they never return to the apiary. So you have to catch them with jars and import them again. I have only made it to the second tier apiary and both first and second tier apiaries don't function properly. 

### Expected Behavior

From what other mod packs I've played the bees would return to the apiary after they got done pollinating the blocs  from resourceful bees mod.

### Version

1.0.13

### Mod Loader Version

17

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Please fill out the template correctly. What mod version? What pack? What forge version? “17” means nothing to me

**Comment by Epic428** [comment]
I will reopen this when the proper data is provided

**Comment by CubicalDisaster** [comment]
I am sorry I am running the newest version of Sky Farm and I have installed the newest version of Minecraft installed.  I am new this and I really like the mod and I don't report things because I don't understand how to do it.  I thought it might of been implemented my the modpack  developer whom I thought this issue was going to.  You don''t have to worry about it I will not use this part of the modpack but it is one of the more enjoyable mods that I like playing with. Thanks and sorry for the frustration.

**Comment by Epic428** [comment]
No worries. It’s just really difficult to debug an issue without knowing which version of our mod it is. But now knowing the modpack it makes it easier to debug. That said however. Have you confirmed you are using the correct flowers for the bees and have those flowers placed inside the apiary? Not all bees use the same flowers.

**Comment by CubicalDisaster** [comment]
I'm using the right flowers. The bees produce the honey combs like it's supposed to. The bees just don't go back into the apiary
after dropping off the combs..

**Comment by ThatGravyBoat** [comment]
send a picture of hte apiary structure

**Comment by CubicalDisaster** [comment]
![2021-07-04_10 07 27](https://user-images.githubusercontent.com/71413718/124390247-42eb3e00-dcb0-11eb-852f-af45337b133a.png)

**Comment by Epic428** [comment]
Can I see a better screenshot of the inside? Not the interface. Also a screenshot of the flowers needed for the bees as shown in jei and/or beepedia would be super helpful too. I’m at work so I can’t download the pack and verify this info.

**Comment by CubicalDisaster** [comment]
![2021-07-04_10 21 40](https://user-images.githubusercontent.com/71413718/124390618-0c162780-dcb2-11eb-8f97-4b68ca980ef1.png)
![2021-07-04_10 27 47](https://user-images.githubusercontent.com/71413718/124390734-8ba3f680-dcb2-11eb-9665-15f2a5ad66a0.png)
![2021-07-04_10 28 39](https://user-images.githubusercontent.com/71413718/124390768-a5453e00-dcb2-11eb-8777-e23ba06225ba.png)
I took that last photo to show that the structure was valid but I hope these pics are what you are asking for.

**Comment by TemperedFool** [comment]
Iirc you don't want the apiary block at the floor like that, as it can cause the bees to have issues returning to the apiary block.

**Comment by CubicalDisaster** [comment]
Okay I'll try raising them. It said they were valid apiary blocks so I thought it was by design that they would work that way. I tried raising them and still the same problem.
![2021-07-04_10 45 49](https://user-images.githubusercontent.com/71413718/124391191-0e2db580-dcb5-11eb-9252-5736dee374f7.png)

**Comment by Epic428** [comment]
Can you try breaking the apiary and replacing it? Something must be bugged in your world. Based on your images everything appears to be perfectly fine. The apiary is one of the most thoroughly tested pieces of the mod and as such issues like this shouldn’t be present.

edit: if that doesn’t work I’m not really sure what else to try outside of me downloading the pack and testing or getting a zip of your world and testing myself.

**Comment by CubicalDisaster** [comment]
I've already broken it and tried replacing it. I also cheated in a tier 4 apiary to see if it would work but it had the same problem.
I'll try starting a new world and testing it out. I thought the person who put together the mod pack might of shut off some features but I wasn't sure. Thanks for the help though.

**Comment by Epic428** [comment]
No worries. If you find a solution let us know. I’ll try and test it tonight and see if I can reproduce the issue.

**Comment by CubicalDisaster** [comment]
I deleted and reinstalled the the pack with the same issues.  The pack had a stages and no stages options in world generation section I tried both of them thinking it might of been locked behind a stage but that wasn't the case.

**Comment by Epic428** [comment]
@CubicalDisaster do me a favor. We just discovered a mod incompatibility issue that was fixed last night while helping another person with a similar issue. Update sodium reforged to version 2.9+ that was released in the past 12 hours and tell me if it solves your problem

**Comment by CubicalDisaster** [comment]
It wasn't working at first but I broke the apiary and replaced it. Everything seems okay from what I can tell so far.

**Comment by Epic428** [comment]
this is after updating the sodium mod correct?

**Comment by CubicalDisaster** [comment]
Yes that is correct I had to delete the old file because it didn't replace the old one. I just got back to the house so I just tested it out as soon as I seen your response. From what I can tell it's working properly.

**Comment by Epic428** [comment]
excellent. from what I understand there was a bug fix to disable lithium or something as it affected entity AI. at least that's what the changelogs mention. SO I'm glad we figured out the solution. now we just need to notify the SkyFarm dev so they can update and I don't get inundated with bug reports

**Comment by Epic428** [comment]
closing as resolved
