### ISSUE TITLE
TOP Integration doesn't work when using Dedicated Server

### ISSUE THREAD

**Issue by Epic428** [Team-Resourceful/ResourcefulBees#3]
Need to investigate and figure out why TOP doesn't work properly with dedicated servers.

**Comment by Epic428** [comment]
Note to self: change how TOP compat gets loaded. Likely not working due to loading on client side only. Needs to be loaded during common setup.

**Comment by ThatGravyBoat** [comment]
Fixed in commit `6f11701`
