### ISSUE TITLE
Bees Crash The Game When Imported Into Apiary

### ISSUE THREAD

**Issue by Zaratuir** [Team-Resourceful/ResourcefulBees#30]
**Describe the bug**
When the Wither Bee is added to the Apiary, the game crashes on rendering the ValidatedApiaryScreen.

**To Reproduce**
1. Create an apiary (I used t4 apiary, 1 apiary_storage, and oak planks. Interior of the Apiary was dirt on top of bottom planks and flowers on top of dirt.
2. Use the bee spawner to spawn bees until you get a wither bee.
3. Capture the Wither Bee in an Apiary Jar
4. Import the Wither Bee into the Apiary
5. See the game crash.

**Expected behavior**
Wither Bee is added to apiary inventory as locked bee

**Crash Report:**
[crash-2020-08-18_00.33.26-client.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/5088630/crash-2020-08-18_00.33.26-client.txt)

**please complete the following information:**
 - Forge Version 1.16.1 - 32.0.108
 - Mod Version Resourceful Bees 1.16.1-0.3.7a

**Comment by Epic428** [comment]
Bug is fixed in the latest mod update. 0.3.8a

**Comment by Epic428** [comment]
If you’re on ATM6 modpack you can edit the bees json to include a `primaryColor` that is a hex value of 0xffffff and it will fix it
