### ISSUE TITLE
Netherite Bee Dies from Wither Rose

### ISSUE THREAD

**Issue by BJR1984** [Team-Resourceful/ResourcefulBees#32]
Netherite bee can't pollinate wither rose without getting wither effect. then it dies.

**Comment by Epic428** [comment]
That’s an easy fix. I’ll fix it for the default shipped options. But you can go into the bee jsons and set the netherite bee to ~~`”isWither”: true`~~

**Comment by Epic428** [comment]
Sorry `“witherBee”: true`

**Comment by Selbram** [comment]
In resourcefulbees-1.16.3-0.5.5b.jar this is still an issue. Would changing the 
`"traits": ["nether"],`
to 
`"traits": ["nether", "wither"]`
correct this?

**Comment by ThatGravyBoat** [comment]
Yes changing it to that would be correct
