### ISSUE TITLE
Multiblock centrifuge inputs accept bottles

### ISSUE THREAD

**Issue by ClaymooreEOC** [Team-Resourceful/ResourcefulBees#33]
**Describe the bug**
When using the multiblock centrifuge and feeding it bottles as well as honeycombs the two first input slots for honeycombs fill up with glass bottles.

**To Reproduce**
I am in ATM6 and using Refined Storage to fill the centrifuge using an exporter configured to move glass bottles and honeycomb blocks.

**Expected behavior**
Expected behavior would be that bottles only go into the bottle slot on the left of the UI

**Screenshots**
https://imgur.com/a/asyEess

**please complete the following information:**
 - Forge Version :I do not know how to find this information :(
 - Mod Version :resourcefulbees-1.16.1-0.3.8a

**Additional context**

**Comment by Epic428** [comment]
Fixed in dev. Will be in next release.
