### ISSUE TITLE
Comb block recipes don't respect mainInputCount

### ISSUE THREAD

**Issue by rowanthemodder** [Team-Resourceful/ResourcefulBees#35]
**Describe the bug**
Auto generated comb *block* recipes don't respect mainInputCount.

**To Reproduce**
Check JEI or put a comb block in the multiblock centrifuge.

**Expected behavior**
64 Comb blocks should equal 9 netherite in my example image.

**Screenshots**
(Additionally tested by putting comb block in centrifuge multiblock)
![Bug1](https://user-images.githubusercontent.com/46363164/92162732-7c7cbf80-ede7-11ea-8e8c-09f7385b1c0b.PNG)

![bug](https://user-images.githubusercontent.com/46363164/92162147-8ce06a80-ede6-11ea-9a38-4a0b88c46d93.PNG)

 - Forge Version 32.0.108
 - Mod Version 1.0.3.9a

**Comment by ThatGravyBoat** [comment]
Fixed in dev.
