### ISSUE TITLE
Comb block output change suggestion

### ISSUE THREAD

**Issue by rowanthemodder** [Team-Resourceful/ResourcefulBees#36]
**Is your feature request related to a problem? Please describe.**
Currently the comb block recipes output in large chunks rather than 9 rolls of one comb recipe, which makes especially rare outputs even rarer than using combs.

**Describe the solution you'd like**
Comb block recipes should output 9 separate rolls of their outputs rather than 1 roll for 9 of the outputs.
I would like this more as it allows for especially rare outputs to be rolled in a balanced way.

**Describe alternatives you've considered**
Currently comb blocks roll for 9 of an output, which is alright, just not what I expected the behavior to be.

**Comment by ThatGravyBoat** [comment]
This would be too overly complicated and complex for the simple recipe system that it uses this would make it so that devs would have to input a bunch of extra uneeded data to add a custom recipe in a data pack, we may reconsider it down the line but not right now.
