### ISSUE TITLE
Shift-Clicking Honeycomb into Third Spot in Multiblock Centrifuge

### ISSUE THREAD

**Issue by Tizby101** [Team-Resourceful/ResourcefulBees#38]
Description:
When using the GUI for the Centrifuge Multi-block, shift-clicking honeycombs and honeycomb blocks are not jumping into the third (right most) location.  Dragging honeycombs and honeycomb blocks into the location does allow the position to work.  

Version Information: 
 - Forge Version 31.2.36
 - ATM 5 - Mod Version 2.21
 - Resourceful Bees Version 1.15.2-0.3.8a

**Comment by Epic428** [comment]
fixed in 1.16.3 will back port to older versions when doing backports.
