### ISSUE TITLE
Honeycomb ID and Tags are the same across all Honeycombs

### ISSUE THREAD

**Issue by Tizby101** [Team-Resourceful/ResourcefulBees#39]
All Honeycombs ID and Tags are the same.  This causes other mods to consider different honeycombs to be the same.  Therefore, when auto sorting or using a item movement system, they can't move different types to different locations.  Please add different tags and different IDs to each honeycomb (possibly the honeycomb blocks) to fix issues.  

 - Forge Version 31.2.36
 - ATM 5 - Mod Version 2.21
 - Resourceful Bees Version 1.15.2-0.3.8a

**Comment by ThatGravyBoat** [comment]
This will not be done in 1.15 or 1.16.1 this will be a thing in 1.16.3 and will not be back ported due to it being a major change.

**Comment by Epic428** [comment]
I realize this is closed. But just for clarification. The NBT data for items/blocks/entities *are* different. If a mod allows filtering on that data then it will work. *Technically* the proper way to do registration according to forge is to register a static number of objects and variations should be done using NBT. With 1.16.3 we’ve switched to a more iterative/dynamic registration method similar to how Mystical Agriculture and JAOPCA do registrations. This allows for elimination of the NBT data and each item/block/entity to have a separate ID. The issue with back porting this Is that there no way to do so without requiring every person upgrading to make new worlds. Every bee/comb/block in existing worlds would cease to exist.

**Comment by ThatGravyBoat** [comment]
An addition to this is that those mods that cant distinguish between different honeycombs are doing something wrong if they cant sort between 2 items that have different nbt this would mean they wouldnt be able to sort swords with different durability and so on.

**Comment by Tizby101** [comment]
Thank you for the clarification, it is very helpful. I understand the
situation and now see going backwards is not an option. Reaching out with
more information is above and beyond in my book. Thank you very much.

Sincerely,
Dale Rogers
