### ISSUE TITLE
Crash with centrifuge

### ISSUE THREAD

**Issue by MelanX** [Team-Resourceful/ResourcefulBees#44]
**Describe the bug**
Game crashes if centrifuge output is too full.

**To Reproduce**
1. Build multiblock centrifuge
2. Add a lot of coal comb blocks
3. Wait a few seconds
4. Crash

**Expected behavior**
Machine stops working if output is too full.

**please complete the following information:**
 - Forge Version 1.16.3-34.1.0
 - Mod Version 1.16.3-0.5.1a

**Additional context**
Crash log: https://pastebin.com/EEygvbxJ

**Comment by Epic428** [comment]
That’s a simple fix. I’ll have it fixed tonight and in the next version which should release tomorrow on curse. Thanks for reporting!

**Comment by MelanX** [comment]
There is a PR for that. Maybe that's good?

**Comment by Epic428** [comment]
I’m at work atm so I’ll review it tonight and merge it if it’s good unless @ThatGravyboat can get to it before me
