### ISSUE TITLE
Bee name and colour problem

### ISSUE THREAD

**Issue by xXmilchzombieXx** [Team-Resourceful/ResourcefulBees#47]
![2020-10-08_13 09 13](https://user-images.githubusercontent.com/72553828/95460591-72fdee80-0975-11eb-8cd9-31ee4c8bded6.png)

`{
  "color": "#5dbcd2",
  "flower": "minecraft:nether_wart",
  "baseBlock": "minecraft:netherrack",
  "mutationBlock": "minecraft:magma_block",
  "mainOutput": "minecraft:blaze_rod",
  "spawnInWorld": true,
  "biomeList": "tag:NETHER",
  "maxTimeInHive": 600,
  "certusBee": true
}`
 
My problem is that the name of my bee and the colour is not correctly displayed and i do not know how i can fix that because i have only used the example code and only changed the name of the bee.

**Comment by Epic428** [comment]
There’s a few issues with your json file. `color` is not correct. `biomeList` is not correct.

you should be using `primaryColor` `secondaryColor` if you want to change it.

For biomes there’s `biomeWhitelist` and `biomeBlacklist`

Mutations _should_ be `mutationInput` and `mutationOutput` I know it’s that way for 1.16.1 and 1.16.3 90% certain that’s how I have it setup for 1.15.2 but would need to double check it.

In order for the name to display properly you need to create a Lang file and put it in the proper directory. We have a wiki doc that shows how to do it.

**Comment by Epic428** [comment]
https://github.com/Resourceful-Bees/ResourcefulBees/blob/1.15.2/src/main/java/com/dungeonderps/resourcefulbees/data/BeeData.java


https://github.com/Resourceful-Bees/ResourcefulBees/tree/master/src/main/java/com/resourcefulbees/resourcefulbees/api/beedata

First link covers 1.15.2 and 1.16.1. Second covers 1.16.3 as there was a format change to the json. Any value not marked as `transient` is a value that can be customized. I HIGHLY recommend looking at the default generated bees as an example of how to format the json correctly. But until the jsons are established properly I can’t provide any further assistance.

**Comment by xXmilchzombieXx** [comment]
Trank you for your fast reaction and thx for the help.

Am Freitag, 9. Oktober 2020 schrieb Epic428 <notifications@github.com>:

**Comment by xXmilchzombieXx** [comment]
I have only one problem left all i change in the already existing bees will be changed back after i have started my minecraft but i don't want this to happen because I want to make some little changes.

**Comment by ThatGravyBoat** [comment]
You need to set the Generate Default Bees config option to false if you want to edit default bees

**Comment by ThatGravyBoat** [comment]
lol im so used to closing issues when commenting

**Comment by xXmilchzombieXx** [comment]
Okay thx for your help and no problem the problem is solved also :D


Am Fr., 9. Okt. 2020 um 16:32 Uhr schrieb ThatGravyBoat <
notifications@github.com>:

**Comment by xXmilchzombieXx** [comment]
How I let more parents of bees breed one be so for example i have three bees and all three could be cross bred so one other be could be createt?

**Comment by Epic428** [comment]
We only allow for two parents of a bee. Same as vanilla. You’d have to do cross breeding by having an intermediary bee. Also vanilla breeding logic doesn’t support a 3rd lover in the mix. I’m not 100% sure if I could roll my own either.

**Comment by xXmilchzombieXx** [comment]
No not a third. I mean that for example I have A, B, C Bees and want that Bee E can be bred with A+B, A+C and B+C but i do not know how the expression should look like and also I have another problem that my bees does not take my breed weight serious, because one bees should have a breed weight of 8% but ingame she tells me that she has 50% with this code `"breedWeight": 0.5`.

**Comment by Epic428** [comment]
Ahh currently a bee does not support having more than one pair of parents. However I will be working on making it so that’s a possibility

**Comment by Epic428** [comment]
Breed weights are calculated against all bees that the same two parents can make. So for example you have bee X can be made by bees A and B and you have bee Y can also be made by bee A and B and same for Z. If X was 20 weight and Y and Z each 40 weight. Then X would have a 20% chance of being bred

**Comment by xXmilchzombieXx** [comment]
Okay thx :D

Am So., 11. Okt. 2020 um 12:44 Uhr schrieb Epic428 <notifications@github.com

**Comment by ThatGravyBoat** [comment]
Closing issue, if you have any further questions you can join our [discord](https://discord.gg/mWcDarK).
