### ISSUE TITLE
Can we get a Wiki that explains the Mod??

### ISSUE THREAD

**Issue by smallerYeet** [Team-Resourceful/ResourcefulBees#49]
I just don't know how to anything with this Mod. I can't find any guides that tells me how to breed or get specific bees and i am completely lost.

With a Proper Wiki or Guide (maybe even In game guide using Guide API's) players can progress much better with this mod.

A Video or a Wiki even a Guidebook is all I need.

Is that possible or even in work, or am I just too stupid to play this mod?

**Comment by WhitePhant0m** [comment]
They are already working on a guide

**Comment by smallerYeet** [comment]
That's nice! 
Is there a Discord or something? Would help finding volunteers and helping people like me

**Comment by WhitePhant0m** [comment]
There is a link on the curse forge page but here https://discord.gg/rteh4mh

**Comment by smallerYeet** [comment]
Thanks very much!
