### ISSUE TITLE
Pre-created bees stats arent saving 

### ISSUE THREAD

**Issue by MRGWolf** [Team-Resourceful/ResourcefulBees#5]
Hello! Just found an issue where if the original 14 bees are tweaked or adjusted the changes do not save and get reset after loading up minecraft to the original state. I'm trying to create a tier style breeding system using your bees and dont want gold, diamond, etc to spawn freely around the world but to be bred instead.

**Comment by Epic428** [comment]
There’s a Config option for “generate default bees” if you turn that off the bees will stay and you can modify them.

I should probably add some clarifying text to the Config option indicating its use.

**Comment by Epic428** [comment]
Currently, I do a check for the flag and if it’s true then I copy the files over from the jar to the Config directory and overwrite the existing bees

**Comment by MRGWolf** [comment]
Thank you for the reply! def helped a lot. For each individual bee do we need to write a separate lang file? Or how does one setup multiple renames within a single lang file?

**Comment by Epic428** [comment]
No. One Lang file would cover all bees you add. You just have to add a line for each entry type like honeycomb and honeycomb block.

**Comment by ThatGravyBoat** [comment]
Issue resolved all documentation and wikis are updated to better clarify this.
