### ISSUE TITLE
Multiblock Centrifuge

### ISSUE THREAD

**Issue by NudeShrimp** [Team-Resourceful/ResourcefulBees#50]
I am not sure if this is intended but glass bottles get filled into every slot of the centrifuge not just the left one where they are supposed to be.

**Comment by Epic428** [comment]
Which version of the mod?

**Comment by NudeShrimp** [comment]
This should be it resourcefulbees-1.16.1-0.3.8a, at least I think so

**Comment by Epic428** [comment]
Ah ok. I think that bug got fixed after that version which explains why

**Comment by NudeShrimp** [comment]
Oh I see, thanks for the quick response
