### ISSUE TITLE
Add the 1.16.3 json format to the wiki

### ISSUE THREAD

**Issue by aprilthepink** [Team-Resourceful/ResourcefulBees#53]
**Is your feature request related to a problem? Please describe.**
Its very frustrating that the new json style isn't in the wiki

**Describe the solution you'd like**
I want that the new json format is also in the wiki.. pls

**Describe alternatives you've considered**
Using the json used in the default bees. its aids

**Comment by Epic428** [comment]
Working on it. Just need the time to devote to it. In our discord we have pinned a template showing all possible options with the exception of a few newly added ones. I’m hoping this weekend I can take some time to really update the documentation

**Comment by Epic428** [comment]
here is a link to the new wiki: https://resourceful-bees.readthedocs.io/en/1.16.3/

It's not complete but has about 95% of the info you need to get started I will finish it over the next several days
