### ISSUE TITLE
Coal bee issues

### ISSUE THREAD

**Issue by ElvenWhiskers** [Team-Resourceful/ResourcefulBees#54]
Problem: Spent hours looking, never found coal bee, cheated spawn egg in. Coal bee never grew.
-used on multiplayer server
-only seem to have an issue with coal bee, haven't found a single other issue.

**Comment by Epic428** [comment]
think that's my fault. changed its biomeWhitelist to tag:mountain from the previous tag:overworld.

That is assuming this is for 1.16.3

However that brings me to another point: in 1.16.3 there's an additional info tab for every bee which lists what biomes the bee can spawn in if the bee is spawnable.

**Comment by ElvenWhiskers** [comment]
It says its spawnable is quite a lot of biomes, ive searched them all. None of the bee's ive spawned in grow still. Actively playing it now. It is 1.16.3, I shoulda mentioned that, my bad :) Love the mod! <3

**Comment by Epic428** [comment]
Is this a custom mod pack or ATM6?

The bees spawn naturally like passive mobs and as such they shouldn't be terribly difficult to find unless the spawn weight for the bee was configured to be very low. But I highly doubt a coal bee would have been configured in such a way.

Also not exactly sure what you mean by:
>None of the bee's ive spawned in grow still

**Comment by ElvenWhiskers** [comment]
I put together a 1.16.3 pack for my husband and I. I gave myself 3 coal bee spawn eggs because i couldnt find a single coal bee after 3 hours of actively searching (Im persistent). The three spawned coal bee's (from the spawn eggs) haven't grown in the last hour of play time(real life hour). I've stood by them waiting, making sure they're chunk loaded. They aren't spawning honey or honey combs because they're babies. You cant feed flower to speed up growth, and the One probe isn't showing a grow timer.

**Comment by Epic428** [comment]
can you send me the json file for the coal bee as it appears in the config folder for our mod?

Also coal bees by default were set to have a size modifier of .5 meaning they are half the size of a normal bee.

Our mod allows for pack developers to fully customize bees, so our default bees are really just a small representation of what you can do with the mod itself as a developer. They're really intended to be overridden and modified to the developers liking

**Comment by ElvenWhiskers** [comment]
Oh! I was not at all aware they were half the size. They're working just fine. I just didnt see their resources were getting trashed because my of automated system! I didnt think to keep looking for combs because the bees weren't growing. So sorry about that.

**Comment by Epic428** [comment]
lol no worries! I'll mark this as resolved and close. if you have any other issues or questions let us know either here or in our discord :)
