### ISSUE TITLE
oreo bee output

### ISSUE THREAD

**Issue by Shockax** [Team-Resourceful/ResourcefulBees#58]
Right now the Oreo bee is producing:

Apiary T1: 8 Epic Oreo
Apiary T2: 16 Epic Oreo
Apiary T3: 4 Epic Oreo
Apiary T4: 8 Epic Oreo

i think some numbers are mixed up because it should not produce less in a better apiary maybe change it to:

Apiary T1: 2 Epic Oreo
Apiary T2: 4 Epic Oreo
Apiary T3: 8 Epic Oreo
Apiary T4: 16 Epic Oreo

**Comment by Epic428** [comment]
Are you on the latest version of the mod shockax? I changed the Oreo bee so it only outputs 1,2,3,4 in apiary.

**Comment by Shockax** [comment]
Yeah currently on 0.5.4b

[https://i.imgur.com/L31KFfV.png](url)

**Comment by Epic428** [comment]
This was fixed in 0.5.5b closing :)
