### ISSUE TITLE
Fifty Shades of Bees not craftable

### ISSUE THREAD

**Issue by Shockax** [Team-Resourceful/ResourcefulBees#59]
Fifty Shades of Bees is not craftable. It is not showing a crafting recipe in JEI and if you use the "old" crafting recipe (Screenshot below) you get a "item.patchouli.guide_book" that cant do anything. 

[https://i.imgur.com/M9b8H3O.png](url)

**please complete the following information:**
 - Forge Version [e.g. '1.16.3 - 34.1.25']
 - Mod Version [e.g. '0.5.4b']

**Comment by aprilthepink** [comment]
do you have any other mods installed?

**Comment by Epic428** [comment]
Recipe is bad. Fixed in dev. Will push to curse tonight. Can cheat in for now
