### ISSUE TITLE
Shears not working on Tiered beehives

### ISSUE THREAD

**Issue by AggressivePear** [Team-Resourceful/ResourcefulBees#63]
**Describe the bug**
I attempted to use shears on a dripping tier 1 beehive. I can shear normal beehives with the shears, but not any ones from the mod.

**To Reproduce**
1. Place Tier 1 beehive.
2. Have Oreo and normal bees fill the hive to dripping point.
3. Right click on beehive with shears.
4. Get no combs or oreos.

**Expected behavior**
I should get either normal combs or oreos.

**please complete the following information:**
 - Forge Version 34.1.25
 - Mod Version 0.5.4b

**Additional context**
I have not yet been able to recreate the problem in other worlds. It persists on my main world through reloaods.

**Comment by Epic428** [comment]
If you’re playing on ATM6 I believe they changed the Config allowShears to false due to an issue between us and apotheosis. I fixed some things in the latest version so they should be able to re-enable it. Double check if that value is true or false.

**Comment by AggressivePear** [comment]
Thank you for the info, though I am having trouble finding the correct config with that value. What is the name of the config file?

**Comment by Epic428** [comment]
In the configs folder of your modpack instance is a folder called resourcefulbees. In that folder is a common.toml. You’ll find the allowShears option

**Comment by AggressivePear** [comment]
It was set to false. sorry to waste your time.

**Comment by Epic428** [comment]
You’re okay! 🙂
