### ISSUE TITLE
Beehive entry/exit

### ISSUE THREAD

**Issue by AggressivePear** [Team-Resourceful/ResourcefulBees#64]
**Is your feature request related to a problem? Please describe.**
Yes. I get annoyed when the hives do not allow bees to exit from any side. Some hives only allow entry or exit from one side and get my decorations/designs ruined to try and accommodate that.

**Describe the solution you'd like**
Allow bees to enter or exit any side. Or make the side facing you when placed be the entry and exit point, instead of the side facing away from you be the exit point.

**Describe alternatives you've considered**
I have thought of having floating beehives or hives on a stick, but they usually look ugly like that.

**Additional context**
I once had a set of tier 3 beehives all full of bees but not producing anything because they could not leave.

**Comment by Epic428** [comment]
Hold shift when placing a beehive to change the direction it is oriented when placed. Bees will ALWAYS exit from the face of the hive including vanilla hives. That would be the side of the hive where the honey shows when it's hit max honey level. Bees can enter any side of the hive always

**Comment by AggressivePear** [comment]
Ah, did not know that. Is it possible to change the exit to any side in the mod?

**Comment by Epic428** [comment]
It doesn't make sense for them to exit any side of the hive. I *could* change it but I won't. It would also break the apiary if I did bc of how it is designed.
