### ISSUE TITLE
Netherite Bee Dies from Wither Rose (yes this is a repeat)

### ISSUE THREAD

**Issue by Selbram** [Team-Resourceful/ResourcefulBees#65]
The netherite bee still gets damaged from the wither rose and cannot pollinate and produce combs.

**please complete the following information:**
 - Forge Version forge-34.1.25
 - Mod Version resourcefulbees-1.16.3-0.5.5b.jar

**Additional context**
Would modifiying the Netherite.json to have:
'"traits": ["nether", "wither"],'
instead of:
'"traits": ["nether"],'
correct this issue?

**Comment by ThatGravyBoat** [comment]
Yes as I said here changing it would work. https://github.com/Resourceful-Bees/ResourcefulBees/issues/32#issuecomment-718006345
