### ISSUE TITLE
[1.16.3] Crash when Dungeons Gear mod is present

### ISSUE THREAD

**Issue by bessiq** [Team-Resourceful/ResourcefulBees#67]
Forge: 34.1.25
Resourceful Bees 1.16.3-0.5.5b (and 2 previous versions)
dungeons_gear-1.16.2+1.16.3-2.0.12.jar (and several previous versions)
logs: https://gist.github.com/bessiq/4530d87371be852324d74493fbd9d28b

**Describe the bug**
Hi there! Forge is crashing during early loading when Resourceful Bees and Dungeons Gear are installed together. The Dungeons Gear dev provided some feedback - please reference the open issue on their Github here: https://github.com/Thelnfamous1/Dungeons-Gear/issues/7

Also, the dev for Dungeons Gear wanted me to link you the relevant part of their code: https://github.com/Thelnfamous1/Dungeons-Gear/blob/master/src/main/java/com/infamous/dungeons_gear/mixin/HurtByTargetGoalMixin.java

**To Reproduce**
1. Install both mods and start game instance

**Additional context**
Bees go bzzzzzt 🐝 🤷 

Thanks!

**Comment by Thelnfamous1** [comment]
The simplest fix for this is to remove the AT for alertOthers in HurtByTargetGoal and in your BeeAngerGoal class simply override it as normal, as you don't need to AT a protected method to override it.

**Comment by Epic428** [comment]
I’ll fix it up today. Thanks for the info!

**Comment by WenXin20** [comment]
Hello, I had the same crash, but for 1.15.2 reported at Thelnfamous1/Dungeons-Gear#13. Will this be fixed for 1.15.2 as well?

**Comment by Epic428** [comment]
I have it fixed in dev for 1.16.3 just haven't done a curse build yet. as for 1.15.2 I'm not 100% sure. That version is so far behind in terms of bug fixes/updates and the newer version is of higher priority that it's just a matter of when I can backport. I recommend when possible to use the newer version esp since *most* mods have made it to the newer versions

**Comment by WenXin20** [comment]
Alright thanks. I tried moving to 1.16 recently, but Optifine doesn't work very well with mods yet, and minecraft on my laptop is slow without it, unfortunately.

**Comment by Epic428** [comment]
Have you tried optiforge and optifine combined? I know a lot of people in ATM who use them without issue. There are of course a few who still have issues depending on the mod.

**Comment by WenXin20** [comment]
Yeah I did, but still got a crash. But I'll probably try again soon since 1.16.4 has released.

**Comment by Vaerys-Dawn** [comment]
fixed, oreo please close issues ;-;
