### ISSUE TITLE
Chunk Loading not work

### ISSUE THREAD

**Issue by G4mer0815** [Team-Resourceful/ResourcefulBees#69]
FTB Chunk Loading does not work with the mod. 
And Vanilla / forceload doesn't work either.

Resourceful Bees Version 1.16.3-05-5b
Ftb Chunks Version 1.16.3-2.0.42
Forge Version 34.1.25

Pls help, sry bad english

**Comment by Epic428** [comment]
What exactly doesn’t work?

**Comment by Epic428** [comment]
Is this still an issue??

**Comment by ViRb3** [comment]
I used FTB chunk loading just fine a few weeks ago, with both Apiaries and Tiered Beehives. I don't know if a recent regression in this mod or FTB didn't change that though.
