### ISSUE TITLE
npe with 1.15.2-0.2.0

### ISSUE THREAD

**Issue by kreezxil** [Team-Resourceful/ResourcefulBees#7]
https://paste.ee/p/1tP66

using forge 31.2.4

**Comment by ThatGravyBoat** [comment]
Did you change any of the default bees or add any new ones? if so you can give us the jsons for said bees.

**Comment by Epic428** [comment]
Yeah we def need more information to be able to resolve this. What happened leading up to the crash? Was it during world load, run time, game load? What mods are installed? Were bees added and removed? 

The way the data is obtained and used for color handling shouldn’t allow for NPE but it’s possible I have a method call that didn’t get updated.

**Comment by kreezxil** [comment]
brand new pack build. initial run on the client. I'm being told that it is
caused by the forge class renames that happened in 31.2.0 and 31.2.4, and
this is using 31.2.4

**Comment by ThatGravyBoat** [comment]
Our compiled release build on curse was for 31.2.0 and we tested it on 31.2.4 and its all fine in dev and in jar.

**Comment by kreezxil** [comment]
thanks for double checking, I double checked too, and I thought I was
right, but I was wrong. One of the other mods I selected jacked with the
forge registries. You can close this ticket.

**Comment by Epic428** [comment]
Sounds good. Thanks for the report :)
