### ISSUE TITLE
Mod Specific Bees without building your own custom bees

### ISSUE THREAD

**Issue by b52src** [Team-Resourceful/ResourcefulBees#70]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
pre built Mod integration as an alternative to creating your own custom bees, if Immersive engineering is installed copper bees or, manna steel bees with Botania much like Magic Bees did in 1.12 and earlier . Mod integration could then bee disabled via module(IE, Botania, Thermal, etc.) via config. 

**Describe alternatives you've considered**
alternatively a custom bee modules could bee kept as a library to grab prebuilt bees for specific mods.
or addon mod much like Magic bees is for Forestry.

**Comment by Epic428** [comment]
I’ve been going back and forth on how I want to best handle this. Perhaps having a selection of bees available for download would be a good option? I thought about having configurable modules in the configs but the main issue is if multiple mods have the same ores then only one of the bees would get registered and it would be a roulette as to which one it is. I also don’t want to have a complex module system on top of an already complex customization system. But I think if we have predefined options that can be downloaded and popped in, then edited, if desired, that would be the better option overall.

**Comment by b52src** [comment]
yea think a nice bee library may bee the best option over all., prebuild a few for some of the most popular mods then people can work from there to customize if they like and perhaps allow people to submit their own as well.

if you go modules and have multiple mods with the same ingots like copper for example not sure if you could essentially give the bee a priority so that if IE and Thermal are both installed make only the thermal copper bee exist. then if someone wants to go crazy with custom bees they can disable the modules and build their own custom bees.

**Comment by tomtenberge** [comment]
isn't there a way to detect wich (forge) ores and things are present and base the available bees on that?

**Comment by ThatGravyBoat** [comment]
We wont be adding premade custom bees in the mod itself but if you join the discord there is a channel where people post their custom bees for specific mods, possibly later down the line well make a site where we can have zips with premade bees.
