### ISSUE TITLE
Centrifuge/ crafttweaker bug and flower with apotheosis bug

### ISSUE THREAD

**Issue by Joshernoob** [Team-Resourceful/ResourcefulBees#71]
Both bugs are in file bellow 
[latest.log](https://github.com/Resourceful-Bees/ResourcefulBees/files/5539759/latest.log)

**Comment by Epic428** [comment]
can you point out the lines where the bugs are located? I can't seem to identify them in the log

**Comment by Joshernoob** [comment]
Seems i put in the wrong log and have already reloaded the game when i did so ill try to remeber the best i can on what the errors said

first was 'Centrifuge recipe missing unable to load recipes" with "crafttweaker:error recipe not working" above

second was "Resourceful-Bees, flower recipe, missing flower" this was after the code of apotheosis changing vanilla blocks like reeds and poppies.

**Comment by Epic428** [comment]
Yeah I would need the log with the error and the crafttweaker scripts. Sounds like the recipe wasn’t created properly.
