### ISSUE TITLE
Custom Bee issue

### ISSUE THREAD

**Issue by ElvenWhiskers** [Team-Resourceful/ResourcefulBees#74]
Okay, so im working on my OWN modpack, and i'd like to add my own custom bee's, so i'm following along with you're blaze bee tutorial. I literally copy and pasted what you had in a Blaze.json file next to all other bee's. Its the only one i added. (because i'm testing to learn). The Added bee is completely gray, theres no honey comb item in JEI and it isnt having any drops via apiary. It just pops into it and then gets out with nothing inside. 
Also, i made the en_us.json and that isnt working either.

**To Reproduce**
1. Add Blaze.json with copy and pasted code from |create new bee wiki".
2. make en_us.json, with blaze info via wiki.
3. load world to test(super flat, peaceful.)
4. Bee is wrong color/wrong name, no drops.

**Expected behavior**
Blaze colored bee.. called blaze bee, that drops blaze honeycomb

**please complete the following information:**
 - Forge Version: 1.16.4 - 35.1.1
 - Mod Version: 0.5.5b

![Errorbee pic](https://user-images.githubusercontent.com/52249807/99920584-63dec000-2cd9-11eb-877e-fbc0b406cfe2.png)

**Additional context**
It wont let me upload .jsons so if you'd like i can save as a text file and upload,

**Comment by Epic428** [comment]
I’m going to assume that you followed the wiki that’s accessible from our curse page. I have to alter the links and finish transferring the docs over. For mod versions post 1.16.1 use this json template instead.

https://resourceful-bees.readthedocs.io/en/1.16.3/data_templates/bee_template/

 It should also help with the Lang issue but if you still have any issues let me know.

**Comment by ElvenWhiskers** [comment]
Thank you so much! I'll look into it now and see if i can get the blaze bee working. Thanks for getting back to me so quick! I appreciate it!

**Comment by Epic428** [comment]
No problem. That link is for the master template containing every possible option available in the jsons. You don’t have to fill everything out. There’s links on the left side of the page that breaks each section down and covers what’s required as well as when and why.

**Comment by Epic428** [comment]
We’re you able to get this working so I can close the issue?

**Comment by ElvenWhiskers** [comment]
Yes, Thank you so much.

**Comment by Epic428** [comment]
You’re welcome! If you have any other issues let us know! I’ll close this :)
