### ISSUE TITLE
JEI-Resourceful bee bug

### ISSUE THREAD

**Issue by asterisman** [Team-Resourceful/ResourcefulBees#76]
**Describe the bug**
I m using the JEI mod to see the breeding recipes of your bees. When i do so the game crashes this is happening only in your mod 

**To Reproduce**
1. Go to 'JEI menu '
2. Click on 'random bee'
3. Then the game crashes

**Expected behavior**
I expected to just show the breeding recipes

**Screenshots**
![2020-11-24_15 08 12](https://user-images.githubusercontent.com/74962435/100098825-3e7fbc80-2e67-11eb-9dfe-e7a434d50bc8.png)

**please complete the following information:**
 - Forge Version [e.g. '1.16.3 - 35.1.3']
 - Mod Version [e.g. ['1.6.3-0.5.5b']]

**Comment by ThatGravyBoat** [comment]
Please provide a crash log as this isnt happening for me.

**Comment by allout58** [comment]
If this is from the AllTheMod's 6 Pack, it is an issue with ElementalCraft

https://github.com/Sirttas/ElementalCraft/issues/17

**Comment by asterisman** [comment]
yea it is i just saw your comment "Just ran into this too, appears to be a bug with ElementalCraft, see #371"

**Comment by Epic428** [comment]
Do we know if this has been fixed since it’s an issue in another mod?

**Comment by ViRb3** [comment]
Yes, it's been fixed. The problem was ElementalCraft crashed on any item that doesn't have standard crafting recipe in JEI. You can close this issue.
