### ISSUE TITLE
Enderbee leaves apiary on missing path.

### ISSUE THREAD

**Issue by DarkDon** [Team-Resourceful/ResourcefulBees#79]
1. Place endstone
2. put chorus flower on top
3. watch enderbee sometimes not getting on top of chorus 
4. enderbee couldn't find the path and teleports outside of apiary / beehive containment

**Expected behavior**
Enderbee should not be able to teleport or at least should not teleport if path was missing.
Really annoying to catch the little sucker. 

Modpack: All the mods 6 Vers. 1.16.4
Mod Vers: resourcefulbees-1.16.3-0.5.5b.jar

**Comment by Epic428** [comment]
I have a fix in dev that should eliminate the teleportation issue.

**Comment by Vaerys-Dawn** [comment]
Fixed in dev, apiaries now stop ender bees from teleporting in a 5 block radius

**Comment by Vaerys-Dawn** [comment]
Fixed in dev, apiaries now stop ender bees from teleporting in a 5 block radius

**Comment by Porcy** [comment]
Not sure if it's the same issue, but it kinda looks like:
Resourceful Bees 1.16.5-0.10.7, 
Enigmatica 6 Expert 1.3.0
ender bees teleporting even if in range of a bee nest. (It says they should not teleport when within 10 blocks of a hive, I'd assume it also means nests)
