### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by bessiq** [Team-Resourceful/ResourcefulBees#8]
Minecraft Version: 1.15.2
forge-31.2.5
Resourceful Bees Alpha - 0.2.0

Hello!

I'm testing out a bunch of mods on a local world, and my client has crashed a couple times. The crash reports list Resourceful Bees and a getRandomBee(BeeInfo.java:42) event. But I have quite a few mods, so maybe it's some interaction between this one and another. Any thoughts or suggestions are welcome!

Oh, and I have not made any custom bees - all configs are default. And I have seen many of the bees from this mod in the world, e.g. skeleton bee, redstone bee, gold bee, etc.

[crash-2020-05-25_17.47.37-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4678988/crash-2020-05-25_17.47.37-server.txt)
[crash-2020-05-25_14.47.06-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4678989/crash-2020-05-25_14.47.06-server.txt)

Thanks for any help you can provide!

**Comment by Epic428** [comment]
Thank you for reporting! I’ll look into it tomorrow. Looking at the crash report it looks like a quark monster box is ticking at the time of the crash. Will have to double check what that block is. But the method being used for spawning is based on the biome from BOP so it’s more likely some kind of issue with our mod and BOP.

**Comment by Epic428** [comment]
Do you happen to know what biome you were in at the time of the crash? Just curious

**Comment by ThatGravyBoat** [comment]
Also were you by chance in a cave or underground when this happened? or placing a monster box?

**Comment by bessiq** [comment]
Sorry for the late response, but I am not sure what biome I was in. I was above ground though, in creative, just kind of slowly flying through the world checking out world gen. I didn't see a monster box, but I wouldn't be surprised if there were some in the caves below where I was at.

During one of the crashes I do remember a savanna village in view, and I was trying to head towards it. But I don't think I was in a true savanna. Maybe a BoP shrubland or something. I'll be messing around with the pack some more today, and I'll re-enable this mod and try to provide more details.

**Comment by Epic428** [comment]
hmmm well the info is helpful either way. if you come across a way to reproduce the issue or some kind of pattern do let us know. I know @ThatGravyboat did some tests with BoP and the monster box, but was unsuccessful in getting the crash to happen. I'm also currently going through the classes and cleaning up some things, so hopefully one way or another we get this resolved. Will leave the issue open for now. Thank you for your feedback!

**Comment by ThatGravyBoat** [comment]
Did you change any configs in any other mods when this happened?

**Comment by bessiq** [comment]
Yes, I have been changing quite a few configs as I try to balance the world gen, mob spawns, and other things. To be fair, there is quite a bit of goofy stuff going on in this pack at the moment (I'm sure you noticed the mod list). And I am by no means a pack dev, but just a guy with an IT background that loves modded Minecraft.

I'd hate for you to go down a rabbit-hole of troubleshooting if these errors are false positives - even in my limited experience, I've seen Minecraft blame a random mod for a crash, and it end up being something else entirely. But I will keep providing info until you tell me to stop! :)

The main mod configs I've been adjusting are:
- Lycanites: lowering spawn rates globally, and lately blacklisting the Overworld.
- Apotheosis - deadly module: lowering spawner/boss chances, or trying to anyway. Can never figure out how to disable certain random spawners completely. I do know I haven't seen any bees listed in the random spawner list.
- Project: Vibrant Journeys: lowering world gen of all the various ground cover, trees, bugs, etc.

Here's a couple more crash reports, fwiw:
[crash-2020-05-26_22.15.23-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4689293/crash-2020-05-26_22.15.23-server.txt)
[crash-2020-05-26_17.27.37-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4689294/crash-2020-05-26_17.27.37-server.txt)

**Comment by Epic428** [comment]
Out of curiosity any chance for a twitch export?

I’d like to see what happens in action and try to figure out what it might be.

I can also include a new jar of the mod to test. It has a bunch of extra null checks in for quite a few things. The default bees get modified a bit though due to testing an interesting feature.

**Comment by bessiq** [comment]
Sure, here's the export:
[test-1.0.0.zip](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4690465/test-1.0.0.zip)

Just included mods, configs, and defaultconfigs. I can include other folders/files if you like. And keep in mind these configs are changing pretty frequently. Not sure if the export indicates it, but I've disabled InControl due to some crashes when going to a couple mod dimensions. It's completely unconfigured so not sure what it's doing.

And I can try the new jar if you like. :)

**Comment by Epic428** [comment]
Awesome thanks! I have a jar to test. 

[resourcefulbees-0.2.1a.zip](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4690946/resourcefulbees-0.2.1a.zip)

**Comment by bessiq** [comment]
Hello again,

I tested the jar you provided a bit on Wednesday, and enabled it again today. Unfortunately, I am still getting crashes with it enabled. These are at least clean crashes and provide a crash report; I've had a fair share of instances where the game stops responding (with this mod disabled), and I usually have to kill the Java process and pore through the latest.log. These other crashes almost always occur when I am teleporting to, or already in, a non-vanilla dimension, whereas the crashes I have with Resourceful Bees enabled are always in the Overworld - usually fairly early on, before I've done much exploring or dimension switching. If it helps, the latest crash happened when I was entering a Mushroom Fields biome. I saw quite a few Resourceful Bees and some Mooshrooms; and then it crashed.

One thing I have noticed is that once I do find Resourceful Bees, there seems to be a lot of them - usually at least 10 or more in the same chunk or adjacent chunks. Even if I change the config to the lowest values for weighting and min/max bee groups, it seems like multiple groups are spawning very close to each other. But I have been around a bunch of these bees and not crashed, and crashed with no bees in sight. So it might not be relevant to the crashing issue, but would be nice to reduce their numbers a bit more if desired. :)

Considering the staggering number of mods I am trying to get to play nice together, I still don't think these awesome little bees are totally to blame. If I get time, I might throw this mod into a well-known pack made by _real_ modpack devs, like Enigmatica 5 or ATM5, and see how it goes. I just wanted to provide an update since you've been helpful and responsive to my issue. Thanks again!

fwiw:
[crash-2020-05-27_15.50.42-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4703907/crash-2020-05-27_15.50.42-server.txt)
[crash-2020-05-27_19.23.40-server.txt](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4703908/crash-2020-05-27_19.23.40-server.txt)

**Comment by ThatGravyBoat** [comment]
Is this happening on a server also if it is happening on a server is it also happening on client.

**Comment by bessiq** [comment]
Client only. I frequently create fresh worlds for testing.

**Comment by Epic428** [comment]
I’ve been working 12hr days last couple days. Haven’t had a chance to test the twitch export yet. I’m off for the next week so I will play around with it. If I can at least get the error to consistently generate then I can start pulling mods a handful at a time and see if the errors disappear. I’ll also be adding in custom texture support and modifying bee traits as well. So this week I plan on pushing a new update to curse. I can also modify the bee spawning configs a bit as well so less bees spawn. Once I get nest generation in place the normal spawning may be modified even more.

**Comment by bessiq** [comment]
Cool, sounds exciting! You'll definitely have a broad range of mods to test against with my export. 😄

**Comment by Epic428** [comment]
I got the crash to occur when using the twitch export and a newer mod version. I added some try/catch statements to the methods to collect data in the logs and see what’s coming back null. It happened in a beach biome for me and the monster box was ticking at the time it crashed. But it’s failing when trying to select a random bee from the spawnable biome list. My guess is a biome value is coming back null for some reason despite a null check being performed When the list is being created. So hopefully I can get more data and figure what’s goin on.

**Comment by bessiq** [comment]
I started having different crash errors since disabling RBees, and many led back to Vampirism. I've had Vamp disabled for a day, and crashes are practically gone. (Not counting my experiments with InControl configs!) I also removed the gun mod because it's come up in a couple crash reports, and I just wasn't really feeling it anyway.

I'm going to re-enable RBees soon and see how it goes, and wanted to reply in case you wanted to disable Vampirism for testing also. I've seen at least one other report of Vampirism causing this out of bound chunk error (in the Project: Vibrant Journeys' CurseForge comments iirc), so idk if it's trying to query every entity in existence to see if it can make it a vampire or what. It's probably unrelated to the bees, but Vampirism has got some weird mechanics to it. I did notice many of the entities (vampires, bats, even sheep) in the vampire forest also have super long NBT strings for their names.

Anyway, thanks for your continued effort!

**Comment by Epic428** [comment]
No worries I was able to discover more information as well and I'm adding an additional null check. I'm also moving the loading order for the bees to see if perhaps that will help. But I was able to regularly get the crash while flying around and trace it back to where the null value is. Just not really sure how or why the value is null in the first place, or rather why the bee spawn is being requested.

**Comment by Epic428** [comment]
[resourcefulbees-0.2.2a.zip](https://github.com/Dungeon-Derps-Development/ResourcefulBees/files/4707180/resourcefulbees-0.2.2a.zip)


Here is a new test jar for you. WARNING: This is an experimental build with new Bee Data. If you have created any custom bees they will cause errors unless the jsons get updated. specifically "color" is now honeycombColor, there are two other new color value as well: "primaryColor", and "secondaryColor". Anyway I flew around for a long while and was unable to produce any more crashes with this jar.

EDIT: I should also note I have not yet tested this jar with physical separation of server/client and there's been some modifications to client/server syncing. It's still heavily in the testing phase atm before I can commit and push a new version to curse.

**Comment by bessiq** [comment]
Hey,

Resourceful Bees seems to be crash-free with the new jar you provided. The only minor things I noticed are a "default" bee spawning (only seen once), and the baby "coal" bees are not coal-colored (naturally spawned and with the spawn item). Can't wait to start making some custom bees soon!

![2020-05-31](https://user-images.githubusercontent.com/7315505/83424543-89f66800-a3fa-11ea-9bb2-50f8588ee24a.png)
![2020-05-31 (1)](https://user-images.githubusercontent.com/7315505/83424545-8b279500-a3fa-11ea-9b31-52ff7c613bfa.png)

**Comment by Epic428** [comment]
Yeah the coal bees were from me messing around with the custom texture and 2-color options. They will go back to normal for release. The default bee is an intended effect. That bee would have been the bee that caused the crashes before. It should follow normal logic and eventually get removed. If not I may have change it to the “default-remove” bee instead

**Comment by Epic428** [comment]
OK fixed the issue with the default bee, was a discrepancy in character case.

**Comment by bessiq** [comment]
Hi again,

Still no RBee-related crashes to report! I do have some other questions, but let me know if it would be better to start a different issue. Basically, I am trying to customize the existing bees and make some new ones. I've been using your great wiki, but having mixed results. I can provide more info in this or another ticket. Just let me know!

**Comment by DrDarkfire** [comment]
Just for tracking purposes if you could open a new issue that'd be sick :)
