### ISSUE TITLE
Placing the Apiary in the top of the multiblock

### ISSUE THREAD

**Issue by mkaito** [Team-Resourceful/ResourcefulBees#80]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to be able to embed my apiaries in the ground. For this to work, I would like to be able to put the apiary block in the "roof" of the multiblock.

**Describe alternatives you've considered**
Not doing that, I guess.

**Additional context**
None

**Comment by Epic428** [comment]
I’ll have to think about this one for a little while.

**Comment by mkaito** [comment]
I just realized that I can put the apiary storage anywhere, including somewhere in the top, and use it to access the bee import interface with the tabs on the right. That will do for me.
