### ISSUE TITLE
JEI search for `$valid_apiary` returns no results

### ISSUE THREAD

**Issue by mkaito** [Team-Resourceful/ResourcefulBees#81]
**Describe the bug**
The guide book says that any block with the tag `valid_apiary` can be used to build an apiary. I expected that to be searchable via JEI.

**To Reproduce**
1. Go to JEI
2. Search `$valid_apiary`
3. Observe zero results

**Expected behavior**
A list of blocks that I can use to build an apiary

**Screenshots or Crash Logs**
![image](https://user-images.githubusercontent.com/20434/100923323-ebe17880-34d6-11eb-9cb1-7b9fc298ac88.png)

**please complete the following information:**
 - Forge Version 1.16.4-35.1.4
 - Mod Version 1.16.3-0.5.5b

**Additional context**
All The Mods 6 modpack

**Comment by Epic428** [comment]
Jei doesn’t display block tags. I have an item tag in dev to fix it. But it won’t show all possible blocks Bc not all block tags have an item tag variant.

**Comment by mkaito** [comment]
Is there any other way to get a list?

**Comment by Epic428** [comment]
```json
{
  "replace": false,
  "values": [
    "resourcefulbees:t1_apiary",
    "resourcefulbees:t2_apiary",
    "resourcefulbees:t3_apiary",
    "resourcefulbees:t4_apiary",
    "resourcefulbees:apiary_storage",
    "resourcefulbees:apiary_breeder",
    "#minecraft:wool",
    "#minecraft:planks",
    "#minecraft:sand",
    "#minecraft:logs",
    "#minecraft:doors",
    "#minecraft:stairs",
    "#minecraft:slabs",
    "#minecraft:walls",
    "#minecraft:leaves",
    "#minecraft:trapdoors",
    "#minecraft:fences",
    "#minecraft:ice",
    "#minecraft:coral_blocks",
    "#forge:dirt",
    "#forge:end_stones",
    "#forge:fences",
    "#forge:glass",
    "#forge:glass_panes",
    "#forge:gravel",
    "#forge:netherrack",
    "#forge:obsidian",
    "#forge:ores",
    "#forge:sand",
    "#forge:sandstone",
    "#forge:stone",
    "#forge:storage_blocks",
    "#forge:fence_gates",
    "minecraft:bricks",
    "minecraft:farmland"
  ]
}
```

That’s our tag list by default. However you can add more through data packs

**Comment by mkaito** [comment]
Thank you!
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by mkaito** [comment]
I came across [this issue on JEI](https://github.com/mezz/JustEnoughItems/issues/2004) that suggests searching for block tags should be possible somehow.

**Comment by Epic428** [comment]
Hmm perhaps it’s the jei version? Our block tag is added the same way as every other tag so assuming jei is working properly then ours should work as welll

**Comment by mkaito** [comment]
Searching for other block tags, such as Botania's `terraformable` doesn't yield any results for me either. I'm using the latest version of JEI on 1.16.4. I think it just doesn't allow searching for block tags period, and the implication in the linked issue is just wrong. After all, JEI is all about items and their recipes. It just so happens to a lot of items have the same tags as the blocks they become when placed. So I suppose the only real way around this is to add item tags to everything.

**Comment by Epic428** [comment]
Yeah that’s been my gripe for a while. Block tags should automatically come with an item tag variant. But ultimately that’s up to us modders to handle Bc forge couldn’t be bothered to do something good/useful for once.

**Comment by mkaito** [comment]
I would argue that it's probably better for us to automate adding both tags than Forge forcing the assumptions that they should be the same, but that's just my personal opinion.
