### ISSUE TITLE
Allow glowstone in the apiary structure

### ISSUE THREAD

**Issue by mkaito** [Team-Resourceful/ResourcefulBees#82]
**Is your feature request related to a problem? Please describe.**
You need to light up the interior of an apiary, to avoid hostile spawns. A convenient way to do this would be to put glowstone in the corners, with glass as the walls. Unfortunately, glowstone is not an allowed apiary block.

**Describe the solution you'd like**
Allow glowstone in the apiary structure

**Describe alternatives you've considered**
Placing lights inside the structure is the most obvious alternative.

**Additional context**
None

**Comment by Epic428** [comment]
I will add it to the default tag list. Thank you for letting me know about it 🙂
