### ISSUE TITLE
Config for bees dropping their honeycomb on death

### ISSUE THREAD

**Issue by Taccio33** [Team-Resourceful/ResourcefulBees#83]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
As in the title it would be neat if the bees drop their honeycomb on death, possibly with a configurable rate (as a percentage) so to stop this mekanic from beeing abused.

**Additional context**
So to why is that I'm working on a personal modpack and I thought it should have been in the game, and + this gives a chance to get something from the bees in the star of the game, when you don't have the infrastructure to properly cultivate them.

**Comment by Epic428** [comment]
There’s some code currently in the mod for an alternative use from killing bees. It’s still very WIP and only the beginning of it has been added.

Essentially there will be a custom pollen system that operates similarly to how bee customization works. Basically killing a bee after it has pollinated a flower will yield a type of pollen based on the flower the bee pollinated from. This pollen can then be crafted into various fertilizers that will only work on certain flowers. Or the pollen can be used in a brewing stand to create different potions.

**Comment by Epic428** [comment]
The dev that was adding the custom pollen system stopped working on it and the code has since been stripped from the mod. There *may* be a new system to replace it eventually but dropping combs on death doesn’t make sense since bees don’t carry honeycombs but rather produce them in the hives. I’m going to close this for now.
