### ISSUE TITLE
[Request] Bee prefers to flowers

### ISSUE THREAD

**Issue by KhanhPham05** [Team-Resourceful/ResourcefulBees#87]
**Describe **
Bees are should prefers with some types of flowers. For example: Lapis Bee loves some flowers that have blue colour. When they come to a flower that they loves, they will produces faster and more honeycomb.

**Additional **
 add a JEI tab that listed which flowers they loves with < bee and a hearth > icon

**Comment by Epic428** [comment]
Jei does show what flowers a bee likes. It’s in the flowers category. Also bees are customizable and as such they can be customized to use any particular flower you like.
