### ISSUE TITLE
Tier 2 Beehive eats all my bees??

### ISSUE THREAD

**Issue by SgtMorrigahnGaming** [Team-Resourceful/ResourcefulBees#88]
Set up 4 tier 2 beehives, add in 20 bees. As soon as they enter any of the hives, they are gone.
Have scraper in a dispenser beside, having campfire below.

Worked fine with Tier 1 hives... but not after upgrading them to tier 2.

How to reproduce:
Make tier 2 hive, add bees, wait for them to enter the hive, they are gone.

Tested with 35 bees... no one left to tell the tale...

Forge 35.1.13
Resourceful bees resourcefulbees-1.16.3-0.5.5b.jar
Minecraft 1.16.4

**Comment by SgtMorrigahnGaming** [comment]
Turns out that beehives change direction when one set them into another block. Bees apparently suffocated. 
Please ensure the beehives small line that indicate the opening, actually faces out ( you NEED a block under )

**Comment by Epic428** [comment]
Just a note for reference. If you sneak when placing a hive it will place it facing the opposite direction
