### ISSUE TITLE
centrifuge does not work on world/server load

### ISSUE THREAD

**Issue by Pdiddy973** [Team-Resourceful/ResourcefulBees#89]
**Describe the bug**
When loading into a world, the multi block centrifuge will not work with AE2 import/export buses until you interact with them

**To Reproduce**
1. load world with centrifuge  automated
2. open centrifuge  and it will show no items going in/out such as combs/bottles/comb products
3. once you open the input/export bus connected to the centrifuge it should start working

**Expected behavior**
should not need to check on centrifuges every time i need to load my world/restart server

**please complete the following information:**
 - Forge Version [35.1.13]
 - Mod Version   [0.5.5b]

**Comment by Epic428** [comment]
That’s likely an issue with ae2 itself but I’ll have to look into it. We use the normal item handler capability that pretty much every mod uses for pipes and whatnot so it should work.

**Comment by Pdiddy973** [comment]
wasn't sure if it was an AE issue or not, its not to bad now that i know why it wasn't working after it loading for awhile. but i play on a server so i don't need to load the world very often

**Comment by Epic428** [comment]
Chunk loading is a good intermediary measure on servers for now

**Comment by Vaerys-Dawn** [comment]
Unable to repro
