### ISSUE TITLE
Bee's causing issues in the nether

### ISSUE THREAD

**Issue by nobotious** [Team-Resourceful/ResourcefulBees#92]
I don't pretend to know all that much about java, but I've been sort of chasing down an issue thats been causing heavy lag.

I have a spark profile linked, I can't seem to get this to crash a server, it seems to eventually recover.

100% of the server thread being used by a single bee entity lol. 

https://spark.lucko.me/#eAGBreYBc7

server running allthemods 6 - 1.3.7
resourceful bees 1.16.3 - 0.5.5b
anyone else experiencing this? I've tried really hard and I've been able to reproduce it a couple of times by flying through the nether hella fast and watching for my tps to drop, and stopping in the area where it starts to.

not sure if this is an interaction between the bee's pathing, and something another mod introduced, or even vanilla bee behavior. honestly not sure lol.

**Comment by ThatGravyBoat** [comment]
I looked at the spark profile and it doesn't seem like anything we're doing is directly causing the lag. The part where it's using the most performance is the basic movement mechanics for all entities so it's likely another mod causing this issue.

**Comment by nobotious** [comment]
Alright, makes sense. Its always been on a bee entity (not blaming the mod), and I've been able to make it happen a number of times. I may try to reproduce without other mods, and maybe with BYG - as it modified the nether terrain in the pack. Kind of an up in the air issue. Thanks for taking a look!
