### ISSUE TITLE
I get honey comb from resourcefull nests or teir 1 beehives. Lclick and Rclick do nothing. Both are full of honey visually. Playing 1.16.4 all the mods 6

### ISSUE THREAD

**Issue by servireettueri** [Team-Resourceful/ResourcefulBees#99]
If this is about a specific bee please report to the pack dev as we do not create bees we just give tools to pack devs.
If you do report a "bug" that is about a specific bee or set of bees it will be instantly closed due to it most likely being
an issue with the bees that pack devs added themself and not our code.
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Crash Logs**
If applicable, add screenshots or crash logs to help explain your problem.

**please complete the following information:**
 - Forge Version [e.g. '1.15.2 - 31.2.5']
 - Mod Version [e.g. '0.2.0']

**Additional context**

**Comment by Vaerys-Dawn** [comment]
Can you please check /config/resourcefulbees/common.toml for `allowShears = true` if false, you need to use the scraper added with the mod.
